### ISSUE TITLE
sosač+befun

### ISSUE THREAD

**Issue by cmarek** [mx3L/archivczsk#10]
Nedá sa pridat záložka na konkretny film-chýba položka pridat do založiek.
Dakujem.

**Comment by mx3L** [comment]
Polozka pridana, treba pockat na novu verziu

**Comment by mx3L** [comment]
Pridavam verziu na test, zalozky by mali fungovat aj pre filmy
https://www.dropbox.com/s/w2rhqkku15qvoe7/enigma2-plugin-extensions-archivczsk_0.73-20161025_all.ipk?dl=1

**Comment by mx3L** [comment]
pre-release verzia 0.74 s moznostou pridat zalozky aj pre videa pridana
