### ISSUE TITLE
Nejde doplnek iVysilani - Ceska televize

### ISSUE THREAD

**Issue by mivi2266** [mx3L/archivczsk#100]
Zdravim, chtel bych se zeptat, zda by mohl nekdo opravit iVysilani CT, nejde jiz nejakou dobu.
Predem dekuji

**Comment by manmatej** [comment]
Ahoj, ani u mě to nefunguje už cca 14 dní. Aktualizoval jsem, přeinstaloval vše ale stále nejde. Sám nedokážu ale rozlousknout v čem to vězí. Prosím opravte kdo to dokážete. Díky.

**Comment by mivi2266** [comment]
Je to tedy mrtvá záležitost? Nikdo to již nepoužívá? Autorem je Štěpán Ort Verze má označení 1.3.6.
Rád bych přispěl, pokud to umíte někdo opravit.

**Comment by misanov** [comment]
Aktuálně jsem opravil, připravuje se release, poté zaktualizujte.
