### ISSUE TITLE
Nejde doplněk Drtinová Veselovský TV

### ISSUE THREAD

**Issue by mivi2266** [mx3L/archivczsk#101]
Mohl by prosim nekdo opravit tento doplnek? Predem moc dekuji.

**Comment by mivi2266** [comment]
Je to tedy mrtvá záležitost? Nikdo to již nepoužívá? Autorem je Štěpán Ort. Verze má označení 1.2.3.
Rád bych přispěl, pokud to umíte někdo opravit.

**Comment by misanov** [comment]
Jo, je tam drobná chybička, opravím, jestli to tedy ještě někdo používáte a nepřispěli jste jinam :relaxed:

**Comment by misanov** [comment]
Vyřešeno novým alpha releasem v1.3.0 s addonem Aktualne.cz, který obsahuje DVTV.
