### ISSUE TITLE
 Neaktualizují se seznamy pořadů v doplňku Stream TV Archiv

### ISSUE THREAD

**Issue by mivi2266** [mx3L/archivczsk#103]
Zdavím, již nějkou dobu se neaktualizují seznamy pořadů v tomto pluginu. Autorem je Jiří Vyálek verze 1.2.2. Mohl by se na to prosím někdo kouknout? Předem moc děkuji.

**Comment by misanov** [comment]
Zkoušel jsem a vypadá to ok, zavírám.
