### ISSUE TITLE
Aktualizácia archivCZSK na premium

### ISSUE THREAD

**Issue by ganco47** [mx3L/archivczsk#104]

**Comment by hitman222** [comment]
http://ab-forum.info/viewtopic.php?f=468&t=74033
Prečítaj si tuto stranku.


   1. Pripojite sa na box cez ftp napr. cez TotalComander
   2. Skopirujete adresar


   1. Pri obnove najskor naistalujete ipk balicek a teda
   2. Nasledne prepisete odzalohovany adresar v boxe a vykonajte restart.


út 25. 2. 2020 v 12:02 odesílatel ganco47 <notifications@github.com> napsal:

**Comment by ganco47** [comment]
ďakujem veľmi pekne

Dňa st 26. 2. 2020, 14:23 hitman222 <notifications@github.com> napísal(a):
