### ISSUE TITLE
Nespravne prihlasovacie udaje - sledovanietv

### ISSUE THREAD

**Issue by xpeti** [mx3L/archivczsk#105]
Nemohu zadat udaje pro doplnek sledovanietv. Na ceske klavesnici si to pridava mezery, na anglicke se to tvari OK, ale nefunguje. Je moznost zeditovat primo soubor? Kdyz zedituju /usr/lib/enigma2/python/Plugins/Extensions/archivCZSKpremium/resources/repositories/plugin.video.sledovanitv/resources/settings.xml, tak se zmeny neukazou v doplnku. 

Diky

**Comment by misanov** [comment]
Sledovanitv v našem repozitáři není, ale plánuji ho, to je na premium, musíš poslat dotaz tam.
