### ISSUE TITLE
Chyby v Prima, Nova, iVysilani a Stream Cinema

### ISSUE THREAD

**Issue by misanov** [mx3L/archivczsk#106]
Pravděpodobně nikdo na tomto projektu nedělá. Přepsal jsem plugin Prima, Nova a iVysilani. Dodělal pár feature pro sebe, které samo poskytnu. Teď opravuji Stream Cinema dle Kodi. Mohu vám to sem commitnout nebo mám založit nový projekt? Byla by škoda toto ukončit. Já s Pythonem nemám problém a vše v klidu upravuji. Nikomu nevadí, že to nejede?

**Comment by misanov** [comment]
Stream Cinema opraveno také.

**Comment by PeterPetrech** [comment]
Cauko. Mne to nejede. Zaujima ma StreamCinema. Vies poradit ako tie tvoje opravene veci nainstalovat do enigma 2. Dik

**Comment by misanov** [comment]
No pokud se vyznáš v daných souborech pluginu na linuxu, tak v scinema.py vyhledej řádek:
        `if itm['provider'] == 'plugin.video.online-files': #and itm['params']['cp'] == 'webshare.cz':`
a změň na:
        `if itm['provider'] == 'plugin.video.online-files' or itm['provider'] == 'webshare':`
To by k fungování mělo aktuálně stačit, i když jsem tam udělal více úprav.

**Comment by lachyn** [comment]
Ahoj, ja myslim ze forkem nic nepokazis, urcite by spousta lidi ocenila i tu opravu  iVysilani atd. :)

**Comment by misanov** [comment]
Připravím zítra, vlastně už dnes, commit pro archivczsk-doplnky a pošlu to tam.

**Comment by lachyn** [comment]
Obavam se, ze to nikdo necomitne. Posledni, kdo se o to staral, nakonec udelal fork a zpoplatnil aktualizace. Pokud to chces Tvou praci nasdilet, zrejme budes muset forknout do noveho repo.

**Comment by PeterPetrech** [comment]
Dakujem za upravu. Funguje. Dobra praca.

**Comment by hitman222** [comment]
Ahoj,dá se někde stáhnout instalační soubor ipk?

**Comment by JanoD79** [comment]
Super pomoc misanov. Díky. Máš niekde komplet súbor na stiahnutie. Som tu nový.

**Comment by lachyn** [comment]
> Připravím zítra, vlastně už dnes, commit pro archivczsk-doplnky a pošlu to tam.

@misanov  pokud to puvodni autor necommitne, udelas prosim ten fork?
Kdyby jsi se taky podelil o nejake tipy jak jsi to napr. debugoval, tak bych se taky pridal, aby to jako open-source neumrelo. Napr. jestli ty skripty jdou nejak pokusne spoustet na PC, nebo to upravujes rovnou v prijmaci.
Diky.

**Comment by matko1976** [comment]
Super práca. Ďakujem, že sa nájdu aj ľudia, ktorým to nedá spať.

**Comment by milis222** [comment]
Moc dobrá práce, jen tak dál.

**Comment by kralikportos** [comment]
Ahoj,jak se vám projevuje ta nefunkčnost?Nevím jestli mám stejný problém.Já když zapnu film tak to jen problikne a jsem zpět u volby filmu.Díky za odpo.

**Comment by lachyn** [comment]
pro opravu iVysilani staci nakopirovat
[https://github.com/kodi-czsk/plugin.video.ivysilani/blob/master/ivysilani.py](url)
do
`/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/resources/repositories/custom/plugin.video.ivysilani/resources/lib/ivysilani.py`

**Comment by mx3L** [comment]
@misanov ako si napisal vytvor prosim pull request na archivczsk-doplnky a commitnem. diky

**Comment by misanov** [comment]
Chlapi, nestíhám, hodím pull během zítřka do doplňků. Snad to ještě umím, naposledy jsem to dělal před asi 4 lety :-D. Vydržte!

@lachyn podělit se můžu, ale tady v issues mi to přijde divné, dělám to na linuxovém serveru, ale určitě se dá i klidně na dreamboxu, kde vlastně to prostředí už je. Parsuji stránky v developer modu. Něco vytáhnu jen z kodi, abych věděl jak to funguje, atd.

Ohledně toho forku zpoplatněného, no upřímně mi přijde dělat něco nelegálního a ještě si za to nechat platit je právně dost o hubu nejen pro něj, ale i pro ty co to zaplatí, páč ho v tom vlastně podporují. No známe to ;-). A ještě k tomu to má zkompilované, takže si v tom člověk nemůže dělat úpravy dle svého, což je k prdu.

Jinak se o to rád budu starat, aby to fungovalo, tedy minimálně o to, co používám sám, Nova, Prima, iVysilani a SC.

**Comment by mtester270** [comment]
Uprimne drzim palce nech vam ten elan vydrzi. Ja som za ten dlhy cas co som tu ma mal one man show pocuval v 98% len pindy a podobne.

GL&HF

@misanov: a co si cakal ze to necham neskompilovane? Kolko rokov mas praxe 😉

**Comment by misanov** [comment]
Jak píšu, minimálně se postarám o to co používám, páč to chci aby fungovalo, nemám pak problém to poskytnout dál.

Nevím jestli to byla otázka, ale letos to už bude 20 let praxe 8-). Ale začínal jsem na takových prkotinách jako opravy kernelu linuxu.

@mx3L máš to tam v obou repozitářích, snad je to ok, je to můj bastl, ale funguje to ;-)

**Comment by mtester270** [comment]
@misanov tak stara skola 😉, uz vam chyba len to aby to ponuklo online update vsetkym co to pouzivaju lebo stylom ze tu si to stiahni a prekopci moc ludi nadsenych asi nebude.

**Comment by vatlach** [comment]
@misanov 
Pozrel by si sa aj na markiza.sk plugin?

**Comment by lachyn** [comment]
@mtester270  ja myslim, ze kdo chce, tak si to stahne a kdo to nezvladne, tak se proste poohledne jinde. Dulezite na tom je, ze si tyhle informace lide vubec nasdili, to je myslim cely princip open-source. Treba se nakonec rozjedou i ty aktualizace, co muzes vedet ;)

**Comment by misanov** [comment]
Jo jo, však já taky využívám plno opensource, taky čas od času někomu pošlu malou finanční podporu, ale mám to rád a jsem za to vděčný, tak proč být jiný, není to nic komerčního. Automatické aktualizace můžeme taky vymyslet, to není nic složitého. Upřímně, by to chtělo hodně rewritu, uvidíme.

@vatlach no ten je úplně o ničem, to chce rewrite, koukal jsem do kodi a je nový, tak časem vyměníme. Já ho nepoužívám, ale zkusím mrknout.

Teď už bych to tu asi uzavřel, když budou chyby, požadavky, apod. tak pište spíše do doplňků na https://github.com/mx3L/archivczsk-doplnky/issues. Díky.

**Comment by misanov** [comment]
@lachyn hele, to ivysilani přímo kopírovat z kodi sice jde, ale je to trošku jiné (hází chyby), já doopravím ten náš, tedy už je, ale ještě jsou tam drobnosti co chci upravit, teď jsem to udělal jen aby šel.

**Comment by mtester270** [comment]
@misanov nie rewrite ale postudovat a spravne nastavit publikaciu. To ty ale zvladnes. 
Z bohom.

**Comment by mx3L** [comment]
teoreticky by to mohlo ist teraz cez auto update, dajte vediet ci vam to ide

**Comment by misanov** [comment]
@mtester270 proč ne rewrite? To by se ti blbě pak kopírovalo? Ne, dělám si srandu ;-). Doufám, že to nebudu spravovat jen sám, další se určitě přidají, já si budu dělat hlavně to své, co používám, a o tom to je, každý dělá něco co umí nebo co chce aby fungovalo, a hlavně teď má každý plno času v období sezení doma.

@mx3L zkusím večer až všichni vypadnou od tv ;-)

**Comment by mtester270** [comment]
@misanov lebo to tam predsa uz je (veduci ti spravil addony ale da sa aj archiv publikovat). No podla mna ostanes ty a veduci ale bodaj by to tak nebolo uvidite casom.

**Comment by misanov** [comment]
@mx3L auto update proběhl v pořádku, super!

**Comment by mx3L** [comment]
parada :)

**Comment by mx3L** [comment]
Este jedna vec, urobil som update na 1.2.3 tak tiez by sa mala aktualizovat verzia archivov. Tak prosim tiez nejake echo ci to zbehlo alebo nie, vdaka

**Comment by misanov** [comment]
Jo, u mě aktualizováno v pohodě. Já jsem verze pluginů ani neměnil, natož changelog, jak jsem to dělal pro sebe ;-). Možná by stálo zato vyhodit nefunkční, respektive nepoužívané, pluginy, je toho tam fakt hafo.

**Comment by george4830** [comment]
Aktualizace na 1.2.3 proběhla v pohodě super práce díky moc.

**Comment by milis222** [comment]
Aktualizace v poho, vše funguje. Velká gratulace.

**Comment by hitman222** [comment]
Mne po aktualizaci seka stream cinema ,video 1.35 GB,internet O2 100 MB,Zero 4K,posledni OpenPLI.
casovy limit RTMP 20,RTMP zasobnik 10000 ms

**Comment by misanov** [comment]
@hitman222 zkus to v jinou dobu, je možné, že mají zatíženou síť, oni to na ws furt píšou, mě to občas dělá také, nic systémového se nezměnilo, jen parse url. Teď jsou zkoušel přes mobilní síť 30 Mbps 1080p video 2,3 GB a jede to ok. Zkoušej a dej vědět.

**Comment by hitman222** [comment]
@misanov tak všechno OK,tak jak píšeš,něco na webshare.
