### ISSUE TITLE
Stream-Cinema 

### ISSUE THREAD

**Issue by hitman222** [mx3L/archivczsk#108]
Ahoj,v stream cinema kdyz pustim serial Sinner po 10 sekundach se sekne,neslo by do nastaveni pridat zmenu prehravace jak je to u premium verze,tam pomohlo zmenit na GstPlayer.
Diky moc.

**Comment by misanov** [comment]
Já tam seriál Sinner vůbec nevidím, jen film The Sinner, tak nezkusím :(

**Comment by hitman222** [comment]
tak se mrkni na Hrisnice. Mam Zero4K posledni OpenPLI 7:2,vcera jsem zaplatil premium a u serialu Ti,co vrazdi zase jde jen zvuk a na UNO 4K vsechno stejne jako Zero jde vsechno.

**Comment by misanov** [comment]
Zaplatil jsi premium čeho? ws? nebo kra? nebo archivu? Nicméně dnes jsem to zkoušel a taky se mi to sekne, řešením je používat exteplayer3 jako default přehrávač v enigmě, což aktuální release neumí, ale bude umět v budoucnu, případně si to můžeš nastavit jestli umíš, nainstalovat v modulech serviceapp, exteplayer3 a v nastavení serviceapp ho nastavit jako default, restartovat, a jede, neseká.

**Comment by hitman222** [comment]
Zaplatil jsem Archiv CZSK Premium ale zase nejede Ti,co vrazdi jede jen zvuk,to service app mam nainstalovany,musim mrknout jak to nastavit defaul,nekde to tam najdu?

**Comment by misanov** [comment]
No jo, ale tady to není o Premium, tady jsme free verze, to musíš hlásit na https://github.com/mtester270/archivczskpremium/issues

**Comment by hitman222** [comment]
To,já vím,premium jsem platil vcera na zero na uno uz to mam od zacatku.

**Comment by hitman222** [comment]
Právě že na UNO 4K to šlo po změně playeru tak jsem psal jestli by to nešlo i tady.
