### ISSUE TITLE
stream cinema nefunkcny

### ISSUE THREAD

**Issue by sinacik** [mx3L/archivczsk#109]
caute od 3.5 00:00 prestal ist stream cinema. Na zero a uno4kse vti14 nacita pismeno obsahu a none? Ma este niekto podobny problem?

Diky

**Comment by sinacik** [comment]
Ani kody nenacita nic ;(

**Comment by L0th4r** [comment]
Přesne jak pisete :)

**Comment by Ciksa** [comment]
Mladenci, kedze autor uz odstrihol webshare tak musite bud prejst na kra.sk alebo pokial sa to "nevyvrbi" vyuzit docasne zluzby nejakeho ineho pluginu, napriklad Soubory Online .

**Comment by L0th4r** [comment]
Diky za info ;)

**Comment by sinacik** [comment]
Soubory Online neviete plz kde sa uklada meno a heslo? Je tam chyba ked to zadam cez nastavenia tak mi tam vzdy prida medzeru a potom to neautorizuje.. S tym webshare som celkom spokojny. Vdaka

**Comment by Ciksa** [comment]
Skus hodit ockom do /etc/enigma2/ na subor settings.

**Comment by misanov** [comment]
Mám jisté řešení jak to zprovoznit, ale ještě čekám na jistá vyjádření.

Ohledně Souborů online, víme o tom, opravuje se. Jak píše Ciksa, v settings změnit na správný a pak tvrdý reset satu, jinak se to obnoví ze spuštěné enigmy.

**Comment by sinacik** [comment]
Super, rozbehal som, upravil som heslo na webshare a dal som zaň "  " dve medzery a ide to.. za posledny tyden do toho webshare riadne operuju.. pockame na update diky pani

**Comment by psstastny** [comment]
jak do pluginu pridat kra alebo ako presmerovat z webshare loginu na kra

**Comment by Ciksa** [comment]
Musis pockat bud na novu verziu alebo na novy plugin.

**Comment by L0th4r** [comment]
Na XBMC uz se resi novy doplnek SC2 mozna nazev jiny, doufam, ze bude do budoucna i na E2 ;)

**Comment by Ciksa** [comment]
SC2 je zatial len takym "provizoriom". Mas tam Filmy a Serialy ale mozes len vyhladavat alebo pouzit radenie podla pismena A-Z. Daj tomu cas, ono sa to urcite popravi. Aj pani Janosikova tak vravela Jurovi a vydis, mala pravdu. :-D

**Comment by hitman222** [comment]
Ahoj,jak to vypada, pojede to jeste pres webshare?
Dík

**Comment by misanov** [comment]
Ano, teď zatím bude jen alpha SC2, pracuji teď na betě.

**Comment by sinacik** [comment]
Prihlasujem sa ako 🗡️ Beta tester, ak to bude možné :D , tie serialy online, od štvrtka 7.5 úplne zlyhanie zmiznlo mi tam 3/4 obsahu, nefiltruje to zip koncovky archívov 001,002, je to ďakujem.. Tak zatiaľ som dal sosáč, ten chodí..

**Comment by mtester270** [comment]
ked chces betatestovat tak si stiahni prekopci a testuj teda ak to tam ma misanov aktualne 👍 
https://github.com/mx3L/archivczsk-doplnky/tree/master-next/plugin.video.sc2

otazne je ci to zvladnes :-)

@misanov ak som ti ten link nemal zverejnit tak to kludne vymaz

**Comment by misanov** [comment]
@sinacik @mtester270 Klidně to může vyzkoušet, pravděpodobně se zítra nebo pozítří alpha již zruší, nebude pro ni dostupné api, a půjde jen beta, na které dělám, ale teď zatím alpha jede, tak si klidně můžete hrát, kdo to umíte ;). Proto jsem to tu zatím nezavřel.
