### ISSUE TITLE
Zalozky Manazer, Nastavenie zhodia prijmac

### ISSUE THREAD

**Issue by pangi** [mx3L/archivczsk#11]
Ahoj,
mam Vu+ Duo2 s image VTI. Plugin funguje, streamuje, ale ked chcem zobrazit Nastavenie alebo Manazer doplnkov, zhodi mi to cely prijmac, zamrzne, cierna obrazovka. Nutny tvrdy restart (vypnut prijmac tlacitkom). Kde by mohol byt problem?
https://www.dropbox.com/s/59orpvw3tdiq8sc/dvbapp2_crash_1476947355_2016-10-20_09-09-15.log?dl=0

**Comment by mx3L** [comment]
Ahoj, plugin vytvaram na Openpli image. VTI image pozmenil signaturu funkcie parseSize v skin module preto to pada.
Pridal som malu upravu ktora by mala detekovat VTI image a prisposobit argumenty tak aby odpovedali parseSize funkcii vo VTI image.

V prilohe je posledny build je tam viacero zmien ale zaujima ma len ci menu uz funguje.

Dakujem

https://www.dropbox.com/s/zooo42bfjbqpuqo/enigma2-plugin-extensions-archivczsk_0.73-20161020_all.ipk?dl=1

**Comment by pangi** [comment]
Manzer uz v pohode, ale Nastavenie stale pada.
https://www.dropbox.com/s/omtifdskcpohfh9/dvbapp2_crash_1477001441_2016-10-21_00-10-41.log?dl=0

**Comment by mx3L** [comment]
Skus teraz
https://www.dropbox.com/s/9zjjh9xdkd8is4f/enigma2-plugin-extensions-archivczsk_0.73-20161021_all.ipk?dl=1

**Comment by pangi** [comment]
Som do nedele mimo domov, mozem dat vediet az potom..

**Comment by pangi** [comment]
Nastavenie sa uz zobrazi, ale ked chcem upravit nejaku hodnotu, zamrzne.
https://www.dropbox.com/sh/gjthssnih5troty/AAB_ASkFiAz_KOcpavekOxkga?dl=0

**Comment by mx3L** [comment]
https://www.dropbox.com/s/szcp4fudpcw8hvf/enigma2-plugin-extensions-archivczsk_0.73-20161024_all.ipk?dl=1

**Comment by pangi** [comment]
Ano, teraz uz funguje. 
Dalej este mrzne pri streamovani (sosac) po stlaceni tlacitka Audio na ovladaci.

**Comment by mx3L** [comment]
U mna na openpli funguje, poprosim o log
![audio](https://cloud.githubusercontent.com/assets/3874649/19652590/9594dc42-9a11-11e6-9340-3b346087190d.png)

**Comment by pangi** [comment]
Log som pridal do toho adresara (odkaz vyssie).

**Comment by mx3L** [comment]
Vdaka
https://www.dropbox.com/s/bot6nt62b6jtmrf/enigma2-plugin-extensions-archivczsk_0.73-20161025_all.ipk?dl=1

**Comment by pangi** [comment]
Nepomohlo, log pridany.

**Comment by mx3L** [comment]
ok, budem potrebovat subor AudioSelection.py[oc], mal by byt v /usr/lib/enigma2/python/Screens/

**Comment by pangi** [comment]
Pridal som

**Comment by mx3L** [comment]
https://www.dropbox.com/s/w2rhqkku15qvoe7/enigma2-plugin-extensions-archivczsk_0.73-20161025_all.ipk?dl=1

**Comment by pangi** [comment]
Ano, vsetko funguje. Diky moc!

**Comment by mx3L** [comment]
super, vdaka za info, commit-y pre opravu pridane

**Comment by mx3L** [comment]
0.74 pre-release verzia s opravami pre VTI pridana
