### ISSUE TITLE
Instalacia 1.3.0 z IPK nie je 1.3.0 ale 1.2.3

### ISSUE THREAD

**Issue by Ciksa** [mx3L/archivczsk#110]
# - odkaz na 1.3.0 obsahuje verziu 1.2.3
![0](https://user-images.githubusercontent.com/44697180/81783878-5069c580-94fc-11ea-8f6d-396aee362ad0.jpg)

# - instalacny balik detekuje arm ako mips32el
![1](https://user-images.githubusercontent.com/44697180/81783605-e18c6c80-94fb-11ea-8a87-cbb4f9efbaed.jpg)

**Comment by sinacik** [comment]
Zdravím, 
JJ ale v skutočnosti je to 1.3.0 asi len popis prepísať v kóde tej šablóny.. Skôr väčší problém mi robí SC2 nejde uložiť korektne meno/heslo.. V /etc/e2/configuráku som to nastavil na tvrdo a ide to 💯 .. riadok pre meno som tam dokonca ani nemal, do hesla mi dalo meno a do VIP days doplnilo heslo.. Niektoré písmena vo filmoch mi napísalo aktualizujte plugin, niektoré išli A,C,.. Ešte poskúšam cez weekend.

**Comment by Ciksa** [comment]
No ja skor myslim ze nastala niekde "osibka" a nielen ze sa nejedna o poslednu verziu Archivu ale ani o poslednu verziu SC2.
