### ISSUE TITLE
Archiv CZ/SK 1.3.0

### ISSUE THREAD

**Issue by Janyck1982** [mx3L/archivczsk#111]
Nefunguje nahratie nového archivu do prijimača DM 820,image Dream OS stable OE 2.5 debian,vyjadrite sa kompetentní len verzia 1.2.3 a nefunguje ani update,subbsupport najnovsia verzia 1.5.7

**Comment by misanov** [comment]
Mělo by být opraveno v nové verzi 1.3.1. Pokud je to ok, může se toto issue zavřít.

**Comment by Janyck1982** [comment]
Takže funguje konečne tá verzia 1.3.1 hlavne SC 2,vďaka za dobre odvedenú prácu nemohol som sa dočkať

**Comment by peter771** [comment]
Pošlite mi instalacku

Dňa št 14. 5. 2020, 0:03 Janyck1982 <notifications@github.com> napísal(a):

**Comment by Janyck1982** [comment]
Dajte si tam verziu archivu cz/sk 1.2.3 a prijimač Vás automaticky vyzve,ak vstúpite do archívu 1.2.3 je dostupná aktualizácia 1.3.1,Prajete si aktualizovať,Dáte áno,Prijímač Vás upozorní na reštart asi 3 krát po sebe a nainštalujú sa aj aktualizované pripadne nové doplnky

**Comment by misanov** [comment]
@peter771 poslední instalačka je zde https://github.com/mx3L/archivczsk/releases/tag/v1.3.1

**Comment by peter771** [comment]
Už to mám to vyhľadávaní filmov vylepšia či to bude také slabé?sc1 bol lepsi

Dňa št 14. 5. 2020, 10:35 Michal Novotný <notifications@github.com>
napísal(a):
