### ISSUE TITLE
Stream Cinema 2 - Error

### ISSUE THREAD

**Issue by polachz** [mx3L/archivczsk#112]
Nainstaloval jsem 1.3.1 verzi doplnku, restart enigmy.  Pak pokus o prehrani z cehokoliv pres SC2 hlasi 

[chyba archivu]
autor jej musi opravit.

Nevim, zda jde o chybu WS, SC2, nebo neco generictejsiho. Urcite mohu nahrat logy, pokud date info kde rostou.

Diky !

**Comment by peter771** [comment]
Funkčné by to malo byť do dvoch tyzdnov

Dňa st 13. 5. 2020, 23:58 Zdenek Polach <notifications@github.com>
napísal(a):

**Comment by peter771** [comment]
Pošlite mi stiahnuť instacku ipk archív CZ sk

Dňa st 13. 5. 2020, 23:58 Zdenek Polach <notifications@github.com>
napísal(a):

**Comment by polachz** [comment]
Instalaci jsem provadel takto:

opkg install http://github.com/mx3L/archivczsk/releases/download/v1.3.1/archivczsk_1.3.1-20200513.ipk

A to 2x, podruhe jsem to zkusil jeste pred zadanim bugu. Download corruption archivu bych asi vyloucil

Vypada spise, ze pomohl dalsi restart, ted uz to jede. Zadaval jsem login/pass pro WS.. Ale nerebootoval.

**Comment by peter771** [comment]
Škoda že to není také vyhľadávanie filmov ako na sc1

Dňa št 14. 5. 2020, 8:27 Zdenek Polach <notifications@github.com>
napísal(a):

**Comment by misanov** [comment]
@peter771 > Funkčné by to malo byť do dvoch tyzdnov

Co by mělo být funkční do dvou týdnů? Archiv nám normálně běží již několik dní v pořádku.

**Comment by misanov** [comment]
@polachz takže rozchozeno? Můžeme uzavřít toto issue?

**Comment by peter771** [comment]
Myslím zoradenie podľa žánrov a je tam oveľa menej filmov ako na sc1

Dňa št 14. 5. 2020, 10:39 Michal Novotný <notifications@github.com>
napísal(a):

**Comment by peter771** [comment]
Ide mi to ale je tam menej filmov a zle sa to vyhľadáva.sc1 bol lepsi

Dňa št 14. 5. 2020, 10:40 Michal Novotný <notifications@github.com>
napísal(a):

**Comment by misanov** [comment]
@peter771 ohledně funkčnosti a porovnání starého a nového sc neporadím, musíte se obrátit na sc2.zone, my spravujeme pouze archivczsk

**Comment by misanov** [comment]
@peter771 jinak můžete použít placenou verzi https://github.com/mtester270/archivczskpremium, kde si ještě zaplatíte přístup na kra a pak vám bude fungovat staré sc1. My už staré sc1 nepodporujeme.

**Comment by peter771** [comment]
Stačí zaplatiť kra.a tie prihlasovacie údaje s kra vpisat do sc1 a pôjde to?

Dňa št 14. 5. 2020, 10:49 Michal Novotný <notifications@github.com>
napísal(a):

**Comment by misanov** [comment]
@peter771 Snad ano, to už musíte řešit v issues na https://github.com/mtester270/archivczskpremium, to my neprovozujeme.

**Comment by peter771** [comment]
Na obyčajnom archíve a nie premium to pôjde?či musí byť premium?

Dňa št 14. 5. 2020, 10:53 Michal Novotný <notifications@github.com>
napísal(a):

**Comment by misanov** [comment]
My nepodporujeme sc1 ani kra, z archivu ho již brzy smažeme.

**Comment by peter771** [comment]
Čo vlastne od vás ide?

Dňa št 14. 5. 2020, 11:17 Michal Novotný <notifications@github.com>
napísal(a):

**Comment by misanov** [comment]
Stáhněte si a vyzkoušejte.

**Comment by peter771** [comment]
Koľko sa za to platí?mesačne alebo ročne????

Dňa št 14. 5. 2020, 11:32 Michal Novotný <notifications@github.com>
napísal(a):

**Comment by misanov** [comment]
Toto není chatovací systém, ale vývojářský systém, přečtěte si pravidla githubu, koukal jsem, že jste mladý nový, tak studujte.

**Comment by peter771** [comment]
Škoda dakujem

Dňa št 14. 5. 2020, 11:45 Michal Novotný <notifications@github.com>
napísal(a):

**Comment by polachz** [comment]
@misanov Vypada, ze ano. Asi nejaky problem s funkcnosti doplnku po cerstvem zadani WS udaju. To mi pripomina, ze kdyz jsem zkusil zobrazit seznam filmu uplne bez zadani udaju na WS, tak cely doplnek vytuhnul a musel jsem rebootovat. Ale da se rici, ze reboot je funkcni lecivo na vsechny me potize, zatim. NA to jak rychle se SC2 dostalo do distribuce je to skvele. Diky ;)

**Comment by peter771** [comment]
Aj mne ide SC 2 len je malý výber chyba položka najnovšie dabovane a novo
pridané.

Dňa št 14. 5. 2020, 18:43 Zdenek Polach <notifications@github.com>
napísal(a):

**Comment by kostik12345** [comment]
Dobrý deň, pridáte prosím aj dokumenty.tv?
