### ISSUE TITLE
DM920

### ISSUE THREAD

**Issue by pe3kf** [mx3L/archivczsk#113]
Zdravím, 
nainštaloval som do /tmp 
enigma2-plugin-extensions-subssupport_1.5.7-20200421_all.deb
a potom
archivczsk_1.3.1-20200513.deb
ale v plugine sa archív nezobrazil , je tm iba subssuport.
tak som skúsil starší link  cez putty:
dpkg -i http://github.com/mx3L/archivczsk/releases/download/v1.1/archivczsk_1.1-20180623.deb
ale tiež neberie
dpkg: error processing archive http://github.com/mx3L/archivczsk/releases/download/v1.1/archivczsk_1.1-20180623.deb (--install):
 cannot access archive: No such file or directory
Errors were encountered while processing:
 http://github.com/mx3L/archivczsk/releases/download/v1.1/archivczsk_1.1-20180623.deb
čo može byť problém.

Dík

**Comment by 005jon** [comment]
pokiaľ si tam mal starý archivczsk tak ho treba odinštalovať

**Comment by pe3kf** [comment]
nie nemal , nanovo som flashoval nový image

**Comment by 005jon** [comment]
do /tmp  prekopiruj archivczsk_1.3.1-20200513.deb

telnet:

apt-get update
apt-get -y -f install curl
apt-get -y -f install python-json
dpkg -i /tmp/*.debe
apt-get -y -f install

**Comment by peter771** [comment]
Ja to robím cez usb

Dňa št 14. 5. 2020, 21:11 pe3kf <notifications@github.com> napísal(a):

**Comment by 005jon** [comment]
tak to daj cez telnet

**Comment by peter771** [comment]
To je čo cez čo?

Dňa št 14. 5. 2020, 22:41 005jon <notifications@github.com> napísal(a):

**Comment by 005jon** [comment]
SSH telnet

**Comment by peter771** [comment]
Aleš čo to je nechápem ta

Dňa št 14. 5. 2020, 22:48 005jon <notifications@github.com> napísal(a):

**Comment by pe3kf** [comment]
> apt-get -y -f install

skúsil som podla tvojho návodu cez putty , ale nič ...

root@dm920:~# dpkg -i /tmp/*.deb
(Reading database ... 17558 files and directories currently installed.)
Preparing to unpack .../archivczsk_1.3.1-20200513.deb ...
Unpacking enigma2-plugin-extensions-archivczsk (1.3.1) ...
dpkg: error processing archive /tmp/archivczsk_1.3.1-20200513.deb (--install):
 trying to overwrite '/CONTROL/control', which is also in package enigma2-plugin-extensions-subssupport 1.5.7-20200421
dpkg-deb (subprocess): subprocess decompressing archive member was killed by signal (Broken pipe)
dpkg-deb: error: subprocess <decompress> returned error exit status 2
Errors were encountered while processing:
 /tmp/archivczsk_1.3.1-20200513.deb

**Comment by pe3kf** [comment]
dal som hladať ...ale nič, iba picony naň

root@dm920:~# find / -name *archiv*
/var/cache/apt/archives
/tmp/archivczsk_1.3.1-20200513.deb
/autofs/mmcblk1p1/hdg17_files/menuIcons/1/archivy_czsk.png
/autofs/mmcblk1p1/hdg17_files/menuIcons/1/archivy_czsk_premium.png
/autofs/mmcblk1p1/hdg17_files/menuIcons/1/archivy_czsk_premium_stream_cinema.png
/autofs/mmcblk1p1/hdg17_files/menuIcons/1/archivy_czsk_premium_search.png
/autofs/mmcblk1p1/hdg17_files/menuIconsBig/archivy_czsk_premium_search2.png
/autofs/mmcblk1p1/hdg17_files/menuIconsBig/archivy_czsk2.png
/autofs/mmcblk1p1/hdg17_files/menuIconsBig/archivy_czsk_premium2.png
/autofs/mmcblk1p1/hdg17_files/menuIconsBig/archivy_czsk_premium_stream_cinema2.p                   ng
/usr/lib/python2.7/distutils/archive_util.py
/usr/lib/python2.7/distutils/tests/test_archive_util.pyc
/usr/lib/python2.7/distutils/tests/test_archive_util.py
/usr/lib/python2.7/distutils/archive_util.pyc
/usr/lib/python2.7/site-packages/youtube_dl/extractor/archiveorg.pyc
/usr/lib/python2.7/site-packages/youtube_dl/extractor/internetvideoarchive.pyc
/usr/lib/python2.7/site-packages/youtube_dl/extractor/internetvideoarchive.py
/usr/lib/python2.7/site-packages/youtube_dl/extractor/archiveorg.py

**Comment by peter771** [comment]
Daj archív premium 1.3.1

Dňa pi 15. 5. 2020, 15:27 pe3kf <notifications@github.com> napísal(a):

**Comment by peter771** [comment]
Potom za zazreg.na kraj.sk ja som to robil cez usb

Dňa pi 15. 5. 2020, 15:27 pe3kf <notifications@github.com> napísal(a):

**Comment by peter771** [comment]
Podarilo sa?

Dňa pi 15. 5. 2020, 15:27 pe3kf <notifications@github.com> napísal(a):

**Comment by pe3kf** [comment]
archív premium nie je 1.3.1 trochu to máš popletené.

ale skúsil som aj teda premium archivczskpremium_1.0-12122019.deb
a ten mi nainštalovalo , ale cez z tmp cez putty príkazom to nešlo:
root@dm920:~#  dpkg -i https://github.com/mtester270/archivczskpremium/releases/download/v1.0.0/pyt                                hon-pycrypto_2.5-r0.4_armhf.1.deb
dpkg: error processing archive https://github.com/mtester270/archivczskpremium/releases/download/v1                                .0.0/python-pycrypto_2.5-r0.4_armhf.1.deb (--install):
 cannot access archive: No such file or directory
Errors were encountered while processing:
 https://github.com/mtester270/archivczskpremium/releases/download/v1.0.0/python-pycrypto_2.5-r0.4_                                armhf.1.deb

 ...zaujímavé, tak kde je teda problém v tom pôvodnom základnom archíve czsk?!


(len info ..premium mám aktívne a kra zaplatené v druhom VU+ boxe )

**Comment by peter771** [comment]
Hej iné čísla ale fakt super kukam od včera SC parada

Dňa pi 15. 5. 2020, 15:58 pe3kf <notifications@github.com> napísal(a):

**Comment by pe3kf** [comment]
Takže dávam sem môj poznatok po xx pokusoch.

archív nechcelo nainštalovať pretože som inštaloval túto verziu subssuport:
enigma2-plugin-extensions-subssupport_1.5.7-20200421_all.deb

ked som nainštaloval nižšiu verziu , tak už všetko OK.

Postup ktorý funguje:
####DM920UHD-####

do /tmp
subssupport_OE2.5_1.5.6-r0.2_all.deb
archivczsk_1.3.1-20200513.deb
reštart.

potom kto chce
archivczskpremium_1.0-20190504.deb
reštart

ak archiv nenabehne alebo je prazdne okno
python-pycrypto_2.5-r0.4_armhf.1.deb
reštart

možno to niekomu pomôže.

**Comment by peter771** [comment]
Už ti to ide?

Dňa pi 15. 5. 2020, 17:28 pe3kf <notifications@github.com> napísal(a):

**Comment by peter771** [comment]
Mám aktívne a zaplatené kraj.sk. s údajmi ficim na Pc cez kodi SC.ok
funguje Linux archív premium stream cinema fičí a 1000x je lepšie ako sc1.

Dňa pi 15. 5. 2020, 17:31 peter najred <peternajred64@gmail.com> napísal(a):

**Comment by peter771** [comment]
Mne to ide aj na ntb aj na linuxe.dakujem vývojárom ste super.podporim
vás!!!!

Dňa št 14. 5. 2020, 21:11 pe3kf <notifications@github.com> napísal(a):

**Comment by lazosk** [comment]
este poznatok z instalacie deb z webinterface DM920 (keca o mipsel32el a hlada OE1.6)

Selecting previously unselected package enigma2-plugin-extensions-archivczsk.
(Reading database ... 22714 files and directories currently installed.)
Preparing to unpack /tmp/tmpG13wpz.deb ...
Unpacking enigma2-plugin-extensions-archivczsk (1.3.1) ...
Setting up enigma2-plugin-extensions-archivczsk (1.3.1) ...
Installation for mips32el platform
Installing pngquant...
Installing neccessary Python libraries
Found Python 2.7
Removing temp folder...
Installation of archivCZSK was successfull
cp: can't stat '/tmp/archivczsk/mipsel/pngquant/OE16/pngquant': No such file or directory

**Comment by pe3kf** [comment]
u mňa stále pretrváva problém, že ked chcem odísť z pluginu , tak zostane na TV svietiť 
správa " kotrolujem aktualizácie" a nič sa dlú dobu nedeje a nedá sa to vypnúť, pomôže až reštart.

len upresním, že mám DM920 oe2.5 Merlin

**Comment by EnoSat** [comment]
> u mňa stále pretrváva problém, že ked chcem odísť z pluginu , tak zostane na TV svietiť
> správa " kotrolujem aktualizácie" a nič sa dlú dobu nedeje a nedá sa to vypnúť, pomôže až reštart.
> 
> len upresním, že mám DM920 oe2.5 Merlin

pozri si log ci nahodou nemas failed update

**Comment by pe3kf** [comment]
myslíš crashlog?
ten nevytvorí, lebo to nejde do zelenáča , ale len box zatuhne a musím ho ručne reštartovať.

**Comment by EnoSat** [comment]
> myslíš crashlog?
> ten nevytvorí, lebo to nejde do zelenáča , ale box len zatuhne a musím ho ručne reštartovať.
> a KODI v.19 čo tam mám, to zase ked vypnem, tak sa box celý sám reštartne.

nie crashlog , ale log cinnosti archivu - FTP pristup ide stale aj ked dialkove nereaguje

**Comment by pe3kf** [comment]
[archivCZSK.log](https://github.com/mx3L/archivczsk/files/4646372/archivCZSK.log)

**Comment by EnoSat** [comment]
2020-05-18 21:29:02,686 - INFO - YoutubeDL::gotResponse: initialized
ak to vytuhlo, tak nestahuje hoci je pripravene na tuto akciu , over si ci mas v boxe curl (pripadne ci je to spravna verzia) , ale tieto zavislosti by ti asi lepsie objasnil **misanov**

**Comment by misanov** [comment]
> [archivCZSK.log](https://github.com/mx3L/archivczsk/files/4646372/archivCZSK.log)
> ...ak z toho niečo vyčítaš , a najdeš riešenie, budem rád.
> Ď.

V logu není žádná chyba, která by něco způsobila. Zkus nainstalovat poslední release a poslední subssupport z https://github.com/mx3L/archivczsk/releases. Možná ještě před init 3 promaž v /etc/enigma2/setting vše co se týká archivczsk, nebo si to zazálohuj a smaž, pak dej init 3.

**Comment by meshuggah6** [comment]
ahojte, 
mozem poprosit o radu. Mam nainstalovany plugin verzia 1.3.1 vo VU+Solo4K  a ked zadam prihlasovacie udaje tak vo VIP mi pise 0 dni. Po otvoreni doplnku vidim kategorie filmy a serialy ale ked otvorim polozku tak sa nic neudeje.Dakujem za radu

**Comment by sinacik** [comment]
Treba mat 1.3.3, odinstalujte a naistalujte, 4x reset a musi sa aktualizovat potom to pojde.. na VTI to ide ako vinko.. Hauk..

**Comment by meshuggah6** [comment]
vychazal som z tejto verzie 1.3.1 a aktualizovala sa na 1.3.3

**Comment by sinacik** [comment]
Tak to mas ok.. skontroluj ci mas dobre meno a heslo mne tam davalo medzeru navyse.. upravil som to v subore rucne cez ftp teda total commander, ulozil a vytiahnut sat z elektriky. Potom to slo..cesta kde je login zapisany.. /etc/enigma2/settings

**Comment by meshuggah6** [comment]
skusil som tvoj postup, ale nepomohlo. Zmenil som si aj prihlasovacie heslo a tiez nepomohlo. Pise chybu: nepodarilo sa stiahnut data zo servru v casovom limite.

**Comment by peter771** [comment]
Ahoj daj tak 4 restarty mne to pomohlo mal som podobný problém daj vediet

Dňa st 27. 5. 2020, 11:18 meshuggah6 <notifications@github.com> napísal(a):

**Comment by meshuggah6** [comment]
ahoj peter771, tak 4x restart prijimaca cez menu a stale VIP 0 dni pri StreamCinema 2.0 a nespusti ziaden film, serial.  :(

**Comment by peter771** [comment]
Máš Linux?máš zaplatené kra.sk?aj zaplatený premium?

Dňa st 27. 5. 2020, 15:58 meshuggah6 <notifications@github.com> napísal(a):

**Comment by meshuggah6** [comment]
Mam Linux. Zaplateny ucet na webshare. Archiv CZ/SK nainstalovany obycajny, nie plateny premium. Doplnok StreamCinema 2.0 je pre webshare ucty alebo sa mylim?

**Comment by peter771** [comment]
Ok takže takto!!!!webshare už nepôjde!!!!!musíš sa registrovať na www.kra.sk
zaplať a  údaje vpis do stream cinema také ako za zaregistrujes na kra.sk a
môžeš pozerať.ked nainštalujem premium tak treba jednorázovo zaplatiť 1.20€
ide to super.na webshare zabudni.fakt ti ide a na czsk premium máš kopec
nových veci ľutovať nebudeš!!!!!

Dňa st 27. 5. 2020, 16:09 meshuggah6 <notifications@github.com> napísal(a):

**Comment by meshuggah6** [comment]
do teraz som pouzival  archiv cz/sk kde je StreamCinema a teraz pribudla StreamCinema 2.0 beta, ktora ma ak som spravne pochopil podporovat webshare ucet. A archiv cz/sk premium ma byt pre kra.Ale asi to tak nieje ako som si myslel. dakujem za info peter771

**Comment by misanov** [comment]
@peter771 je tu takový propagátor kra.sk, nevím jestli je s ním nějak spojený, ale WS samozřejmě funguje v SC2, teď jsem to zkoušel a normálně vše jede, pokud to někomu nejde, může se obrátit na podporu na forum.sc2.zone, pokud někomu nejde archivczsk, může se ozvat tady.

**Comment by misanov** [comment]
> skusil som tvoj postup, ale nepomohlo. Zmenil som si aj prihlasovacie heslo a tiez nepomohlo. Pise chybu: nepodarilo sa stiahnut data zo servru v casovom limite. StreamCinema stary funguje. StreamCinema 2.0 nie

Pokud to píše, že se nepodařilo data stáhnout v časovém limitu, tak je problém na serveru sc2.zone, ono asi jak to používá teď hodně lidí, tak to nestíhá, nevím.

Každopádně staré SC tam také funguje, jen výsledkem není přímo odkaz na video, ale na vyhledání videa, funguje to zatím také dobře.

**Comment by peter771** [comment]
Vyskúšaj premium fakt neolutujes

Dňa st 27. 5. 2020, 17:12 meshuggah6 <notifications@github.com> napísal(a):

**Comment by meshuggah6** [comment]
Ahoj misanov dakujem ti za informaciu. Stary SC mi v funguje iba to vyhladavanie je trochu kostrbatejsie. Chcel som rozchodit SC2.0 a to mi akosi robi problemi. Pisal som aj na fore sc2zone ale mozno som zle popisal problem,lebo som pisal ohladom VIP 0dni. A ten problem s timeout som prikladal tomu,ze mi nezaregistrovalo VIP. 
DAKUJEM TI.Ak by si mal nejaky napad tak napis.

**Comment by misanov** [comment]
No možná by byl dobrý ten log hned poté co se ti to stane. Verzi SC2 máš doufám poslední 2.0.0-beta. Aktuálně ji používá několik tisíc lidí, holt někdo má problém, ale jsou to jednotky lidí.

**Comment by meshuggah6** [comment]
verzia SC2.0 je 2.0.0.-beta, poradili mi, ze je tam bug a nezapise login/password do settings.xml doplnil som ho rucne a stale to iste 
[archivCZSK.log](https://github.com/mx3L/archivczsk/files/4691660/archivCZSK.log)

**Comment by misanov** [comment]
Možná takový hloupý dotaz, ale máš ten box připojený k internetu? V logu totiž je furt blbé neaktuální datum 1970-01-01 01:27:47. Jinak v logu žádná chyba, jen to připojení.

Nevím kde je jaký bug o login/password, ale v /etc/enigma/settings by mělo být něco jako *sc2.wsuser a *sc2.wspass, pokud to chceš změnit ručně, musíš nejdřív shodit enigmu, tj. init 4, pak změnit ten settings, pak spustit enigmu pomocí init 3. Ale nevidím důvod, pokud to zadáváš správně na klávesnici, pak v tom settings to uvidíš správně.

**Comment by meshuggah6** [comment]
ahoj, 
ano je pripojeny k netu. Ten cas som si vsimol, ze dava zly. SC ide v poriadku iba SC 2.0 hlasi ten problem. Tak mozno bude sposobovat ten problem cas. Skusim to vyriesit. Dakujem ti za tvoju pomoc a cas

**Comment by meshuggah6** [comment]
misanov VELKE DAKUJEM. cele ten problem bol v case, nesynchronizovalo ho. Vyriesene. Dakujem

**Comment by EnoSat** [comment]
> > [archivCZSK.log](https://github.com/mx3L/archivczsk/files/4646372/archivCZSK.log)
> > ...ak z toho niečo vyčítaš , a najdeš riešenie, budem rád.
> > Ď.
> 
> V logu není žádná chyba, která by něco způsobila. Zkus nainstalovat poslední release a poslední subssupport z https://github.com/mx3L/archivczsk/releases. Možná ještě před init 3 promaž v /etc/enigma2/setting vše co se týká archivczsk, nebo si to zazálohuj a smaž, pak dej init 3.

v OE2.5 sa neodporuca **init** ale **systemctl**
