### ISSUE TITLE
Octagon sf80084K openatv 6,4

### ISSUE THREAD

**Issue by baaluu** [mx3L/archivczsk#116]
Nefunkcny archiv czsk.pri spusteni po aktualizacii modra smrt.Nejde od 1,3,1.Box s obrazovkou menu archivu zamrzne.Nutny reset boxu.Premium funguje.Potrebujem stream cinema 2,0.Dik za radu.

**Comment by EnoSat** [comment]
rada sa nachadza v logu cinnosti

**Comment by Ciksa** [comment]
Skus si cely Archiv odinstalovat, restartnut box, nainstalovat odtialto poslednu verziu 1.3.1, restartnut box, soustit Archiv a aktualizovat na 1.3.3 co ti ponukne a potom znovu po restarte by ti mal ponuknut okrem inych aj instalaciu SC 2.0.

**Comment by baaluu** [comment]
reinstal a znovu to iste.Na OpenEight 6.7 mi to ide no openatv je krajsie.Prikladam log.
[enigma2_crash_1590343318.log](https://github.com/mx3L/archivczsk/files/4674116/enigma2_crash_1590343318.log)

**Comment by Ciksa** [comment]
Preinstaluj si box.

**Comment by baaluu** [comment]
Dik to nebude problem pokial to pobeží.

**Comment by misanov** [comment]
K tomu crashlogu, máš chybu v settings u nějakého doplňku, viz. Invalid value setting 'auto_addon_order' for addon
