### ISSUE TITLE
DM520 + OE2.2.0 + GP3.3

### ISSUE THREAD

**Issue by EnoSat** [mx3L/archivczsk#12]
Instalacia do DM520 s original image+GP3.3 v poriadku , ale po spusteni doplnku (napr. Sosac) ziadna reakcia ani hlaska + nereaguje na EXIT ani ine (tlacitko HELP vyvola crash , ale len kvoli sherlock pluginu).

**Comment by mx3L** [comment]
Ahoj, 
Mohol by si vytvorit log z enigmy ked nastane uvedeny problem a prilepit ho sem?

**Comment by EnoSat** [comment]
mal som ho tu len par dni , skusim pozriet nejake logy ci sa nieco zachovalo

**Comment by EnoSat** [comment]
nejake pozostatky logov z DM520 a DM900
https://uloz.to/!rita8ky78RCS/archivczsk-zip

**Comment by mx3L** [comment]
po tejto zmene by to mohlo fungovat
https://github.com/mx3L/archivczsk/commit/e0411001d5cfb8929841be864e8ab7c27255360c
