### ISSUE TITLE
Opat Stream cinema comunity nejde, vraj treba update..

### ISSUE THREAD

**Issue by sinacik** [mx3L/archivczsk#122]
Dalsie zlyhanie, scc nejde spustic.. treba update, mame nejaky liek? Danke

**Comment by Hakatitla** [comment]
Potvrdzujem ze nejde.

**Comment by EnoSat** [comment]
Nie kazdy ma cas sediet pri pocitaci 24 hodin a kazdu zmenu previest do "zivota", ked bude mat cas tak to zrealizuje. Kto sa nemoze dockat moze si naistalovat KODI do TV ci BOXu a tam to pozerat.

**Comment by Hakatitla** [comment]
@EnoSat ktory box odporucas?

**Comment by timtimeshock** [comment]
> Nie kazdy ma cas sediet pri pocitaci 24 hodin a kazdu zmenu previest do "zivota", ked bude mat cas tak to zrealizuje. Kto sa nemoze dockat moze si naistalovat KODI do TV ci BOXu a tam to pozerat.

tak  abych  pravdu   řek   že  tu  máme dvě  pískoviště pro  jeden   plugins   se  mne  taky  moc  nelíbí  jedni  si  hrají  v  kodi  a ti   druzí  v  enigma  asi  by  spolupráce  vůbec  neuškodila.Není  třeba   ani  tak  sedět   na  pc 24 hodin  jak  třeba   uživatele  tak  nějak informovat.Myslím že  komunita  v kodi  daleko  lépe  komunikuje jak   třeba  tady což  je   škoda.

**Comment by sinacik** [comment]
Opravené již od piatku.. Ďakujem ste top !

**Comment by sinacik** [comment]
A zase nejde..

**Comment by Ciksa** [comment]
Zas sa neplaste, vsetko ide.

**Comment by sinacik** [comment]
Vam to fakt ide ?

**Comment by Ciksa** [comment]
Samozrejme a preco by nemalo ? Tu mate dokaz.
![1](https://user-images.githubusercontent.com/44697180/90608255-a38d9b80-e202-11ea-9163-5ec217cb0099.jpg)
![2](https://user-images.githubusercontent.com/44697180/90608259-a4bec880-e202-11ea-9b43-bffdc22427e2.jpg)
![3](https://user-images.githubusercontent.com/44697180/90608263-a5575f00-e202-11ea-8224-cd471ed3e50b.jpg)
![4](https://user-images.githubusercontent.com/44697180/90608264-a5eff580-e202-11ea-8748-791344772351.jpg)

**Comment by sinacik** [comment]
Áno už ide ale včera nešiel písalo mi, že si mám aktualizovať plugin.. Dnes dokonca vyhodilo aktualizáciu a už teda ide, som zvedavý ako dlho hádam to vydrží aspoň 7 dní. Pekný deň vespolek.

**Comment by Ciksa** [comment]
Netaraj, ide to v pohode a posledna aktualizacia pluginu SCC na 2.1.13 bola vydana uz pred tyzdnom, konkretne 12.8.

**Comment by sinacik** [comment]
Odborník, včera som to zapol a nešlo, ešte raz napísalo mi že server je nedostupný a mám to aktualizovať.. Naskočila mi až dnes, že sa chce aktualizovať zaktualizovalo a už ide.. O akej neschopnosti tu píšeš??  Si v poriadku? Nemám slov, daj si nejaké lieky na ukludnenie.. 
HAUK

**Comment by Ciksa** [comment]
Chlapce pravidelne tu vyplakavas ze ti to nejde ale pritom je propblem len tvoja hlupost a neschopnost. Ty si daj lieky na kebulku, poriadne ich zalej a mozno ti v nej konecne aspon nieco vypuci.
Ty HAUKac .
howgh

**Comment by sinacik** [comment]
Uprimne ťa ľutujem..Aká nechopnosť keď to nevyhodilo aktualizáciu? :D Bohužiaľ som systémový administrátor a robím to 20rokov na rozdiel od teba chlapče.. Takéto slová si nechaj pre svoje zrkadlo degeš

**Comment by Ciksa** [comment]
Chlapecku, na rodiel od teba som skutocne viac ako 25 rokov robil pre velku strojarsku nadnarodnu spolocnost Administratora. Ty chujko pocmarany a neschopny si mohol leda tak s prstom v nose stat pred uradom prace. :-D

**Comment by sinacik** [comment]
Takto sa vyjadruje RETARD a nie inteligetný človek je môj názor.. A budem rád ak moje články nebudeš komnetovať.. Uži si svoj chorý život máš to ťažké..

**Comment by Ciksa** [comment]
Tajtrlik, preco mam pri tebe dojem, ze mas vymenene usta za zadok ? To bude asi tym, ze ak by si bol este o nieco hlupejsi, tak uz by ta stacilo len polievat, tak asi dva krat do tyzdna.  :-D
