### ISSUE TITLE
Okno aktualizace se nezobrazuje

### ISSUE THREAD

**Issue by maciii** [mx3L/archivczsk#123]
Ahoj, na OpenATV 6.4, VU+ Zero 4K. Instalace verze 1.3.5. Po zapnutí doplňku to nezobrazí okno s aktualizací doplňků, vše jede ale při opuštění doplňku se objeví okno "Kontrola aktualizací" a z toho už se nedá dostat ven a je nutná tvrdý restart boxu. Zda se že tam je nějaký trabl.

Workaround: nainstalovat verzi 1.3.1, update doplňků a následně i ArchivCZSK na 1.3.5. Provede to navíc i instalaci "demjson??" - ten název si nevybavuju přesně. Možná tohle tam chybí?

**Comment by misanov** [comment]
Bez crashlogu těžko zjistit co se zaseklo. Je třeba zkusit mačkat několikrát exit, měl by se zaseknout a restartovat.
