### ISSUE TITLE
Nezobrazuje popis filmov

### ISSUE THREAD

**Issue by matadon02** [mx3L/archivczsk#124]
Dobry mam vu zero open atv 6.4 pouzivam cinema stream comunity a j sosac a pri oboch mi nezobrazuje popis filmu. Neviete mi prosim poradit. Dakujem

**Comment by misanov** [comment]
Zapnout si v globálním nastavení archivu zobrazení popisu filmů?

**Comment by matadon02** [comment]
To mam asi v 10 % to zobrazuje inal nie

**Comment by misanov** [comment]
Nevím jestli tento problém stále trvá, ale pokud to někdy jde a někdy ne, tak je to divné. Možná problém při stahování dat. Pomalost/chybovost linky. V logu nejsou nějaké chyby?

**Comment by matadon02** [comment]
Dobry problem je v tom ze nezobrazi popis len nejake cislo vid priloha je
tam cislo 12272

**Comment by misanov** [comment]
Bohužel tady na githubu se asi příloha nepřidává, nic tu není :-(. Možná jste to poslal mailem, což asi nejde, netuším.

**Comment by peter771** [comment]
Ahoj zmizol mi s menu stream cinema prečo?

Dňa št 26. 11. 2020, 16:57 Michal Novotný <notifications@github.com>
napísal(a):

**Comment by misanov** [comment]
Closed for inactivity.
