### ISSUE TITLE
V nastaveniach doplnkov nefunguju sipky :(

### ISSUE THREAD

**Issue by Gugi25** [mx3L/archivczsk#125]
Nefunguju vsetky 4, HORE, DOLE, VLAVO, VPRAVO a neda sa tak pohybovat v nastaveniach ani hore ani dole. Napisat do prveho riadku nejaky text cez klavesnicu sa da.
Robi to len v nastaveniach, ked uz idete v niektorom z doplnkov vyhladavat, to funguje korektne.

Ine pluginy su OK. Image mam OpenVix 5.4. V starom 5.3 to bolo OK.
Keymap.xml pluginu archivczsk mam rovnaky ako vtedy, ked mi to na starsom image islo.

Neviete niekto, co s tym ?

**Comment by misanov** [comment]
Evidentně je něco špatně/jinak v nové verzi Image. Bohužel ji vůbec neznám, tak neporadím. Snad jedině, pokud nepotřebujete novou verzi, tak se vraťte k 5.3.
