### ISSUE TITLE
DreamboxOne DreamOS 2.6

### ISSUE THREAD

**Issue by miro350** [mx3L/archivczsk#126]
Dreambox One DreamOS 2.6 -subsupport i archiv naistalovat i aktualizovat jdou, spustit se vsak z archicvu neda nic, okamzite green screen, log prikladam
[archivCZSK.log](https://github.com/mx3L/archivczsk/files/5995059/archivCZSK.log)

**Comment by misanov** [comment]
V tomto logu je jen chyba TA3, která je již opravena. Pokud ale spadne na green celý box, pak je třeba přiložit crash log, většinou je v /home/root

**Comment by miro350** [comment]
ok, crashlog prilozen
[enigma2_crash_1614706375.log](https://github.com/mx3L/archivczsk/files/6070625/enigma2_crash_1614706375.log)

**Comment by kajost** [comment]
Mam tiez ten box a tiez archiv nefungoval dobre, kazdopadne som objavil premium verziu a tam to ide bez problemov (vid. google).

**Comment by misanov** [comment]
Je tedy problém již vyřešen?

**Comment by miro350** [comment]
> Je tedy problém již vyřešen?

urcite ne, tento archiv v OE 2.6 nefunguje porad

**Comment by misanov** [comment]
Podle crashlogu archiv spuštěn byl a spadl až při přehrávání filmu z scc kvůli titulkům. Je to tak?

Pokud problém přetrvává, tak zde to někdo již vyřešil http://www.ab-forum.info/viewtopic.php?f=468&t=75781

**Comment by miro350** [comment]
> Podle crashlogu archiv spuštěn byl a spadl až při přehrávání filmu z scc kvůli titulkům. Je to tak?
> 
> Pokud problém přetrvává, tak zde to někdo již vyřešil http://www.ab-forum.info/viewtopic.php?f=468&t=75781

ano, titulky a na tom odkazu, to je vse vetsinou pro OE 2.5, pro OE 2.6 proklate malo rad :-)

**Comment by misanov** [comment]
Bohužel nemám možnost to testovat, nemám tento box, tak fakt neporadím. Snad něco vymyslet se subssupportem, který tam právě padá.

**Comment by misanov** [comment]
Je tento problém již vyřešen?
