### ISSUE TITLE
SCC servery mají problémy

### ISSUE THREAD

**Issue by jmalir** [mx3L/archivczsk#127]
Zdravím,
prosím o pomoc s řešením problému u SCC doplňku.
Některé filmy či jiné položky fungují, ale často se ukáže hláška, že SCC servery mají problémy.
Zkoušel jem to u OpenAtv i OpenPli, je to stejné.
Zjistil jsem, že v informacích o přehrávači je chyba u HTTP protokolu. viz. obrázek.
Přikládám i log
![1613821731577](https://user-images.githubusercontent.com/9347162/108594618-50480180-737b-11eb-902e-5e4328da7144.jpg)
[archivCZSK.log](https://github.com/mx3L/archivczsk/files/6014882/archivCZSK.log)
Děkuji za pomoc.

**Comment by misanov** [comment]
Pokud to někdy jde a někdy ne, tak je to bohužel těžké reprodukovat.

Informace o přehrávači již je k ničemu, já tam např. mám u všeho FAIL a funguje to. Tuto stránku v budoucí verzi odstraníme.
