### ISSUE TITLE
nefukcny ucet Vip

### ISSUE THREAD

**Issue by asfyx** [mx3L/archivczsk#128]
logoch mam blok sc2 provaidera vip ucet bol na 365 dni a od 364 dna je blok...panko co stym...hlaska na ucte je ze furt niekto stahuje...dik za kazdu odpoved...webshare.cz neodpoveda ...na nic...eurace maju na ucte a ja mam blok...ahoj

**Comment by sinacik** [comment]
Skús tie loginy zadat do streamcinema1, reset boxu. Potom som rucne zadal loginy do sc2 cez ftp a sranda ide mi SC a aj SC2 na loginoch webshare..

**Comment by asfyxnew** [comment]
> Skús tie loginy zadat do streamcinema1, reset boxu. Potom som rucne zadal loginy do sc2 cez ftp a sranda ide mi SC a aj SC2 na loginoch webshare..

vies je to enigma2 log dava spolu do tmp jeden je ako archivczk a druhy ako cinema

**Comment by asfyx** [comment]
> Skús tie loginy zadat do streamcinema1, reset boxu. Potom som rucne zadal loginy do sc2 cez ftp a sranda ide mi SC a aj SC2 na loginoch webshare..

do akej zlozky to kopirovat a kde

**Comment by sinacik** [comment]
Najskor som rucne zadal udaje do stream cinema, zacal mi chodit a potom rucne sem.. Ulozit, rst boxu a zapni nieco, naskocia VIP days a malo by to ficat.. este skus zmenit si heslo do uctu ak ti to nepojde
etc/enigma2/settings user a pass som dal..

config.plugins.archivCZSK.archives.plugin_video_stream-cinema.wsuser=
config.plugins.archivCZSK.archives.plugin_video_stream-cinema.wsvipdays=304
config.plugins.archivCZSK.archives.plugin_video_stream-cinema.deviceid=
config.plugins.archivCZSK.archives.plugin_video_stream-cinema.wspass=

**Comment by asfyx** [comment]
dik za rady,mne vip a prihlasenie ide,len ked prejdem na ponuku filmy  v stream cinema community  mi napise ze neukaze link na spustenie cez vip ak vip vypnem ide ake seka obmedzena rychlost...par kilo...mam net 300 bezne ide do250,v doplnku na vip to iste a  doplnku soubory online pise ze prilis vela stahujem...a vyhodi ma...uz 10den vip dnes je 355...ak som pozeral stranku webshare.cz v nastenke vidim 2 linky online...neda sa urobit s nimi nic ani v PC link cliente.ach joo...dik za rady...

**Comment by asfyx** [comment]
> dik za rady,mne vip a prihlasenie ide,len ked prejdem na ponuku filmy v stream cinema community mi napise ze neukaze link na spustenie cez vip ak vip vypnem ide ake seka obmedzena rychlost...par kilo...mam net 300 bezne ide do250,v doplnku na vip to iste a doplnku soubory online pise ze prilis vela stahujem...a vyhodi ma...uz 10den vip dnes je 355...ak som pozeral stranku webshare.cz v nastenke vidim 2 linky online...neda sa urobit s nimi nic ani v PC link cliente.ach joo...dik za rady...

![weshare](https://user-images.githubusercontent.com/79698625/109493791-49ad3e80-7a8d-11eb-9559-a22f238b7fca.jpg)

**Comment by sinacik** [comment]
No a ked si zmenis heslo do websharu? uz ho asi odlogujes toho druheho..

**Comment by asfyx** [comment]
dik za radu to som skusal ako prve,a nic

**Comment by asfyx** [comment]
potreboval by som od websharu aby mi to jejak v syteme vymazali ach joo

**Comment by asfyx** [comment]
dakujem ti za pomoc aj teamu webshare podpore uz sa da pozerat cez enigmu2 appku,este nejde download na HDD ale cex PC Fon to ide...este raz dik

**Comment by asfyx** [comment]
nie len mi poslali email.

**Comment by misanov** [comment]
Předpokládám, že to tedy byla chyba někde mezi vámi a webshare, takže se může tato issue uzavřít.

**Comment by asfyx** [comment]
vies neviem posudit,ked nic neslo...teraz nejde len stahovanie u teba v appke,vies stiahol som si film a urobil som si playlist a bolo vybavene islo to po sebe...inak prispievam aj na appku...dik znamim dopracem setop boxi urobi sa ucet a je klidek pokial to ide ak nejde volaju jak by bol koniec sveta...ahoj
