### ISSUE TITLE
sosac, befun vecer a cez vikend pomale

### ISSUE THREAD

**Issue by corey66** [mx3L/archivczsk#13]
Poslednych par dni mam vecer a cez vikend problem s prehravanim videi zo sosaca a befun (ine zdroje som neskusal), cez den mi rychlost streamu ide pekne cez 1MB a vecer a cez vikend to vzdy padne na cca 100kB, rychlost internet pripojenia je stale stabilna
Pretazeny server?

**Comment by mx3L** [comment]
Ano asi to bude tak, mam podobne skusenosti
