### ISSUE TITLE
ta3 archív

### ISSUE THREAD

**Issue by gregory1970** [mx3L/archivczsk#130]
Neviete prečo nejde archív TA3 ?

**Comment by Sedo77** [comment]
Nazdar. Zistil si niečo? Ani mne nejde uz dlho a neviem sa nikde dočítať preco a neviem na koho sa obrátiť s tym problémom. Dik

**Comment by gregory1970** [comment]
tieto vecičky rieši tuším Misanov. Posielal som mu SZ cez iné fórum ale neozval sa tak neviem čo ďalej.

**Comment by Sedo77** [comment]
Ok, diky.kaslem na to 🙂hadam to opravia

Dňa st 7. 7. 2021, 20:33 gregory1970 ***@***.***> napísal(a):

**Comment by peter771** [comment]
Ahoj Parrot tv ako stiahnem plugin na enigmu na vu Zero 4k?

Dňa st 7. 7. 2021, 20:33 gregory1970 ***@***.***> napísal(a):

**Comment by kajost** [comment]
No ja som cakal a uz ma to prestalo bavit. Ale dal som si tu namahu a nasiel [premium verziu] (https://archivczsk.club/info) kde to funguje, za cenu jedneho pilsnera si myslim ze to je super jedine to SC comunity tam chyba.

**Comment by digitas** [comment]
> 
> 
> No ja som cakal a uz ma to prestalo bavit. Ale dal som si tu namahu a nasiel [premium verziu](https://archivczsk.club/info) kde to funguje, za cenu jedneho pilsnera si myslim ze to je super jedine to SC comunity tam chyba.
> 

Skúšal som nainštalovať Premium, ale nejde mi ju spustiť - pri vstupe do Menu-Doplnky vypíše hlášku "... _counter.so: cannot open shared object file..." čo majú v návode na stránke a ani tá inštalácia archivfix.ipk nepomôže...

Mám ale ešte nainštalovanú klasickú verziu, musí sa odinštalovať alebo chodia súčasne?

**Comment by kajost** [comment]
No ak ti to nejde tak skus zmenit image napr openATV 6.4 co mam ja tak ide po naistalovani fixu, pripadne napis na kontakt co je na stranke mozno ti poradi.

No ja mam obe verzie takze by tam nemal byt problem s fungovanim.

**Comment by digitas** [comment]
@kajost
Dik za info, že môžu byť dve verzie v boxe súčasne. 
Ja mám už svoj vyladený OpenATV image 5.1, na novších od verzie 6 mi nefunguje DVB-T tuner, takže  image meniť nemôžem.
Ešte skúsim na to prísť sám..., naštudovať si python :-)

**Comment by kajost** [comment]
No tak pokial mas starsiu verziu a nejde tak ti najskor pomoze napisat mail aurovi premium pokial sa teda v tom nevyznas jak on :-D

**Comment by misanov** [comment]
Opraveno. Chyby v doplňcích prosím řešte v archivczsk-doplnky.

**Comment by gregory1970** [comment]
Funguje to, ale je to bez možnosti pozrieť si to podľa vybraného dňa. Takže napriklad  tlačovky si neviete pozrieť. Výber podľa dátumu bol ideálny. Takto sú tam kategórie v ktorých niekde nejde ani otvoriť druhá strana.

**Comment by Sedo77** [comment]
Nerozumiem ze to nevrátili do pôvodnej podoby.. Takto je to tak, ze to ani
nemusí byť.. Cele na hovno

Dňa ne 11. 7. 2021, 9:37 gregory1970 ***@***.***> napísal(a):

**Comment by peter771** [comment]
Ahoj kde stiahnem plugin archivczsk premium 1.0?alebo úplne ten
najnovší.poraď

Dňa so 10. 7. 2021, 8:26 kajost ***@***.***> napísal(a):
