### ISSUE TITLE
SCC servery mají problémy. Prosím opakujte akci pozdeji

### ISSUE THREAD

**Issue by EssaykoSK** [mx3L/archivczsk#134]
Zdravim. Uz asi mesiac mi vypisuje SCC hlasku "SCC servery mají problémy. Prosím opakujte akci pozdeji".  Problem nezacal po nejakej aktualizacii, nastal zo dna na den. Je plugin vo vyvoji, alebo uz nie? Ak treba doplnit dalsie informacie, ci logy, doplnim. Len treba povedat co a odkial :)

Prijímač: Vu+ ZERO 4K
OS: openATV v aktuálnej verzii
Mam klasicku verziu Archiv cz sk v. 1.3.8, nie premium.

Dakujem.

**Comment by misanov** [comment]
Toto je třeba řešit s autory, pravděpodobně je to tak, jak ta hláška píše, viz. https://streamcinema.cz/d/662-casto-kladene-otazky-faq
