### ISSUE TITLE
Sledovanie TV

### ISSUE THREAD

**Issue by baaluu** [mx3L/archivczsk#137]
Openatv 6,4. V archive Sledovanie TV nefunguje live tv a ani archiv nahrane programy idu.Moze niekto poradit kde je problem.Dik

**Comment by baaluu** [comment]
Prosim o opravu pluginu Sledovanie TV na Openatv 6,4. Dakujem.

**Comment by skyjet18** [comment]
Tento repozitár už nie je udržiavaný - viď. info na úvodnej stránke ...

**Comment by baaluu** [comment]
Ahoj je nejaka sanca ze niekto obnovi plugin Sledovanie TV.
