### ISSUE TITLE
sosáč

### ISSUE THREAD

**Issue by DuoCore** [mx3L/archivczsk#14]
Nejde stahovat ze sosáče, ani z ulozto. S premiovým, ani bez prem. účtu. Vždy se VU+ Duo2 VTi image 9.0.3 teď nová instalace Vti v11. Tak se receiver restartuje.

**Comment by pangi** [comment]
Stream mne osobne ide, ale receiver sa mi resetuje pri pokuse o download, pri upravach nastaveni ..
Tu mam nejake logy: https://www.dropbox.com/sh/gjthssnih5troty/AAB_ASkFiAz_KOcpavekOxkga?dl=0

**Comment by eraser17** [comment]
VU+ UNO 4k VTi v11 a Sosáč taktiež nefunguje.
Hláška:
[Chyba archivu] Nelze yzískat video link [CR] zkontrolujte jestli video nebylo odstraneno.

Je to pri každom videu.

**Comment by mx3L** [comment]
Po nedavnej aktualizacii je zrejme tento problem vyrieseny, mozte potvrdit?

**Comment by DuoCore** [comment]
Tak stále to samé, receiver sa mi resetuje pri pokuse o download, pri upravach nastaveni ..

**Comment by DuoCore** [comment]
Na ABforum všichni popisují stejný problém. Mne vytuhne box a pomôže len reštart. Vo verzii 0,73 mi nahrávanie funguje,ale zas keď chcem otvoriť nastavenie sosača,tak box vytuhne. Takže ve verzi 0.73 jde nahrávat ze sosáče i uložto, ale nesmí se otevírat nastavení, jinak box vytuhne. Ve verzi nastavení jde, ale vytuhne při downloadu.

**Comment by jurajdrobec** [comment]
v poslednych dnoch mi Sosac stopne stream cca 20 sekund po zacati prehravania, neviete co s tym? vdaka

**Comment by mtester270** [comment]
Zatvaram bud stare alebo budd fixed v novej verzii
