### ISSUE TITLE
openatv 5.3

### ISSUE THREAD

**Issue by pravyroxor** [mx3L/archivczsk#16]
Cez open ATV 5.3 tento plugin dlhodobo nefunguje, box po spustení prehrávania videa zobrazí kruh v ľavom rohu a celý box vytuhne, nič sa nedeje, pomôže len tvrdý reset - prijímač Xtrend ET 7500.

**Comment by ilon1** [comment]
Ten istý problém na ET 7000. Ale upresním to. Takto sa to správa na všetkých firmwéroch (Openwix, openhdf, openatv, openxta) v nových verziách, resp. verzie do konca 06/2016. Napr. Vix 4.1.x ide na 4.2.x nejde. Openatv 5.3 júnový ide na čerstvom novom nejde. Ide to na HDMU aj najnovšej verzii. Openpli neskúšané. Sťahovanie funguje, pohyb v menu funguje.

**Comment by pravyroxor** [comment]
Nie je to tak celkom pravda, toto správanie je skôr špecifikom prijímačov XTrend - resp buildu image pre túto značku, pretože okrem ET7500 mám doma ešte 3 boxy VU+ Zero s rovnakým - aktuálnym image od OPENATV 5.3 a tam nie je vôbec žiadny problém s týmto pluginom - prehrávaním videí.

**Comment by ilon1** [comment]
Ja mám doma et9500 a tam je to v poriadku. Tiež píšem len o et7x00 prijímačoch. Mám v správe jeden 7000 a jeden 7500 a robí to len na nich.

**Comment by pravyroxor** [comment]
To je asi špecifikum hardvéru - procesora alebo nevhodného ovládača.

**Comment by s3n0** [comment]
napr. ja mam zase box Formuler F3 s image OpenATV 5.3 (nie Ellano.sk verziu, ale cisty a aktualizovany oficialny image) a vsetko funguje OK, vlavo nieje ziadny kruh

**Comment by pravyroxor** [comment]
No veď aj ja mám image priamo z http://images.mynonpublic.com/openatv/current/index.php?open=et7x00
a s ním mám tento problém. Potom mám aj rovnakú verziu (nightly) buildu pre VU+ Zero a ten funguje už bezchybne, žiadny kruh, video sa krásne prehráva. Preto si myslím že je problém s ovládačom alebo nepodporovaným hardvérom, možno CPU nevie pracovať s kodekom pluginu.

**Comment by mx3L** [comment]
No vypada to na ovladace, ine video pluginy sa chovaju rovnako? Klasicky prehravac medii funguje?

**Comment by pravyroxor** [comment]
Áno prehrávanie z interného HDD funguje bez problémov - to čo nahral box, rovnako funguje aj plugin media portal, či hbbtv.

**Comment by mx3L** [comment]
A to co nenahral box teda funguje tiez(mp4, mkv , avi)? hbbtv myslis prehravanie videii z ivysilani markiza?

Mohol by si vyskusat aj openpli?, ten ma tiez najnovsie ovladace pre tento xtrend, aby sme zistili ci je problem v nich.

**Comment by Bhellion1** [comment]
Teraz som vyskúšal nahodit najnovsi Openpli na x7000 a robí to tiez. Sťahovanie vyhlási chybu, prehravanie skončí zamrznutim boxu. Na pozadi beží sstelitny kanál, ale box nereaguje na ziadny povel.

**Comment by Bhellion1** [comment]
Doplnam. Mediaplayer 2 ma rovnaké spravanie. Po spusteni vytuhne cely box.

**Comment by ilon1** [comment]
Openatv 6.0 problém s archívom vyriešený. Funguje korektne.

**Comment by ilon1** [comment]
Zabudol som dodať na ET 7000

**Comment by pravyroxor** [comment]
ďakujem za informáciu a potvrdzujem ilon1, že plugin bez problémov funguje pod OpenATV6.0 na prístroji Xtrend et-7x00
