### ISSUE TITLE
Gigablue hd quad+ nefunkcni archivczsk openatv

### ISSUE THREAD

**Issue by nicon12** [mx3L/archivczsk#17]
Zdravim, dne 24.12.2016 vysly nove ovladace pro gigablue,ktere openatv zakomponovala do sebe a od te doby se archivczsk po spusteni kterehokoli doplnku do 2 sekund kousne a pomuze jen tvrdy restart, plati jak pro openatv 5.3 tak 6.0 verze po 24.12.2016,vyzkouseno s verzi archivuczsk 0.73 i 0.74, da se to nejak poresit? Diky

**Comment by mx3L** [comment]
ahoj,
Prosim, upresni co to znamena po spusteni doplnku.(Spustis archivczsk->vyberies doplnok?)

**Comment by nicon12** [comment]
ano,archivczsk se spusti v pohode,ale jakmile spustim kterykoliv doplnek,tak se 1-2 sekund zacne toci t uprostred to kolecko a pak se natvrdo kousne box a pomuze jen tvrdy restart pres zadni vypinac prijimace

Odesláno z MIUIDne mx3L <notifications@github.com> 18. 1. 2017 21:35 napsal(a):ahoj,
Prosim, upresni co to znamena po spusteni doplnku.(Spustis archivczsk->vyberies doplnok?)

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/mx3L/archivczsk","title":"mx3L/archivczsk","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/mx3L/archivczsk"}},"updates":{"snippets":[{"icon":"PERSON","message":"@mx3L in #17: ahoj,\r\nProsim, upresni co to znamena po spusteni doplnku.(Spustis archivczsk-\u003evyberies doplnok?)"}],"action":{"name":"View Issue","url":"https://github.com/mx3L/archivczsk/issues/17#issuecomment-273593781"}}}

**Comment by mx3L** [comment]
Toto skor vyzera na problem v enigme, potreboval by som log z enigmy v momente zamrznutia, predtym nastav v nastaveniach archivoch debug mod.

**Comment by nicon12** [comment]
A kde ten log najdu? Díval jsem se do/tmp a home/root/logs a nikde nic

**Comment by nicon12** [comment]
Tady je crash log, snad to pomůže

<?xml version="1.0" encoding="utf-8"?>
<openATV>
	<enigma2>
		<crashdate>Po úno  6 07:54:17 2017</crashdate>
		<compiledate>Feb  6 2017</compiledate>
		<contactemail>forum at www.opena.tv</contactemail>
		
		<skin>MetrixHD/skin.MySkin.xml</skin>
		<sourcedate>2017-02-05</sourcedate>
		<version>5.3</version>
	</enigma2>
	<image>
		<stbmodel>gigablue</stbmodel>
		<kernelversion>
			<![CDATA[
Linux gbquadplus 4.8.3 #1 SMP Tue Jan 31 08:39:26 CET 2017 mips GNU/Linux
]]>
		</kernelversion>
		<kernelcmdline>libata.force=1:3.0G,2:3.0G,3:3.0G ubi.mtd=rootfs rootfstype=ubifs root=ubi0:rootfs bmem=192M@64M bmem=256M@512M</kernelcmdline>
		<nimsockets>NIM Socket 0:</nimsockets>
		<imageversion>
			<![CDATA[
box_type=gbquadplus
build_type=0
version=6.0
build=0
date=20170131071532
comment=openATV
target=9
creator=openATV
url=http://www.opena.tv
catalog=http://www.opena.tv
]]>
		</imageversion>
		<imageissue>
			<![CDATA[
Welcome to openATV for %h
openatv 6.0 %h

]]>
		</imageissue>
	</image>
	<crashlogs>
		<enigma2crashlog>
			<![CDATA[
esolver/lib', '/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/resources/repositories/xbmc_doplnky/script.module.stream.resolver/lib/contentprovider', '/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/resources/repositories/xbmc_doplnky/script.module.stream.resolver/lib/crypto', '/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/resources/repositories/xbmc_doplnky/script.module.stream.resolver/lib/server']
07:54:17.6985 { E } Plugins/Extensions/archivCZSK/__init__.py:49 debug [ArchivCZSK] DEBUG:  [script.module.stream.resolver-importer]  cannot found modul StorageServer
07:54:17.6989 {   } Plugins/Extensions/archivCZSK/__init__.py:49 debug [ArchivCZSK] DEBUG:  [custom_sys-importer]  import 'StorageServer'
07:54:17.6995 {   } Plugins/Extensions/archivCZSK/__init__.py:49 debug [ArchivCZSK] DEBUG:  [custom_sys-importer]  finding modul 'StorageServer' in ['']
07:54:17.7001 { E } Plugins/Extensions/archivCZSK/__init__.py:49 debug [ArchivCZSK] DEBUG:  [custom_sys-importer]  cannot found modul StorageServer
07:54:17.7119 {   } Plugins/Extensions/archivCZSK/__init__.py:49 debug [ArchivCZSK] DEBUG:  [plugin.video.sosac.ph-importer]  import 'sys'
07:54:17.7126 {   } Plugins/Extensions/archivCZSK/__init__.py:49 debug [ArchivCZSK] DEBUG:  [plugin.video.sosac.ph-importer]  finding modul 'sys' in ['', '/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/resources/repositories/xbmc_doplnky/plugin.video.sosac.ph/resources/lib']
07:54:17.7134 { E } Plugins/Extensions/archivCZSK/__init__.py:49 debug [ArchivCZSK] DEBUG:  [plugin.video.sosac.ph-importer]  cannot found modul sys
07:54:17.7139 {   } Plugins/Extensions/archivCZSK/__init__.py:49 debug [ArchivCZSK] DEBUG:  [script.module.stream.resolver-importer]  import 'sys'
07:54:17.7145 {   } Plugins/Extensions/archivCZSK/__init__.py:49 debug [ArchivCZSK] DEBUG:  [script.module.stream.resolver-importer]  finding modul 'sys' in ['', '/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/resources/repositories/xbmc_doplnky/script.module.stream.resolver/lib', '/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/resources/repositories/xbmc_doplnky/script.module.stream.resolver/lib/contentprovider', '/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/resources/repositories/xbmc_doplnky/script.module.stream.resolver/lib/crypto', '/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/resources/repositories/xbmc_doplnky/script.module.stream.resolver/lib/server']
07:54:17.7156 { E } Plugins/Extensions/archivCZSK/__init__.py:49 debug [ArchivCZSK] DEBUG:  [script.module.stream.resolver-importer]  cannot found modul sys
07:54:17.7162 {   } Plugins/Extensions/archivCZSK/__init__.py:49 debug [ArchivCZSK] DEBUG:  [custom_sys-importer]  import 'sys'
07:54:17.7167 {   } Plugins/Extensions/archivCZSK/__init__.py:49 debug [ArchivCZSK] DEBUG:  [custom_sys-importer]  found 'sys' in modules
07:54:17.7175 {   } Plugins/Extensions/archivCZSK/__init__.py:49 debug [ArchivCZSK] DEBUG:  [plugin.video.sosac.ph-importer]  import 'sqlite'
07:54:17.7181 {   } Plugins/Extensions/archivCZSK/__init__.py:49 debug [ArchivCZSK] DEBUG:  [plugin.video.sosac.ph-importer]  finding modul 'sqlite' in ['', '/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/resources/repositories/xbmc_doplnky/plugin.video.sosac.ph/resources/lib']
07:54:17.7189 { E } Plugins/Extensions/archivCZSK/__init__.py:49 debug [ArchivCZSK] DEBUG:  [plugin.video.sosac.ph-importer]  cannot found modul sqlite
07:54:17.7195 {   } Plugins/Extensions/archivCZSK/__init__.py:49 debug [ArchivCZSK] DEBUG:  [script.module.stream.resolver-importer]  import 'sqlite'
07:54:17.7200 {   } Plugins/Extensions/archivCZSK/__init__.py:49 debug [ArchivCZSK] DEBUG:  [script.module.stream.resolver-importer]  finding modul 'sqlite' in ['', '/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/resources/repositories/xbmc_doplnky/script.module.stream.resolver/lib', '/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/resources/repositories/xbmc_doplnky/script.module.stream.resolver/lib/contentprovider', '/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/resources/repositories/xbmc_doplnky/script.module.stream.resolver/lib/crypto', '/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/resources/repositories/xbmc_doplnky/script.module.stream.resolver/lib/server']
07:54:17.7213 { E } Plugins/Extensions/archivCZSK/__init__.py:49 debug [ArchivCZSK] DEBUG:  [script.module.stream.resolver-importer]  cannot found modul sqlite
07:54:17.7218 {   } Plugins/Extensions/archivCZSK/__init__.py:49 debug [ArchivCZSK] DEBUG:  [custom_sys-importer]  import 'sqlite'
07:54:17.7222 {   } Plugins/Extensions/archivCZSK/__init__.py:49 debug [ArchivCZSK] DEBUG:  [custom_sys-importer]  finding modul 'sqlite' in ['']
07:54:17.7228 { E } Plugins/Extensions/archivCZSK/__init__.py:49 debug [ArchivCZSK] DEBUG:  [custom_sys-importer]  cannot found modul sqlite
07:54:17.7272 {   } Plugins/Extensions/archivCZSK/__init__.py:49 debug [ArchivCZSK] DEBUG:  [plugin.video.sosac.ph-importer]  import 'sqlite3'
07:54:17.7277 {   } Plugins/Extensions/archivCZSK/__init__.py:49 debug [ArchivCZSK] DEBUG:  [plugin.video.sosac.ph-importer]  finding modul 'sqlite3' in ['', '/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/resources/repositories/xbmc_doplnky/plugin.video.sosac.ph/resources/lib']
07:54:17.7286 { E } Plugins/Extensions/archivCZSK/__init__.py:49 debug [ArchivCZSK] DEBUG:  [plugin.video.sosac.ph-importer]  cannot found modul sqlite3
07:54:17.7292 {   } Plugins/Extensions/archivCZSK/__init__.py:49 debug [ArchivCZSK] DEBUG:  [script.module.stream.resolver-importer]  import 'sqlite3'
07:54:17.7297 {   } Plugins/Extensions/archivCZSK/__init__.py:49 debug [ArchivCZSK] DEBUG:  [script.module.stream.resolver-importer]  finding modul 'sqlite3' in ['', '/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/resources/repositories/xbmc_doplnky/script.module.stream.resolver/lib', '/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/resources/repositories/xbmc_doplnky/script.module.stream.resolver/lib/contentprovider', '/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/resources/repositories/xbmc_doplnky/script.module.stream.resolver/lib/crypto', '/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/resources/repositories/xbmc_doplnky/script.module.stream.resolver/lib/server']
07:54:17.7309 { E } Plugins/Extensions/archivCZSK/__init__.py:49 debug [ArchivCZSK] DEBUG:  [script.module.stream.resolver-importer]  cannot found modul sqlite3
07:54:17.7316 {   } Plugins/Extensions/archivCZSK/__init__.py:49 debug [ArchivCZSK] DEBUG:  [custom_sys-importer]  import 'sqlite3'
07:54:17.7321 {   } Plugins/Extensions/archivCZSK/__init__.py:49 debug [ArchivCZSK] DEBUG:  [custom_sys-importer]  finding modul 'sqlite3' in ['']
07:54:17.7327 { E } Plugins/Extensions/archivCZSK/__init__.py:49 debug [ArchivCZSK] DEBUG:  [custom_sys-importer]  cannot found modul sqlite3
07:54:17.7385 {   } Plugins/Extensions/archivCZSK/__init__.py:49 debug [ArchivCZSK] DEBUG:  [plugin.video.sosac.ph-importer]  import 'sqlite3.dbapi2'
07:54:17.7392 {   } Plugins/Extensions/archivCZSK/__init__.py:49 debug [ArchivCZSK] DEBUG:  [plugin.video.sosac.ph-importer]  finding modul 'sqlite3.dbapi2' in ['', '/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/resources/repositories/xbmc_doplnky/plugin.video.sosac.ph/resources/lib']
07:54:17.7400 { E } Plugins/Extensions/archivCZSK/__init__.py:49 debug [ArchivCZSK] DEBUG:  [plugin.video.sosac.ph-importer]  cannot found modul sqlite3.dbapi2
07:54:17.7405 {   } Plugins/Extensions/archivCZSK/__init__.py:49 debug [ArchivCZSK] DEBUG:  [script.module.stream.resolver-importer]  import 'sqlite3.dbapi2'
07:54:17.7411 {   } Plugins/Extensions/archivCZSK/__init__.py:49 debug [ArchivCZSK] DEBUG:  [script.module.stream.resolver-importer]  finding modul 'sqlite3.dbapi2' in ['', '/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/resources/repositories/xbmc_doplnky/script.module.stream.resolver/lib', '/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/resources/repositories/xbmc_doplnky/script.module.stream.resolver/lib/contentprovider', '/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/resources/repositories/xbmc_doplnky/script.module.stream.resolver/lib/crypto', '/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/resources/repositories/xbmc_doplnky/script.module.stream.resolver/lib/server']
07:54:17.7424 { E } Plugins/Extensions/archivCZSK/__init__.py:49 debug [ArchivCZSK] DEBUG:  [script.module.stream.resolver-importer]  cannot found modul sqlite3.dbapi2
07:54:17.7429 {   } Plugins/Extensions/archivCZSK/__init__.py:49 debug [ArchivCZSK] DEBUG:  [custom_sys-importer]  import 'sqlite3.dbapi2'
07:54:17.7435 {   } Plugins/Extensions/archivCZSK/__init__.py:49 debug [ArchivCZSK] DEBUG:  [custom_sys-importer]  finding modul 'sqlite3.dbapi2' in ['']
07:54:17.7442 { E } Plugins/Extensions/archivCZSK/__init__.py:49 debug [ArchivCZSK] DEBUG:  [custom_sys-importer]  cannot found modul sqlite3.dbapi2
07:54:17.7480 {   } Plugins/Extensions/archivCZSK/__init__.py:49 debug [ArchivCZSK] DEBUG:  [plugin.video.sosac.ph-importer]  import 'sqlite3.datetime'
07:54:17.7486 {   } Plugins/Extensions/archivCZSK/__init__.py:49 debug [ArchivCZSK] DEBUG:  [plugin.video.sosac.ph-importer]  finding modul 'sqlite3.datetime' in ['', '/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/resources/repositories/xbmc_doplnky/plugin.video.sosac.ph/resources/lib']
07:54:17.7496 { E } Plugins/Extensions/archivCZSK/__init__.py:49 debug [ArchivCZSK] DEBUG:  [plugin.video.sosac.ph-importer]  cannot found modul sqlite3.datetime
07:54:17.7501 {   } Plugins/Extensions/archivCZSK/__init__.py:49 debug [ArchivCZSK] DEBUG:  [script.module.stream.resolver-importer]  import 'sqlite3.datetime'
07:54:17.7507 {   } Plugins/Extensions/archivCZSK/__init__.py:49 debug [ArchivCZSK] DEBUG:  [script.module.stream.resolver-importer]  finding modul 'sqlite3.datetime' in ['', '/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/resources/repositories/xbmc_doplnky/script.module.stream.resolver/lib', '/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/resources/repositories/xbmc_doplnky/script.module.stream.resolver/lib/contentprovider', '/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/resources/repositories/xbmc_doplnky/script.module.stream.resolver/lib/crypto', '/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/resources/repositories/xbmc_doplnky/script.module.stream.resolver/lib/server']
07:54:17.7519 { E } Plugins/Extensions/archivCZSK/__init__.py:49 debug [ArchivCZSK] DEBUG:  [script.module.stream.resolver-importer]  cannot found modul sqlite3.datetime
07:54:17.7525 {   } Plugins/Extensions/archivCZSK/__init__.py:49 debug [ArchivCZSK] DEBUG:  [custom_sys-importer]  import 'sqlite3.datetime'
07:54:17.7530 {   } Plugins/Extensions/archivCZSK/__init__.py:49 debug [ArchivCZSK] DEBUG:  [custom_sys-importer]  finding modul 'sqlite3.datetime' in ['']
07:54:17.7538 { E } Plugins/Extensions/archivCZSK/__init__.py:49 debug [ArchivCZSK] DEBUG:  [custom_sys-importer]  cannot found modul sqlite3.datetime
07:54:17.7547 {   } Plugins/Extensions/archivCZSK/__init__.py:49 debug [ArchivCZSK] DEBUG:  [plugin.video.sosac.ph-importer]  import 'sqlite3.time'
07:54:17.7553 {   } Plugins/Extensions/archivCZSK/__init__.py:49 debug [ArchivCZSK] DEBUG:  [plugin.video.sosac.ph-importer]  finding modul 'sqlite3.time' in ['', '/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/resources/repositories/xbmc_doplnky/plugin.video.sosac.ph/resources/lib']
07:54:17.7562 { E } Plugins/Extensions/archivCZSK/__init__.py:49 debug [ArchivCZSK] DEBUG:  [plugin.video.sosac.ph-importer]  cannot found modul sqlite3.time
07:54:17.7567 {   } Plugins/Extensions/archivCZSK/__init__.py:49 debug [ArchivCZSK] DEBUG:  [script.module.stream.resolver-importer]  import 'sqlite3.time'
07:54:17.7574 {   } Plugins/Extensions/archivCZSK/__init__.py:49 debug [ArchivCZSK] DEBUG:  [script.module.stream.resolver-importer]  finding modul 'sqlite3.time' in ['', '/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/resources/repositories/xbmc_doplnky/script.module.stream.resolver/lib', '/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/resources/repositories/xbmc_doplnky/script.module.stream.resolver/lib/contentprovider', '/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/resources/repositories/xbmc_doplnky/script.module.stream.resolver/lib/crypto', '/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/resources/repositories/xbmc_doplnky/script.module.stream.resolver/lib/server']
07:54:17.7586 { E } Plugins/Extensions/archivCZSK/__init__.py:49 debug [ArchivCZSK] DEBUG:  [script.module.stream.resolver-importer]  cannot found modul sqlite3.time
07:54:17.7592 {   } Plugins/Extensions/archivCZSK/__init__.py:49 debug [ArchivCZSK] DEBUG:  [custom_sys-importer]  import 'sqlite3.time'
07:54:17.7596 {   } Plugins/Extensions/archivCZSK/__init__.py:49 debug [ArchivCZSK] DEBUG:  [custom_sys-importer]  finding modul 'sqlite3.time' in ['']
07:54:17.7603 { E } Plugins/Extensions/archivCZSK/__init__.py:49 debug [ArchivCZSK] DEBUG:  [custom_sys-importer]  cannot found modul sqlite3.time
07:54:17.7612 {   } Plugins/Extensions/archivCZSK/__init__.py:49 debug [ArchivCZSK] DEBUG:  [plugin.video.sosac.ph-importer]  import 'sqlite3._sqlite3'
07:54:17.7617 {   } Plugins/Extensions/archivCZSK/__init__.py:49 debug [ArchivCZSK] DEBUG:  [plugin.video.sosac.ph-importer]  finding modul 'sqlite3._sqlite3' in ['', '/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/resources/repositories/xbmc_doplnky/plugin.video.sosac.ph/resources/lib']
07:54:17.7626 { E } Plugins/Extensions/archivCZSK/__init__.py:49 debug [ArchivCZSK] DEBUG:  [plugin.video.sosac.ph-importer]  cannot found modul sqlite3._sqlite3
07:54:17.7635 {   } Plugins/Extensions/archivCZSK/__init__.py:49 debug [ArchivCZSK] DEBUG:  [script.module.stream.resolver-importer]  import 'sqlite3._sqlite3'
07:54:17.7642 {   } Plugins/Extensions/archivCZSK/__init__.py:49 debug [ArchivCZSK] DEBUG:  [script.module.stream.resolver-importer]  finding modul 'sqlite3._sqlite3' in ['', '/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/resources/repositories/xbmc_doplnky/script.module.stream.resolver/lib', '/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/resources/repositories/xbmc_doplnky/script.module.stream.resolver/lib/contentprovider', '/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/resources/repositories/xbmc_doplnky/script.module.stream.resolver/lib/crypto', '/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/resources/repositories/xbmc_doplnky/script.module.stream.resolver/lib/server']
07:54:17.7655 { E } Plugins/Extensions/archivCZSK/__init__.py:49 debug [ArchivCZSK] DEBUG:  [script.module.stream.resolver-importer]  cannot found modul sqlite3._sqlite3
07:54:17.7662 {   } Plugins/Extensions/archivCZSK/__init__.py:49 debug [ArchivCZSK] DEBUG:  [custom_sys-importer]  import 'sqlite3._sqlite3'
07:54:17.7667 {   } Plugins/Extensions/archivCZSK/__init__.py:49 debug [ArchivCZSK] DEBUG:  [custom_sys-importer]  finding modul 'sqlite3._sqlite3' in ['']
07:54:17.7674 { E } Plugins/Extensions/archivCZSK/__init__.py:49 debug [ArchivCZSK] DEBUG:  [custom_sys-importer]  cannot found modul sqlite3._sqlite3
07:54:17.7703 [   ] bsod.cpp:304 oops PC: 77f4e80c
07:54:17.7704 [   ] bsod.cpp:310 oops 00000000 10008b00 6747cf0c 6747cf60
07:54:17.7705 [   ] bsod.cpp:310 oops 6747cf0c 00000000 00000050 98b830f4
07:54:17.7705 [   ] bsod.cpp:310 oops 00000000 00000003 00000004 ca5cf438
07:54:17.7706 [   ] bsod.cpp:310 oops 00100077 ca689b84 0000000e 76900010
07:54:17.7706 [   ] bsod.cpp:310 oops 7695dfa0 68d38a80 00000045 00000000
07:54:17.7707 [   ] bsod.cpp:310 oops 68d38c40 00000002 6747cf60 68d38a98
07:54:17.7707 [   ] bsod.cpp:310 oops 00000000 77f4e7c0 00002012 00000000
07:54:17.7707 [   ] bsod.cpp:310 oops 77f6c000 68d38a48 68d38ac8 77f39e88
07:54:17.7836 [   ] bsod.cpp:327 print_backtrace Backtrace:
07:54:17.7841 [   ] bsod.cpp:335 print_backtrace /usr/bin/enigma2(_Z17handleFatalSignaliP9siginfo_tPv) [0x469F04]
07:54:17.7842 [   ] bsod.cpp:335 print_backtrace linux-vdso.so.1(n/a) [0x77F62560]
07:54:17.7843 [   ] bsod.cpp:335 print_backtrace /lib/ld.so.1(n/a) [0x77F4E80E]
07:54:17.7843 [   ] bsod.cpp:335 print_backtrace /lib/ld.so.1(n/a) [0x77F39E88]
07:54:17.7844 [   ] bsod.cpp:347 handleFatalSignal -------FATAL SIGNAL
]]>
		</enigma2crashlog>
	</crashlogs>
</openATV>

**Comment by nicon12** [comment]
Posílám crash log, snad to pomůže chybu odhalit

**Comment by nicon12** [comment]
Tak jsem zkoušel i jiný image a to openmips přímo od Gigablue a zde archiv funguje, jediný rozdíl z mého laického pohledu je že openatv 6.0 používá gstreamer 1.11.1 a Openmips zase gstreamer 1.9.0, ovladače i kernel jsou stejné verze, mohl by to být ten problém? Děkuji

**Comment by nicon12** [comment]
Takže jsem trochu testoval a přišel na to že problém dělají dva pluginy tsmedia a lcd4linux, pokud nejsou nainstalovány archivczsk kompletně funguje
