### ISSUE TITLE
DM7020HD - crash "Nastavenia"

### ISSUE THREAD

**Issue by aaabaloo** [mx3L/archivczsk#18]
Ahoj, bol som nuteny preinstalovat box a po instalacii verzie 0.73 ju sice spustim, aj mi funguje, ale ked chcem vojst do nastavenia aplikacie, tak mi to spadne. Skusal som rozne verzie skinov a rovnaky vysledok. Vies mi prosim napisat v com je problem? Box bezi na poslednom DMM exp. 
[crash.zip](https://github.com/mx3L/archivczsk/files/715317/crash.zip)
Dik

**Comment by mx3L** [comment]
Ahoj, 

v logu vidim 0.73-20160821, skus tuto verziu
https://github.com/mx3L/archivczsk/releases/download/v0.73/enigma2-plugin-extensions-archivczsk_0.73-20160823_all.deb

**Comment by aaabaloo** [comment]
Mam DM 7020HD (v1). Je to starsi box a viem pouzit iba ipk baliky (OE 2.0). Alebo tam viem natlacit nejako aj deb? dik

**Comment by mx3L** [comment]
ten balik je uplne rovnaky s ipk len pripona je zmenena na deb, cize premenuj ak je problem. Preco neskusis 0.74?

**Comment by aaabaloo** [comment]
Premenoval som teda ten balik .deb, nainstaloval, ale to iste. Tak som opat vsetko odinstaloval a dal verziu 0.74. Ta sa mi v menu ale vobec neobjavi a ked ju chcem ist cez menu moduly, tak mi vyhodi tuto hlasku, vid priloha, dakujem za trpezlivost a Tvoj cas.
![screenshot](https://cloud.githubusercontent.com/assets/25211169/22144768/2c987bd0-deff-11e6-86f9-ffade0aa60ed.jpg)

**Comment by sufel** [comment]
Zdravím, takisto ma tento problém, VTI 11.01 1201-61-22, Vu+ Uno 4K.
Potrebujem si zadať prihlasovacie údaje, akonáhle stlačim "nastavenia" , spadne to.
[dvbapp2_crash_1490288967_2017-03-23_18-09-27.txt](https://github.com/mx3L/archivczsk/files/865564/dvbapp2_crash_1490288967_2017-03-23_18-09-27.txt)
Dá sa niečo s tým ?
Ďakujem..

**Comment by mtester270** [comment]
Pada to koli FHD plugine na TV. Ked si zmenite plugin na HD ako AtilaHD tak to pojde. V novej verzii bude opravene
