### ISSUE TITLE
Úprava pro aktivovaný Cloudfare aneb Sosáč mezi 20:00-23:30 nejede :-(

### ISSUE THREAD

**Issue by maciii** [mx3L/archivczsk#19]
Ahoj, zdá se že na Kodi už plugin (v1.3) jede. Myslíš že se Ti podaří toto doplnit i do Enigma pluginu aby jel Sosáč i mezi 20:00-23:30?

**Comment by mx3L** [comment]
Ahoj, mam troska ine cislovanie verzii, v 1.2.5 by malo vsetko fungovat, cca 9 dni dozadu som ju pridal.

**Comment by maciii** [comment]
Ahoj. aha musel jsem vše reinstalovat, nenabízí  mi to update na 1.2.5. Lze ten update vyvolat nějak ručně
