### ISSUE TITLE
Nefunkčný archív

### ISSUE THREAD

**Issue by bobor18** [mx3L/archivczsk#20]
Snažím sa nainštalovať archivczsk cez telnet na box VU+ Uno 4k, image BH 3.0.3. Archivczsk je po nainštalovaní nefunkčný a pri inštalácii v telnete vypíše viď obrázok. Postupujem podľa návodu tu na stránke (vyskúšal som obidva). 
![archivczsk](https://cloud.githubusercontent.com/assets/25536691/22605836/ed61c814-ea51-11e6-8dbe-a32d0c4385d0.png)

**Comment by mtester270** [comment]
na image BH 3.0.3 to nepojede pokial autori BH neaktualizuju kniznicu python-twisted na verziu 16 nie 12 :)

ak tak zmen image alebo si naistaluj verziu 0.73 ta s mensimi nefunkcnostami na BH ide
