### ISSUE TITLE
Release verze

### ISSUE THREAD

**Issue by DuoCore** [mx3L/archivczsk#22]
Prosím, mohl by jsi udělat release verzi, alespoň s těmi důležitými opravami. 
1. Nahrávání
2. Nahrávání z prémium účtu
3. Možnost Zvětšit buffer pro přehrávání, 

bylo by to super.

**Comment by mtester270** [comment]
ak to este nie je poriesene tak napis a skus byt trosku konkretnejsi lebo netusim co konkretne myslis pri bode 1, 2, 3 

sa bavime o konkretnom plugine ?
