### ISSUE TITLE
Dreambox DM525 - openpli 4.0 - nejde obraz zvuk OK

### ISSUE THREAD

**Issue by duro28** [mx3L/archivczsk#23]
Pri spusteny videa v archivu CZ/SK mi nejde obraz len zvuk a vypise hlasku GStreamer plugin H.264 decoder not available. Da sa nejakym sposobom doinstalovat tento plugin? Neexistuje  nejaky doplnok .ipk?

markiza a ta3  - seka.

**Comment by mtester270** [comment]
Skus uja googla pre tvoj image ja stym neviem pommoct
