### ISSUE TITLE
Order

### ISSUE THREAD

**Issue by mtester270** [mx3L/archivczsk#25]
Moze mi niekto povedat na zaklade coho sa robi order pluginov lebo pozeram ten "potkan kod" ktory vidim prvy krat ale neviem na to dojst :)

resp. by bolo mozno fajn spravit order v aplikacii

ak tak poprosim napisat na mtester270@gmail.com

**Comment by mx3L** [comment]
Ahoj, neviem co tym myslis "potkan kod" ale je pravda ze plugin by sa zisiel takmer komplet prepisat, kedze to zacalo len mojim pokusom naucit sa python a vela casti je tam stale povodnych. Takze ak chces vklude prepis je tam vela nepotrebneho balastu, ja to nemam cas momentalne riesit. 

Order je podla abecedy
napr video doplnky:
https://github.com/mx3L/archivczsk/blob/master/build/plugin/src/engine/contentprovider.py#L528

**Comment by mtester270** [comment]
potkan hh ze python som myslel tak pre mna je to des ja kodim .net :-)

no ked si dam vsetky doplnky tak ani nahodou to nie je podla abacedy ani
podla nicoho co je v parametroch pluginu preto som bol mimo podla coho to
radis. Nap ta3 je prve potom slowtv potom blbosti a potom je sosac zase
"s". Vies mi aspon povedat ktory subor by trebalo zmenit ak budem mat cas a
hlavne chut pythonit tak skusim

Dik

**Comment by mtester270** [comment]
bude v novej verzii 💃
