### ISSUE TITLE
VTI image

### ISSUE THREAD

**Issue by mtester270** [mx3L/archivczsk#26]
**Info uzivatelom VU+ s VTi image (Solo 2)**

Na VTi image 11.0.1 koretkne funguje len verzia 0.72_beta7. Verziu 0.74 som este radsej ani neskusal kedze to je RC ak je zajem kludne skusim ak chcete (kontakt cez email).

vo verzii 0.72_beta8 fungovalo skoro vsetko az na to ked som dal stiahnut video tak to cele padlo na restart krabicky :) a zaujimave je ze napriklad Games of tron nesiel vobec ani jeden diel prehrat pricom na beta7 vpohode :)

vo verzie 0.73 ked som dal Nastavenia tak to cele padlo taktiez na restart krabicky takze toto som ani dalej neskusal

GL&HF

**Comment by brkulin** [comment]
Jo, na VTI to nějak nechce korektně fungovat.Zkusil jsem i verzi 0.74 a chová se to stejně. Při pokusu o stažení dojde k restartu a zaseknutí VUčka (mám Solo4K).
Pokud bude mít autor chuť se tím zabývat, pošlu i crashlog.

**Comment by mtester270** [comment]
ak by si chcel rozbehat stahovanie tak ti treba preplacnut plugin
StreamResolver ktory je zjavne zly a ked nainstalujes starsiu verziu
czsk.archiv ten plugin z toho si odlozis a potom ja som uz len aktualizoval
vsetly pluginy cez autoupdater a potom som preplacol spominany plugin a
vypol auto update a vsetko ide jak ma.

Prosim ta kde by som vedel najst logy lebo nemam stym skoro ziadne
skusenosti???

**Comment by brkulin** [comment]
Tak u mě tenhle postup nefunguje. Stream Resolver jsem přeplácnul a stejně to padá.
Jinak crashlogy se generují automaticky a měly by být uloženy na hdd, pokud není v image nastaveno jinak.

**Comment by mx3L** [comment]
@mtester270, @brkulin pridajte sem prosim crashlogy

**Comment by brkulin** [comment]
Přikládám poslední crashlog.
[dvbapp2_crash.zip](https://github.com/mx3L/archivczsk/files/908036/dvbapp2_crash.zip)

**Comment by mx3L** [comment]
Vdaka, skuste tuto verziu
https://www.dropbox.com/s/l7686kcd49yzu2v/enigma2-plugin-extensions-archivczsk_0.74-20170118_all.ipk?dl=1

**Comment by brkulin** [comment]
Vyzkoušel jsem, dostal se o krok dál, ale stále se to zasekává. Přikládám nový
[dvbapp2_crash_1492241579_2017-04-15_09-32-59.zip](https://github.com/mx3L/archivczsk/files/923408/dvbapp2_crash_1492241579_2017-04-15_09-32-59.zip)
 crashlog

**Comment by mtester270** [comment]
no neviem ako tebe na tom VU ale na mojom Solo 2 VTi 11 bezim na verzii
0.72 sa mi vidi tam kde je beta 7 a funguje uz aj ten resolver po
aktualizacii novu verziu som radsej neskusal ked to ako tak ide teraz

**Comment by brkulin** [comment]
Jo, verze 0.72 beta 7 mi taky funguje. Ale jakmile zaktulizuju moduly, tak potom nepomůže ani přepsání resolveru z této verze. Možná bys mi mohl napsat, jaké soubory jsi po aktualizaci přepisoval, nebo mi poslal
svoji zálohu resolveru z beta7.

**Comment by mx3L** [comment]
@brkulin, mozes nastavit debug mode z info na debug v nastaveniach archivov a poslat sem crashlog znova?

**Comment by mx3L** [comment]
dalsia verzia na test
https://www.dropbox.com/s/nfvqln86jq3xpv6/enigma2-plugin-extensions-archivczsk_0.74-20170415_all.ipk?dl=1

**Comment by brkulin** [comment]
Omlouvám se za pozdější reakci, ale byl jsem mimo.
Zkusil jsem i poslední testovací verzi a je to stále stejné. Posílám crashlogy (debug zapnut) z obou testovacích verzí.
[crash_log.ZIP](https://github.com/mx3L/archivczsk/files/923582/crash_log.ZIP)

**Comment by mx3L** [comment]
Diky, este raz prosim stiahni a nainstaluj:
https://www.dropbox.com/s/nfvqln86jq3xpv6/enigma2-plugin-extensions-archivczsk_0.74-20170415_all.ipk?dl=1

**Comment by brkulin** [comment]
Tak stále nic. Pořád se to chová stejně. 
[dvbapp2_crash_1492260650_2017-04-15_14-50-50.zip](https://github.com/mx3L/archivczsk/files/923597/dvbapp2_crash_1492260650_2017-04-15_14-50-50.zip)

**Comment by mx3L** [comment]
No to iste to neni, aspon sa odladia chyby. dalsia verzia, link ten isty

**Comment by brkulin** [comment]
Tak stahování proběhlo bez závad. Jen jsem odhalil malinký nedostatek:
Když v příslušném doplňku po stažení souboru dám přes menu Zobrazit stahované soubory, tak tam mám "úspěšně staženo" a pak volby Zrušit - Přehrát - Odstranit. Pokud dám Přehrát, tak se nic neděje a nejde z toho vyskočit jinak, než dát Zrušit a pak teprve můžu z okna odejít.
Když zvolím Stažené soubory, tak tam to jde přehrát bez problémů.
Není to ale tak podstatná chybička. Ale když už ladíme...

**Comment by brkulin** [comment]
Ještě jsem si dovolil trochu upravit a doplnit češtinu pro archiv, tak to posílám, třeba se to bude hodit do finální verze.
[archivCZSK_lang_CZ.zip](https://github.com/mx3L/archivczsk/files/923627/archivCZSK_lang_CZ.zip)

**Comment by mx3L** [comment]
vdaka, cestina + oprava pridana, link rovnaky

**Comment by brkulin** [comment]
Díky za vyřešení a ať se daří v dalším vývoji, a nejen v něm, ale i v životě.

**Comment by mx3L** [comment]
Diky, pridal som do release aj tuto poslednu verziu
