### ISSUE TITLE
DM7080HD OE2.5 Nefunkčné titulky

### ISSUE THREAD

**Issue by R-I-S-O** [mx3L/archivczsk#27]
Nahral som na môj dreambox DM7080 nový exprimental image OE2.5 dreambox-image-deb-dm7080-20170410 

Doinštaloval som:
gstreamer1.0-plugins-bad-fragmented_1.6.4-r0.7_mipsel.deb
gstreamer1.0-plugins-bad-rtmp_1.6.4-r0.7_mipsel.deb
enigma2-plugin-extensions-subssupport_1.5.4-20160215_all.deb
enigma2-plugin-extensions-archivczsk_0.74-20170415_all.deb

Okrem prehrávania filmov zo sosáču som toho moc neskúšal (ani nepotrebujem) no už odjakživa mám problém s titulkami... automaticky sa nespustia a ako náhle vbehnem do menu tituliek a potvrdím čokoľvek z výberu, nasleduje pád systému...
Na starom image OE2.2 s archivczsk 0.72-beta.8 sa to dalo obísť stlačením kurzorovej šípky vľavo/vpravo čo zmenilo časový posun tituliek a samotné titulky sa začali zázrakom zobrazovať, ono to teraz funguje stále, ibaže ma to hodí na začiatok filmu a lišta s info o priebehu filmu už nezmizne (neprišiel som na spôsob ako ju schovať bez ukončenia prehrávania). Sozdruzi z NDR prišli v tomto image na vstavanom prehrávači s rýchlim prevíjaním ktoré je práve na kurzorových šípkach, neviem či to má súvis...

Za prípadné opravy alebo rady vopred vďaka.

**Comment by mtester270** [comment]
Ak to este riesis posli crash log inac ti neviem pomoct
