### ISSUE TITLE
OPEN ATV 6.0 archiv czsk 0.74 nejde prima a nova

### ISSUE THREAD

**Issue by marek402** [mx3L/archivczsk#28]
Ahoj, neví někdo jak rozjet v archviu czsk novu a primu? Ostatní šlape dobře, ale nova a prima nejde, zkoušel jsem i verzi 0.73 a tam taky vše jde, kromě novy a primy. Dík za radu

**Comment by beri23** [comment]
prima uz ma v kodi repository verziu 0.3.8 (v archivoch je 0.3.7)
asi preto uz archivy nejdu, cez kodi vse ok (Vu Duo2 - OpenATV 6.0 - Kodi17)
alebo skus Hbbtv na prima kanale, pozeram tak Autosalon

**Comment by marek402** [comment]
dík za rady, ale kodi na VU+ zero asi dávat nebudu, někde jsem četl, že to je slabá mašina na kodi, hbbtv testnu dík.

**Comment by zipo11** [comment]
Prosím vás. Stahujú sa vám videa normálne? Ja som kupil octagonsf108 a dal som tam 0.74 a vobec mi to nefunguje. Ďakujem

**Comment by mtester270** [comment]
Skus naistalovat toto
https://github.com/mx3L/archivczsk/releases/download/v0.74/enigma2-plugin-extensions-archivczsk_0.74-20170415_all.ipk
Ak nepojde pockaj na novu verziu
