### ISSUE TITLE
neda sa aktivovat Stream Cinema

### ISSUE THREAD

**Issue by solide1964** [mx3L/archivczsk#29]
zaplatil som si archiv Stream Cinema. Chcel som vlozit v nastaveniach pluginu  prihlasovacie meno a heslo a vzdy mi vypise ze je chyba v software a restartne sa Enigma2 , vid foto: www.stola.rajce.net.formuler4  Neviete prosim v com je problem a ako postupovat? 

tu je crashlogs:

<?xml version="1.0" encoding="utf-8"?>
<openATV>
	<enigma2>
		<crashdate>Ut jún 20 07:00:04 2017</crashdate>
		<compiledate>May  3 2017</compiledate>
		<contactemail>forum at www.opena.tv</contactemail>
		
		<skin>hd_glass17/skin.xml</skin>
		<sourcedate>2017-05-02</sourcedate>
		<version>5.3</version>
	</enigma2>
	<image>
		<stbmodel>formuler4turbo</stbmodel>
		<kernelversion>
			<![CDATA[
Linux formuler4turbo 4.10.6 #1 SMP Wed Apr 26 05:31:56 CEST 2017 mips GNU/Linux
]]>
		</kernelversion>
		<kernelcmdline>ubi.mtd=rootfs rootfstype=ubifs root=ubi0:rootfs bmem=192M@64M console=null</kernelcmdline>
		<nimsockets>NIM Socket 0:</nimsockets>
		<imageversion>
			<![CDATA[
box_type=formuler4turbo
build_type=0
version=6.0
build=0
date=20170417110017
comment=openATV
target=9
creator=openATV
url=http://www.opena.tv
catalog=http://www.opena.tv
]]>
		</imageversion>
		<imageissue>
			<![CDATA[
Welcome to openATV for %h
openatv 6.0 %h

]]>
		</imageissue>
	</image>
	<crashlogs>
		<enigma2crashlog>
			<![CDATA[
ctionMap.py:53 action unknown action WizardActions/ok! typo in keymap?
06:49:26.0766 {   } Components/ActionMap.py:46 action action ->  OkCancelActions ok
06:49:26.1731 {   } skin.py:1325 readSkin [SKIN] processing screen SystemNetworkInfo:
06:49:26.2291 {   } skin.py:577 valign valign must be either top, center or bottom!, not left. Please contact the skin's author!
06:49:26.3516 {   } skin.py:1102 readSkin [SKIN] No skin to read...
06:49:26.3535 {   } skin.py:1325 readSkin [SKIN] processing screen <embedded-in-'AboutSummary'>:
06:49:26.3555 {   } Screens/Screen.py:151 show [SCREENNAME]  AboutSummary
06:49:26.3591 {   } Screens/Screen.py:151 show [SCREENNAME]  ['SystemNetworkInfo', 'WlanStatus']
06:49:26.4274 [   ] base/ebase.cpp:279 processOneEvent poll: unhandled POLLERR/HUP/NVAL for fd 75(16)
06:49:26.4344 [   ] driver/rcinput.cpp:38 handleCode 0 160 1
06:49:26.4465 {   } Screens/InfoBarGenerics.py:205 actionA KEY: 352 1 KEY_OK OK
06:49:26.6043 [   ] base/ebase.cpp:279 processOneEvent poll: unhandled POLLERR/HUP/NVAL for fd 81(16)
06:49:26.6045 [   ] base/ebase.cpp:279 processOneEvent poll: unhandled POLLERR/HUP/NVAL for fd 81(16)
06:49:26.6047 [   ] base/ebase.cpp:279 processOneEvent poll: unhandled POLLERR/HUP/NVAL for fd 81(16)
06:49:26.6048 [   ] base/ebase.cpp:279 processOneEvent poll: unhandled POLLERR/HUP/NVAL for fd 81(16)
06:49:26.6065 [   ] base/ebase.cpp:279 processOneEvent poll: unhandled POLLERR/HUP/NVAL for fd 81(16)
06:49:26.6382 [   ] base/ebase.cpp:279 processOneEvent poll: unhandled POLLERR/HUP/NVAL for fd 78(16)
06:49:26.6661 [   ] base/ebase.cpp:279 processOneEvent poll: unhandled POLLERR/HUP/NVAL for fd 75(16)
06:50:02.5704 [   ] service/servicedvb.cpp:1734 timeshift not enough diskspace for timeshift! (less than 1GB)
06:50:03.5713 [   ] service/servicedvb.cpp:1734 timeshift not enough diskspace for timeshift! (less than 1GB)
06:50:03.5718 { E } Components/Timeshift.py:540 autostartAutorecordTimeshift [TIMESHIFT] - tune lock failed, so could not start.
06:50:31.4753 {   } Plugins/Extensions/AutoTimer/AutoPoller.py:32 query [AutoTimer] Auto Poll
06:50:31.4762 {   } Plugins/Extensions/AutoTimer/AutoPoller.py:49 query [AutoTimer] Auto Poll Started
06:50:31.4899 {   } Components/Task.py:375 jobDone job Components.Task.Job name=AutoTimer #tasks=0 completed with [] in None
06:54:07.6737 {   } Plugins/Extensions/Volume_adjust/plugin.py:468 __evUpdatedInfo [Volume Adjust] Update Info
06:54:07.6743 {   } Plugins/Extensions/Volume_adjust/plugin.py:472 __evUpdatedInfo [Volume Adjust] Volume = 100
06:54:07.6747 {   } Plugins/Extensions/Volume_adjust/plugin.py:446 loadXML [Volume Adjust] load xml...
06:59:37.9582 [   ] driver/rcinput.cpp:38 handleCode 1 ae 1
06:59:37.9613 {   } Screens/InfoBarGenerics.py:205 actionA KEY: 174 0 KEY_EXIT EXIT
06:59:37.9625 {   } Components/ActionMap.py:46 action action ->  SetupActions cancel
06:59:37.9686 {   } Screens/Screen.py:151 show [SCREENNAME]  MenuSummary
06:59:37.9776 {   } Screens/Screen.py:151 show [SCREENNAME]  ['menu_information', 'Menu']
06:59:38.2671 [   ] driver/rcinput.cpp:38 handleCode 0 ae 1
06:59:38.2695 {   } Screens/InfoBarGenerics.py:205 actionA KEY: 174 1 KEY_EXIT EXIT
06:59:39.4951 [   ] driver/rcinput.cpp:38 handleCode 1 ae 1
06:59:39.4981 {   } Screens/InfoBarGenerics.py:205 actionA KEY: 174 0 KEY_EXIT EXIT
06:59:39.5003 {   } Components/ActionMap.py:46 action action ->  WizardActions back
06:59:39.5008 { W } Components/ActionMap.py:53 action unknown action WizardActions/back! typo in keymap?
06:59:39.5015 {   } Components/ActionMap.py:46 action action ->  OkCancelActions cancel
06:59:39.5069 {   } Screens/Screen.py:151 show [SCREENNAME]  MenuSummary
06:59:39.5167 {   } Screens/Screen.py:151 show [SCREENNAME]  ['menu_mainmenu', 'Menu']
06:59:39.8031 [   ] driver/rcinput.cpp:38 handleCode 0 ae 1
06:59:39.8052 {   } Screens/InfoBarGenerics.py:205 actionA KEY: 174 1 KEY_EXIT EXIT
06:59:42.1996 [   ] driver/rcinput.cpp:38 handleCode 1 6c 1
06:59:42.2021 {   } Screens/InfoBarGenerics.py:205 actionA KEY: 108 0 KEY_DOWN DOWN
06:59:42.2031 {   } Components/ActionMap.py:46 action action ->  WizardActions down
06:59:42.2140 [ E ] gdi/accel.cpp:357 accelAlloc accel alloc failed

06:59:42.2141 [ E ] gdi/gpixmap.cpp:146 gSurface ERROR: accelAlloc failed
06:59:42.4611 [ E ] gdi/accel.cpp:357 accelAlloc accel alloc failed

06:59:42.4612 [ E ] gdi/gpixmap.cpp:146 gSurface ERROR: accelAlloc failed
06:59:42.6537 [ E ] gdi/accel.cpp:357 accelAlloc accel alloc failed

06:59:42.6538 [ E ] gdi/gpixmap.cpp:146 gSurface ERROR: accelAlloc failed
06:59:42.8481 [   ] driver/rcinput.cpp:38 handleCode 0 6c 1
06:59:42.8505 {   } Screens/InfoBarGenerics.py:205 actionA KEY: 108 1 KEY_DOWN DOWN
06:59:42.8513 [   ] driver/rcinput.cpp:38 handleCode 1 6c 1
06:59:42.8538 {   } Screens/InfoBarGenerics.py:205 actionA KEY: 108 0 KEY_DOWN DOWN
06:59:42.8547 {   } Components/ActionMap.py:46 action action ->  WizardActions down
06:59:42.8570 [ E ] gdi/accel.cpp:357 accelAlloc accel alloc failed

06:59:42.8571 [ E ] gdi/gpixmap.cpp:146 gSurface ERROR: accelAlloc failed
06:59:43.0488 [ E ] gdi/accel.cpp:357 accelAlloc accel alloc failed

06:59:43.0491 [ E ] gdi/gpixmap.cpp:146 gSurface ERROR: accelAlloc failed
06:59:43.2424 [ E ] gdi/accel.cpp:357 accelAlloc accel alloc failed

06:59:43.2425 [ E ] gdi/gpixmap.cpp:146 gSurface ERROR: accelAlloc failed
06:59:43.4374 [   ] driver/rcinput.cpp:38 handleCode 0 6c 1
06:59:43.4398 {   } Screens/InfoBarGenerics.py:205 actionA KEY: 108 1 KEY_DOWN DOWN
06:59:43.4407 [   ] driver/rcinput.cpp:38 handleCode 1 6c 1
06:59:43.4431 {   } Screens/InfoBarGenerics.py:205 actionA KEY: 108 0 KEY_DOWN DOWN
06:59:43.4441 {   } Components/ActionMap.py:46 action action ->  WizardActions down
06:59:43.4473 [ E ] gdi/accel.cpp:357 accelAlloc accel alloc failed

06:59:43.4474 [ E ] gdi/gpixmap.cpp:146 gSurface ERROR: accelAlloc failed
06:59:43.6413 [ E ] gdi/accel.cpp:357 accelAlloc accel alloc failed

06:59:43.6414 [ E ] gdi/gpixmap.cpp:146 gSurface ERROR: accelAlloc failed
06:59:43.8341 [ E ] gdi/accel.cpp:357 accelAlloc accel alloc failed

06:59:43.8342 [ E ] gdi/gpixmap.cpp:146 gSurface ERROR: accelAlloc failed
06:59:44.0230 [   ] driver/rcinput.cpp:38 handleCode 0 6c 1
06:59:44.0254 {   } Screens/InfoBarGenerics.py:205 actionA KEY: 108 1 KEY_DOWN DOWN
06:59:44.6000 [   ] driver/rcinput.cpp:38 handleCode 1 6c 1
06:59:44.6025 {   } Screens/InfoBarGenerics.py:205 actionA KEY: 108 0 KEY_DOWN DOWN
06:59:44.6034 {   } Components/ActionMap.py:46 action action ->  WizardActions down
06:59:44.6065 [ E ] gdi/accel.cpp:357 accelAlloc accel alloc failed

06:59:44.6066 [ E ] gdi/gpixmap.cpp:146 gSurface ERROR: accelAlloc failed
06:59:44.7995 [ E ] gdi/accel.cpp:357 accelAlloc accel alloc failed

06:59:44.7996 [ E ] gdi/gpixmap.cpp:146 gSurface ERROR: accelAlloc failed
06:59:44.9911 [ E ] gdi/accel.cpp:357 accelAlloc accel alloc failed

06:59:44.9913 [ E ] gdi/gpixmap.cpp:146 gSurface ERROR: accelAlloc failed
06:59:45.1807 [   ] driver/rcinput.cpp:38 handleCode 0 6c 1
06:59:45.1831 {   } Screens/InfoBarGenerics.py:205 actionA KEY: 108 1 KEY_DOWN DOWN
06:59:50.0436 [   ] driver/rcinput.cpp:38 handleCode 1 160 1
06:59:50.0464 {   } Screens/InfoBarGenerics.py:205 actionA KEY: 352 0 KEY_OK OK
06:59:50.0475 {   } Components/ActionMap.py:46 action action ->  WizardActions ok
06:59:50.0478 { W } Components/ActionMap.py:53 action unknown action WizardActions/ok! typo in keymap?
06:59:50.0483 {   } Components/ActionMap.py:46 action action ->  OkCancelActions ok
06:59:50.2421 [   ] driver/rcinput.cpp:38 handleCode 0 160 1
06:59:50.2444 {   } Screens/InfoBarGenerics.py:205 actionA KEY: 352 1 KEY_OK OK
06:59:50.2456 {   } Components/ActionMap.py:46 action action ->  OkCancelActions OK
06:59:50.2468 { W } Components/ActionMap.py:53 action unknown action OkCancelActions/OK! typo in keymap?
06:59:51.7048 {   } Plugins/Extensions/archivCZSK/__init__.py:58 info [ArchivCZSK] INFO:   ArchivCZSKContentProvider get_content - params: None
06:59:51.7087 {   } skin.py:1086 readSkin [SKIN] Parsing embedded skin <embedded-in-'LoadingScreen'>
06:59:51.7112 {   } skin.py:1325 readSkin [SKIN] processing screen <embedded-in-'LoadingScreen'>:
06:59:51.7392 {   } skin.py:1325 readSkin [SKIN] processing screen ArchivCZSKContentScreen:
06:59:51.7587 {   } skin.py:605 flags illegal flag wfBorder!
06:59:51.8034 {   } skin.py:1325 readSkin [SKIN] processing screen SimpleSummary:
06:59:51.8082 {   } Screens/Screen.py:151 show [SCREENNAME]  ['ArchivCZSKContentScreen_summary', 'SimpleSummary']
06:59:51.8113 {   } Screens/Screen.py:151 show [SCREENNAME]  ArchivCZSKContentScreen
06:59:51.8135 [   ] base/ebase.cpp:279 processOneEvent poll: unhandled POLLERR/HUP/NVAL for fd 73(16)
06:59:54.1540 [   ] driver/rcinput.cpp:38 handleCode 1 18e 1
06:59:54.1567 {   } Screens/InfoBarGenerics.py:205 actionA KEY: 398 0 KEY_RED RED
06:59:54.1581 {   } Components/ActionMap.py:46 action action ->  archivCZSKActions red
06:59:54.1621 {   } Plugins/Extensions/archivCZSK/__init__.py:58 info [ArchivCZSK] INFO:   ArchivCZSKContentProvider get_content - params: {'category_addons': 'all_addons', 'filter_enabled': False}
06:59:54.1746 {   } skin.py:1086 readSkin [SKIN] Parsing embedded skin <embedded-in-'LoadingScreen'>
06:59:54.1769 {   } skin.py:1325 readSkin [SKIN] processing screen <embedded-in-'LoadingScreen'>:
06:59:54.1885 {   } skin.py:1325 readSkin [SKIN] processing screen ArchivCZSKContentScreen:
06:59:54.2077 {   } skin.py:605 flags illegal flag wfBorder!
06:59:54.3407 {   } skin.py:1325 readSkin [SKIN] processing screen SimpleSummary:
06:59:54.3452 {   } Screens/Screen.py:151 show [SCREENNAME]  ['ArchivCZSKContentScreen_summary', 'SimpleSummary']
06:59:54.3482 {   } Screens/Screen.py:151 show [SCREENNAME]  ArchivCZSKContentScreen
06:59:54.4580 [   ] driver/rcinput.cpp:38 handleCode 0 18e 1
06:59:54.4602 {   } Screens/InfoBarGenerics.py:205 actionA KEY: 398 1 KEY_RED RED
06:59:56.6743 [   ] driver/rcinput.cpp:38 handleCode 1 6c 1
06:59:56.6767 {   } Screens/InfoBarGenerics.py:205 actionA KEY: 108 0 KEY_DOWN DOWN
06:59:56.6777 {   } Components/ActionMap.py:46 action action ->  archivCZSKActions down
06:59:56.9781 [   ] driver/rcinput.cpp:38 handleCode 0 6c 1
06:59:56.9805 {   } Screens/InfoBarGenerics.py:205 actionA KEY: 108 1 KEY_DOWN DOWN
06:59:57.4837 [   ] driver/rcinput.cpp:38 handleCode 1 6c 1
06:59:57.4866 {   } Screens/InfoBarGenerics.py:205 actionA KEY: 108 0 KEY_DOWN DOWN
06:59:57.4876 {   } Components/ActionMap.py:46 action action ->  archivCZSKActions down
06:59:57.6821 [   ] driver/rcinput.cpp:38 handleCode 0 6c 1
06:59:57.6845 {   } Screens/InfoBarGenerics.py:205 actionA KEY: 108 1 KEY_DOWN DOWN
06:59:58.0401 [   ] driver/rcinput.cpp:38 handleCode 1 6c 1
06:59:58.0435 {   } Screens/InfoBarGenerics.py:205 actionA KEY: 108 0 KEY_DOWN DOWN
06:59:58.0444 {   } Components/ActionMap.py:46 action action ->  archivCZSKActions down
06:59:58.2340 [   ] driver/rcinput.cpp:38 handleCode 0 6c 1
06:59:58.2364 {   } Screens/InfoBarGenerics.py:205 actionA KEY: 108 1 KEY_DOWN DOWN
06:59:58.7920 [   ] driver/rcinput.cpp:38 handleCode 1 160 1
06:59:58.7943 {   } Screens/InfoBarGenerics.py:205 actionA KEY: 352 0 KEY_OK OK
06:59:58.7953 {   } Components/ActionMap.py:46 action action ->  archivCZSKActions ok
06:59:58.8143 {   } skin.py:1325 readSkin [SKIN] processing screen ArchivCZSKContextMenuScreen:
06:59:58.8252 {   } skin.py:1325 readSkin [SKIN] processing screen SimpleSummary:
06:59:58.8301 {   } Screens/Screen.py:151 show [SCREENNAME]  ['ArchivCZSKContextMenuScreen_summary', 'SimpleSummary']
06:59:58.8321 {   } Screens/Screen.py:151 show [SCREENNAME]  ArchivCZSKContextMenuScreen
06:59:59.1540 [   ] driver/rcinput.cpp:38 handleCode 0 160 1
06:59:59.1580 {   } Screens/InfoBarGenerics.py:205 actionA KEY: 352 1 KEY_OK OK
07:00:01.0993 [   ] driver/rcinput.cpp:38 handleCode 1 6c 1
07:00:01.1017 {   } Screens/InfoBarGenerics.py:205 actionA KEY: 108 0 KEY_DOWN DOWN
07:00:01.1027 {   } Components/ActionMap.py:46 action action ->  archivCZSKActions down
07:00:01.3163 [   ] driver/rcinput.cpp:38 handleCode 0 6c 1
07:00:01.3186 {   } Screens/InfoBarGenerics.py:205 actionA KEY: 108 1 KEY_DOWN DOWN
07:00:01.7577 [   ] driver/rcinput.cpp:38 handleCode 1 160 1
07:00:01.7601 {   } Screens/InfoBarGenerics.py:205 actionA KEY: 352 0 KEY_OK OK
07:00:01.7611 {   } Components/ActionMap.py:46 action action ->  archivCZSKActions ok
07:00:01.7644 {   } Screens/Screen.py:151 show [SCREENNAME]  ['ArchivCZSKContentScreen_summary', 'SimpleSummary']
07:00:01.7712 {   } Screens/Screen.py:151 show [SCREENNAME]  ArchivCZSKContentScreen
07:00:01.7917 {   } skin.py:1325 readSkin [SKIN] processing screen ArchivCZSKConfigScreen:
07:00:01.8120 {   } Plugins/Extensions/archivCZSK/gui/common.py:475 initList entries_per_row = 4, rows = 1, num_pages = 2
07:00:01.8207 {   } skin.py:1325 readSkin [SKIN] processing screen SimpleSummary:
07:00:01.8255 {   } Screens/Screen.py:151 show [SCREENNAME]  ['ArchivCZSKAddonConfigScreen_summary', 'ArchivCZSKConfigScreen_summary', 'SimpleSummary']
07:00:01.8449 {   } skin.py:1325 readSkin [SKIN] processing screen NumericalTextInputHelpDialog:
07:00:01.8702 {   } Screens/Screen.py:151 show [SCREENNAME]  NumericalTextInputHelpDialog
07:00:01.8844 {   } skin.py:1325 readSkin [SKIN] processing screen NumericalTextInputHelpDialog:
07:00:01.9093 {   } Screens/Screen.py:151 show [SCREENNAME]  NumericalTextInputHelpDialog
07:00:01.9113 {   } Screens/Screen.py:151 show [SCREENNAME]  ['ArchivCZSKAddonConfigScreen', 'ArchivCZSKConfigScreen']
07:00:02.1220 [   ] driver/rcinput.cpp:38 handleCode 0 160 1
07:00:02.1243 {   } Screens/InfoBarGenerics.py:205 actionA KEY: 352 1 KEY_OK OK
07:00:03.6574 [   ] driver/rcinput.cpp:38 handleCode 1 6c 1
07:00:03.6600 {   } Screens/InfoBarGenerics.py:205 actionA KEY: 108 0 KEY_DOWN DOWN
07:00:03.6610 {   } Components/ActionMap.py:46 action action ->  SetupActions down
07:00:03.6613 { W } Components/ActionMap.py:53 action unknown action SetupActions/down! typo in keymap?
07:00:03.6617 {   } Components/ActionMap.py:46 action action ->  SetupActions down
07:00:03.6621 { W } Components/ActionMap.py:53 action unknown action SetupActions/down! typo in keymap?
07:00:03.6775 {   } skin.py:1325 readSkin [SKIN] processing screen NumericalTextInputHelpDialog:
07:00:03.7000 {   } Screens/Screen.py:151 show [SCREENNAME]  NumericalTextInputHelpDialog
07:00:03.8581 [   ] driver/rcinput.cpp:38 handleCode 0 6c 1
07:00:03.8613 {   } Screens/InfoBarGenerics.py:205 actionA KEY: 108 1 KEY_DOWN DOWN
07:00:04.6903 [   ] driver/rcinput.cpp:38 handleCode 1 160 1
07:00:04.6930 {   } Screens/InfoBarGenerics.py:205 actionA KEY: 352 0 KEY_OK OK
07:00:04.6940 {   } Components/ActionMap.py:46 action action ->  SetupActions ok
07:00:04.6973 { D } Traceback (most recent call last):
07:00:04.6976 { D }   File "/usr/lib/enigma2/python/Components/ActionMap.py", line 48, in action
07:00:04.7144 { D }   File "/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/gui/menu.py", line 121, in keyOk
07:00:04.7193 { D }     self.session.openWithCallback(self.virtualKBCB, VirtualKeyBoardCFG, entryName, current)
07:00:04.7196 { D }   File "/usr/lib/enigma2/python/mytest.py", line 316, in openWithCallback
07:00:04.7266 { D }     dlg = self.open(screen, *arguments, **kwargs)
07:00:04.7272 { D }   File "/usr/lib/enigma2/python/mytest.py", line 326, in open
07:00:04.7286 { D }     dlg = self.current_dialog = self.instantiateDialog(screen, *arguments, **kwargs)
07:00:04.7291 { D }   File "/usr/lib/enigma2/python/mytest.py", line 264, in instantiateDialog
07:00:04.7304 { D }     return self.doInstantiateDialog(screen, arguments, kwargs, self.desktop)
07:00:04.7306 { D }   File "/usr/lib/enigma2/python/mytest.py", line 286, in doInstantiateDialog
07:00:04.7321 { D }     dlg = screen(self, *arguments, **kwargs)
07:00:04.7324 { D }   File "/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/gui/menu.py", line 204, in __init__
07:00:04.7337 { D }     VirtualKeyBoard.__init__(self, session, entryName.encode('utf-8'), configEntry.getValue().encode('utf-8'))
07:00:04.7343 { D } TypeError: __init__() takes at most 3 arguments (4 given)
07:00:04.7345 [ E ] python/python.cpp:209 call (PyObject_CallObject(<bound method ActionMap.action of <Components.ActionMap.ActionMap instance at 0x6d039210>>,('SetupActions', 'ok')) failed)
]]>
		</enigma2crashlog>
	</crashlogs>
</openATV>

**Comment by benko21** [comment]
Ten isty problem mam aj ja na xtrend ET7500.je mozne to nejak opravit? Vdaka

**Comment by bbaronSVK** [comment]
problem je v skine. meno/heslo sa da zadat aj stlacanim cisiel bez "kliknutia" na policko meno/heslo - staci prist kurzorom na polozku a potom uz len tlacit cisielka ako na starych telefonoch pri SMS.

**Comment by solide1964** [comment]
Dakujem za vasu odpoved, odpovedali ste mi za viac ako mesiac. Ja som si 
na mesiac zaplatil premium konto, aby som mohol pozerat vas archiv a 
cele mi to prepadlo -:(
Dňa 2017-08-03 11:06 Michal Paulovic napísal(a):

**Comment by pangi** [comment]
Si mal vydrzat.

**Comment by solide1964** [comment]
ahoj, idem buduci tyzden na dovolneku a tam by som chcel pozerat tvoj
archiv Stream Cinema . Nepomozes mi to nastavit tak, aby mi moj satelit ,
ktory si do Grecka beriem na vas archiv fungovalo?  Zatial to skoncilo u
mna le trapnym pokusom, kde som si na mesiac predplatil konto na websare a
nevidel som ani jeden film. Aky skon by podla teba v mojom satelite
fungoval?J

2017-08-03 13:17 GMT+02:00 pangi <notifications@github.com>:

**Comment by mtester270** [comment]
pokial vam nejde zobrazit nastavenia tak fix je jednoduchy:
1) prepnite si SKIN na televizore na HD napr. AtilaHD (NIE FULL HD!!!)a dame restart
2) spustime archiv dame si doplnocek ktory chceme nastavime meno heslo ulozit
3) vratime si SKIN na televizore na povodny FHD
4) restart

PS: v novej verzii to bude opravene
