### ISSUE TITLE
SOSAC TV

### ISSUE THREAD

**Issue by petrger** [mx3L/archivczsk#30]
Dobrý den,

je možné mi pomoci? Rád bych zadal údaje pro SOSAC TV / aktivovano na streamuj CZ /. Používám VU+, ale ne KODI.... Mám VU+ zero.. Předem děkuji za pomoc a radu!!!

Petr

**Comment by forsajd** [comment]
ano tiez sa pripajam  v enigme2 aby sa dalo do sosaca prihlasit cez prihlasovacie udaje ako je to v kodi Dakujem

**Comment by mtester270** [comment]
Stare
