### ISSUE TITLE
befun - výpadky

### ISSUE THREAD

**Issue by xdedek** [mx3L/archivczsk#31]
ahojte, chtěl bych se jen zeptat. Jsem teď v zahraničí a přítelkyně se mi stěžovala, že poslední dva dny padá befun. Je to prý bohužel jediný server, kde mají její seriál. Má s tím taky někdo problémy? Případně někdo řešil?

HDBox Enibox - OpenATV 6.0, release někdy tento měsíc. CZSK Archiv ten nejnovější.

Díky moc za info.

**Comment by mtester270** [comment]
Bohuzial zatvaram stare ak atk napis ked bude nova verzia archivu
