### ISSUE TITLE
Nezobrazeny stream cinema

### ISSUE THREAD

**Issue by L0th4r** [mx3L/archivczsk#32]
Zdravim, nevim zda nekde delam neco spatne, ale nezobrazi se mi v archivu stream cinema czsk, zkousel jsem v. 0.73 i 0.74 . V manazeru archivu take neni. Mam Amiko alien 2 hyperion 5.5

**Comment by mtester270** [comment]
skus odinstalovat a daj si tam toto
https://github.com/mx3L/archivczsk/releases/download/v0.74/enigma2-plugin-extensions-archivczsk_0.74-20170415_all.ipk

ak nepomoze tak skus este nakomplet zmazat adresar cez ftp na ceste
/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/

a tak naistalovat
