### ISSUE TITLE
Ahoj.Nefunguje pretacanie v archivoch napr sosac.Ma niekto rovnaky problem?

### ISSUE THREAD

**Issue by baaluu** [mx3L/archivczsk#33]

**Comment by marian892** [comment]
Ani mne nejde asi po cca 1:20 min vypne ho ...

**Comment by zipo11** [comment]
DobrE vedieť.  Myslel som že som vtom sám. Mne nejde ani na befune a ani na či nemé nič

**Comment by lubosbruha** [comment]
To samé jako marian892, cca po 1:20 se jak sosac, tak befun sam od sebe vypne.

**Comment by zipo11** [comment]
A cinema máte funkcu?

**Comment by marian892** [comment]
ach jaj bolo to spoplatnené ...  takže koniec sosača

**Comment by zipo11** [comment]
Keby si to predplatis tak by išiel?  Ako by sa to vlastne pri hlasovalo?  V archýve som nič nenašiel.
