### ISSUE TITLE
Sosac - login

### ISSUE THREAD

**Issue by Kyselinka** [mx3L/archivczsk#34]
Ahoj, je mozne nejakym sposobom ulozit svoj login do sosaca? Nakolko je uz par dni spoplatneny a chcel by som si tam zadat svoje prihlasovacie udaje k premium uctu. Bez loginu uz nefunguje prehravanie filmov. Dakujem.

**Comment by maciii** [comment]
Taky se přimlouvám :-)

**Comment by zvedava** [comment]
tiez sa pripajam k prosebníkom ohladne sosacu a prihlasovania na satelitný príjmac dreambox. pokial viem je nás vela tápajúcich a čakajúcich na aktualizáciu pluginov s prihlasovacími údajmi.  ďakujeme

**Comment by sinacik** [comment]
Podarí sa niečo upgradnuť? Pripájam sa do kolejky 🗡

**Comment by jandis11** [comment]
Ahoj, také moc prosím o možnost vložení loginu. Koupil jsem si premium pouze kvůli koukání přes výborný Archiv CZ/SK!

**Comment by speedo919** [comment]
Cauko. Tiez prosim o pridanie premium loginu na Sosac. Dakujem

**Comment by bug78** [comment]
Ahoj, také se přidávám. Archiv CZ/SK je skvělí. Jen kvůli nemožnosti zadat login jsem musel přejít na Kodi, ale na Vu+ to jede celé šíleně pomalu, zlobí titulky a nejde mi to propojit s csfd. Díky

**Comment by mx3L** [comment]
Ahoj, potrebujem prihlasovacie udaje na test.

**Comment by bug78** [comment]
Kam je mam poslat? Tady je moc zverejnovat nechci :)

**Comment by maciii** [comment]
mx3l: Nevím jak Tě kontaktovat abych Ti poslal testovací účet. Napiš na maciii zavináč gmail.

**Comment by corey66** [comment]
Ahojte, robi sa nieco ohladom toho loginu? Sosac bez toho stale nefunguje...
Dakujem.

**Comment by ganco47** [comment]
tiez by som si rad predplatil ucet, len neviem kde najdem ceny a ako sa v masine VU+solo4k prihlasit, dakujem

**Comment by speedo919** [comment]
Tak login dnes pribudol, zaplatene mam davno ale nejak to nefunguje :-)

**Comment by ganco47** [comment]
no sosac ani neviem kde mozem zaplatit, hladam a nemozem najst, ale stream
cinema mam zaplateny a ide perfektne

2017-08-07 19:50 GMT+02:00 speedo919 <notifications@github.com>:

**Comment by ganco47** [comment]
no sosac ani neviem, ze kde mozem zaplatit, hladam a nemozem najst, ale stream cinema mam zaplateny a ide perfektne

**Comment by speedo919** [comment]
sosac sa plati na http://www.streamuj.tv

**Comment by frenky55** [comment]
velka vdaka, funguje to 

maly problem je, ze pretacanie funguje az po prvej minute

**Comment by jandis11** [comment]
Díky moc, super!

**Comment by petrger** [comment]
Bohužel v Enigma 2 stále nefunkční / VU+ /... Zadám login a heslo / streamuj.tv / a pouze je možnost shlédnout  prvních 1,38 minuty...  Dělá vám to taky?? Vše kontrolováno a napsáno správně.. Díky za pomoc..

**Comment by Kyselinka** [comment]
Mne to na E2 funguje normalne, len mi nejde pretacat film...ani po prvej minute.

**Comment by bug78** [comment]
Taky mi to na vu+ solo se 2 funguje. Jen to pretaceni mi jde pouzr u nejakych filmu, ale je jich malo.
Ucet musis mit zalozen na stream.tv a samozrejme zaplaceno :)

**Comment by petrger** [comment]
Mám zaplaceno a nejde, 

Streamuj TV - Premium účet máte aktivní do: 18.9.2017 13:57:33

**Comment by petrger** [comment]
Jinak používám VTI 11,0.  Jde jen krátce - mám placeno premium a kontrolováno vše..

**Comment by bug78** [comment]
Já mám VTI 11.0.2, archivczsk 0.74-20170415, sosáč 1.2.7. Zařízení VU+soloSE2.
Stejně to mám ještě u dvou známých. Každý má svůj účet a všem nám to normálně hraje dokonce jde i filmy stahovat. Jediný problém je s tím přetáčením.

**Comment by petrger** [comment]
Přeinstalováno.....
VTI 11.0.2, archivczsk 0.74-20170415, sosáč 1.2.7. Zařízení VU+zero .

Placeno premium na Streamuj.TV a bohužel jede jen 1,36 minuty. Mohu autorovi zaslat hesla...

**Comment by Kyselinka** [comment]
A funguje ti po prihlaseni film aj priamo cez web? http://movies.sosac.tv/cs/

**Comment by petrger** [comment]
Ano funguje.... Zeptá se na heslo na Streamuj,TV, zadám a jede to jako víno...!! Ale pouze na PC....

**Comment by petrger** [comment]
Nemůže být chyba v následujícím?? U streamuj.tv mám login: peger s malým p.. Ale účet na sosac.tv mám pod prihlasovacim jmenem: Peger.. Ale zadává se přeci účet a heslo ze Streamuj.tv, že ano?? 
Kolega platil na 3 měsíce, zadá login a heslo ze Streamuj.TV a taky mu to nejede.... Už nevím, kde je chyba...

**Comment by zvedava** [comment]
prosím o radu sledujem tu debatu a ak spravne rozumiem vyzera to že sa to o krôčik posunulo. ale napriek aktualizacii na mojom dreamboxe enigma 2, atv - možnosť sosač - heslo login ziadna? som laik tak prosim polopate.  prosím vie mi niekto poradiť ako dostanem do ponuky pluginov streamuj.tv? bohuzial ho tam nemam ani pri aktualizacii doplnkov. vdaka za odpoved.

**Comment by Kyselinka** [comment]
Otvoris si archiv cz sk, vyberies si sosac, potom stlacis modre tlacitko - nastavenia a tam by si mala mat moznost vpisat svoj login.
Ak nemas sosac aktualizovany, tak skus restartnut enigmu a po vybrati archivu by ti malo ponuknut automaticky aktualizaciu daneho pluginu.

**Comment by sinacik** [comment]
Asi som to vysmrdel.. ak riesime solo se2 a podobne na vti11.02. neviem ako ale pri mojom uno4k sa mi za meno a heslo zapise XcursorX skuste si na sosaci vytvorit meno aj heslo konciace tymto a do primaca v nastaveniach to nezadavajte len meno a heslo..

**Comment by 1terit1** [comment]
Zdravim . Taky mam problem se sosacem . Presneji za jmenem uctu se mi objevi XcursorX . Jak tady nekdo psal , tak jsem jiz heslo na streamujtv zmenil tak aby za nim byl ten XcursorX ale u jmena mi ta zmena nejde . Nevite nekdo jak nato ?? Dekuji za odpoved

**Comment by sinacik** [comment]
Tiez som s tym bojoval zaloz novy ucet s tym gestom,zaplat  a pojde to aj tak respekt

**Comment by 1terit1** [comment]
Ahoj ? Ted nerozumim ? Co mas namysli tim respekt ? Tobe se to teda rozjelo pote co sis vytvoril to jmeno a heslo s tim XcursorX ? Ja jeste pred chvili napsal dotaz na tu podporu streamuj tv , jestli to jmeno jde zmenit , tak jsem zvedavy co mi napisou . Doted mi je odepisovali , at si nainstaluji KODI :D

**Comment by 1terit1** [comment]
Jeste me napadla jedna vec . Nevite nekdo ve kterem adresari bych nasel to prihlaseni . Bude to nejaky textovy soubor , ve kterem by asi melo jit to XcursorX smazat :-)

**Comment by mx3L** [comment]
settingy su ulozene v /etc/enigma2/settings: 
config.plugins.archivCZSK.archives.plugin_video_sosac_ph.streamujtv_user=
config.plugins.archivCZSK.archives.plugin_video_sosac_ph.streamujtv_pass=
config.plugins.archivCZSK.archives.plugin_video_sosac_ph.streamujtv_location=

**Comment by mtester270** [comment]
XcursorX bude opravene v novej verzii. Problem je vtom ze login heslo nezadavajte cez vitualnu klavesnicu ale len cez ciselka na ovladaci presne tak ako ked ste pisali sms na tlacitkovom mobile.

**Comment by 1terit1** [comment]
Zdravim. Dekuji za odpověď. Uz jsem to vyřešil s míčkem který obsahuje 
xcursorx☺️ ještě jsem se chtěl zeptat, jestli by nesel nějak vyřešit ten 
problém s pretacenim filmů. Děkuji za odpověď

Odesláno pomocí AquaMail pro Android
http://www.aqua-mail.com


Dne 31. října 2017 8:18:45 odp. mtester270 <notifications@github.com> napsal:

**Comment by mtester270** [comment]
Ak hovoris o sosaci tak mozno tto budem riesit neskor ked bude casu. Na stream cinema mi pretacanie funguje. Ked tak napis PM na ab forum

**Comment by 1terit1** [comment]
Ahoj. Už jsem psal na různá fóra a výsledek žádný. Když mám nainstalovane 
kodi na pc a v něm addon sosac tak vše jede bez problémů i pretaceni. Na 
satelitu (vu + zero) některé starší filmy či seriály pretacet jdou a 
některé (většina), nejdou. Do doby než se spoplatnil streamTV vše fungovalo 
dokonale. Teď pokud dám pauzu na minutu a pak to zas pustím je to ok. Film 
pokračuje. Pokud je pauza delší, třeba tři minuty, tak se to kousne. Obraz 
stojí, ale titulky běží dal. Musíš to vypnout a koukat znova a to je 
otravné. Možná to je chyba přehrávače, ale neumím tam dát jiný. Těžko říct. 
Kdybys něco vymyslel, bylo by to fajn. Děkuji

Odesláno pomocí AquaMail pro Android
http://www.aqua-mail.com


Dne 31. října 2017 10:51:14 odp. mtester270 <notifications@github.com> napsal:

**Comment by mtester270** [comment]
Ako som ti už povedal napíš mi PM na AB fórum.
V skratke to ze ti po pauze už nejde prehrávanie ale titulky idú je problém sosac a on ta zjavne odpojí čiže padne connection a titulky sú predsa iná vec. Tým pádom ak to v kodi ide tak sa to nejak bude dat spravit. Len necakaj odomna ze som kuzelnik a ze to bude vyriesene v najblizsom case lebo ja za toto od nikoho nic nedostavam a mam inu robotu ako sa venoval len tomuto iste chapes.

**Comment by 1terit1** [comment]
Jasneeee. Nevím co je PM😃 mám už nějaké roky a byť jsem technicky docela 
sbehly tak téhle oblasti moc nerozumím. Jsem docela dobrý přes mobilní 
telefony. Opravuji poškozené displeje od samsungu, jako koníček. Takze 
kdybys cokoliv potřeboval z téhle oblasti, rád pomohu.

Odesláno pomocí AquaMail pro Android
http://www.aqua-mail.com


Dne 1. listopadu 2017 8:57:25 dop. mtester270 <notifications@github.com> 
napsal:
