### ISSUE TITLE
Stream Cinema - chybajuce zoznamy a triedenie

### ISSUE THREAD

**Issue by cellentano** [mx3L/archivczsk#35]
Zdravim,
v porovnani s kodi addon chybaju zoznamy serialy, koncerty, anime s podkategoriami. Jedina moznost je cez vyhladavanie, ale po zobrazeni najdenej polozky sa zobrazi zoznam streamov s rovnakym nazvom (rozdiel iba v MB).
Verzia: 1.0.0 stream-cinema.online
OpenATV 6.0

**Comment by speedo919** [comment]
Tiez sa pridavam. Vyhladat serial je dost obtiazne

**Comment by Luky68** [comment]
Pozdravujem
Pod enigma2 v plugine Stream Cinema a zozname Movies od 0-9 az po Z neide najst ziadne filmy. Ked zadam vyhladat akekykolvek film z abecedy tak vypisuje len I failed
![img_20170802_225433](https://user-images.githubusercontent.com/15214168/28894759-1db54b32-77d6-11e7-8397-f0539d2cfcce.jpg)

**Comment by bbaronSVK** [comment]
Ludkovia prepacte, ale nemam uz zariadenie s enigmou, takze to neviem poriesit.

**Comment by speedo919** [comment]
A vies pomoct s tym ako na to? Vcera som skusal upravovat sosac.
cez ftp: 0:/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/resources/repositories/xbmc_doplnky/plugin.video.sosac.ph/
ked som cokolvek zmenil, plugin sa po spusteni updatol a nic z toho. Teoreticky by mali byt vsetky veci dostupne priamo z repo kodi czsk ci pre stream cinema alebo sosac...

**Comment by mtester270** [comment]
hosi mam to spravene upravene na novy sposob ako je pre KODI (odtestovane v VTI 11.0.)

@@bbaronSVK vies ma pridat nejako aby som tam vedel spravit commit ci spravime to tak ze ti poslem zmenene subory ci ako sa to robi lebo ja github nepouzivam a python som videl 3 dni kedze som chcel skusit nieco nove?

do buducna by bolo lepsie aby som mal pristup ak bude cas tak to viem potom aj poupravovat

email: mtester270@gmail.com
aj na githube som tam regnuty

**Comment by cellentano** [comment]
Pani, to su vyborne spravy.
Urobil som update na sosac/stream cinema, ale stream cinema je stale vo verzii 1.0.0. 
![img_20170807_210839](https://user-images.githubusercontent.com/25830542/29043788-f7222626-7bbc-11e7-8a68-8372a36b0287.jpg)
![img_20170807_211429](https://user-images.githubusercontent.com/25830542/29043792-fc42c55c-7bbc-11e7-85a9-4223dc33bfb6.jpg)
![img_20170807_211448](https://user-images.githubusercontent.com/25830542/29043802-033722ae-7bbd-11e7-8356-699000f88930.jpg)

**Comment by cellentano** [comment]
Vyskusane na OpenATV 5.3 a 6.0

**Comment by mtester270** [comment]
@@cellentano ty si to aj nahodil do githubu ci ako? lebo ja som si to tiez prerobil ale len lokalne nemam to sice ako ty ale v podstate je to detto

**Comment by cellentano** [comment]
Nie to je nedorozumenie, predpokladal som, ze ste stream cinema ma update (nic som nenahadzoval, neviem ako na to), takze som len poslal foto, ako to vyzera v existujucej verzii.

**Comment by mtester270** [comment]
kedze sa asi v najblizsom case nedockate tak tu si mozete stiahnut moju upravenu verziu

https://drive.google.com/file/d/0B0eoUMRfX-JdNXdKSHh2LXdkODA/view?usp=sharing

1) stiahnut ZIP niekde rozbalit su tam 3 subory

2) pripojit sa na VU+ cez FTP (povedzme total commander) ak to neviete tak prosim pouzit uja Googla napr. https://digitalne.ellano.sk/magazin-7/item/pripojenie-linuxoveho-prijimaca-cez-ftp-k-pc
ja mam na VTI login: root a bez hesla cize nechavam prazdne

3) ak to chcete mat korektne a hned vidiet ze tam mate inu verziu tak treba prepisat 2 subory:
**addon.xml**, **changelog.txt** do cesty (cestou som si neni isty ale cca by to malo sediet)
﻿/usr/lib/enigma2/python/Plugins/Extensions/archivczsk/resources/repositories/xbmc_doplnky/plugin.video.stream-cinema/

4) prepisat hlavny subor **scinema.py** na ceste
/usr/lib/enigma2/python/Plugins/Extensions/archivczsk/resources/repositories/xbmc_doplnky/plugin.video.stream-cinema/resources/lib/

5) restart enigmy (nie GUI) pretoze si to musi prekopilovat ci kju mariu to tam robi 👍 

Spustite archivczsk prejdete na stream-cinama plugin a mali by ste vidiet verziu 1.1.0. a nasledne ine usporiadanie ponuky...
Pozor ak by vam ponukalo update (lebo vam to prehodi spat na verziu 1.0.0.) tak asi bude treba vypnut automaticke aktualizacie v nastaveniach archivczsk aspon zatial.

GL&HF

**Comment by cellentano** [comment]
Paraaaada, potvrdzujem funkcnost na OpenATV 6.0. "Klobuk dole" mtester270.

**Comment by speedo919** [comment]
Podobne. je to pecka. :-)

**Comment by mx3L** [comment]
@mtester270 
Vklude vytvor pull resp. mozem dat pristup na archivczsk-addons a mozes pushovat.

**Comment by mtester270** [comment]
lepsie je ten pristup aj do buducna takze ta poprosim ked mi to pridas tak mi napis a nejak asi buduci tyzden to tam dam lebo cez week u kolegov v cesku na raftikoch

**Comment by mtester270** [comment]
@cellentano hosi az take tazke to nie je python som videl 3 dni aj s topankami ale kedze robim v IT tak to nebol az taky problem takze ak viete kusok programovat tak by ste to zvladli 👍

**Comment by mtester270** [comment]
@mx3L cauko pozeral som ze som uz v member ale zjavne nemam access vid screen :)
![github](https://user-images.githubusercontent.com/26596112/29156565-e5eb9cd8-7da2-11e7-9b16-dd8d29776a9a.JPG)

**Comment by mx3L** [comment]
@mtester270 caves, az teraz som sa k tomu dostal poslal som invite

**Comment by mtester270** [comment]
dal som to tam tak asi by to uz kazdemu malo ponuknut auto update na verziu 1.1.1 

takze toto mozes zatvorit

**Comment by mtester270** [comment]
@mx3L neviem co tam je este potrebne spravit ale push som spravil do master len na prijmaci mi ziadny update neponuklo vies to poriesit?

**Comment by cellentano** [comment]
@mtester270 este jedna vec, pri vyhladavani titulkov sa nekoretne vyplni nazov serialu. Ale to uz je asi iny pribeh ...
![img_20170814_173805](https://user-images.githubusercontent.com/25830542/29279396-ef169466-8117-11e7-998d-166c56f819d1.jpg)

**Comment by mtester270** [comment]
@cellentano presne tak ako pises je to iny pribeh toto je problem niekde inde nie v plugine stream cinema skor to vidim na stream resolver ktory ti tam doda nazov podla toho co si vyberies za stream cize podla nazvu vidis ze to je presne ten zaciatok ako ti napise pri vybere suboru a to ze tam da kratky nazov je uz dalsi pribeh :) ja titulky neriesim vobec takze s tymto ti nepomozem
PS: ale zvacsa tam titulky mam skoro vzdy tak neviem 

@mx3L vsetko uz funguje update mi ponuklo na enigme na verziu 1.1.1 ... dik

**Comment by cellentano** [comment]
Pani, vdaka.
