### ISSUE TITLE
Stream Cinema a Sosac  premium nefunguje pretacanie,

### ISSUE THREAD

**Issue by baaluu** [mx3L/archivczsk#36]

**Comment by baaluu** [comment]
Mam Oenatv 6,0 a nedaju sa pretacat filmy,Mam zaplateny premium ucet.

**Comment by speedo919** [comment]
Po dnesnej aktualizacii UZ nejde stream cinema a este stale nejde sosac :-)

**Comment by baaluu** [comment]
Mne to ide ale zamrzne to pri pretacaní .

Dňa 7. 8. 2017 9:46 odpoludnia používateľ "speedo919" <
notifications@github.com> napísal:

**Comment by s3n0** [comment]
Rovnako tak je to aj u mna - nefunguje posuvanie videi v doplnku "Sosac". Pri ostanych moduloch pluginu ArchivCzSk som to zatial nevyskusal (nebolo vela casu, k satelitnemu boxu som sa dlhsi cas nedostal). Ked spustim Sosac doplnok, najdem film a spustim jeho prehravanie, tak zacne sa prehravat a funguje OK. Akonahle sa pokusim o posun videa dopredu ci dozadu, tak bezec (ukazatel) pozicie videa sa posunie, kym  video+zvuk sa zastavia a uz viac nejdu nijak spustit (tlacidla PAUSE alebo PLAY vobec nereaguju ). Pomoze potom znovu-spustenie konkretneho filmu, avsak cez zoznam najdenych filmov. Plugin samo o sebe inak nezamrzne. Jednoducho sa to zasekne iba to streamovane video, vzdy pri pokuse o jeho posuvanie dopredu ci dozadu a zostane tam len cierna obrazovka. Potom pomoze uz len EXIT tlacidlo do zoznamu hladanych filmov (krok zpäť) a znovupustenie filmu celkom od zaciatku (co je dost frustrujuce).

WTF "pretacanie" ? Kde to zijeme chlapi ?! snad nie v 15. stor. :) ! Nic v zlom samozrejme, ale uz sa treba konecne naucit tie spravne pojmy. Pisme si radsej o "posuvani videa" a nie o "pretacani" - napriklad VHS pasiek, magnetofonovych kaziet, kotucov a podobne... ako tomu bolo pred 20 rokmi.

Pouzivam inac OpenATV 6.0 image. Poskytol by som tiez vypis DebugLOG / CrashLOG, ale to az bude zase niekedy viac casu :( ... cize najskor zajtra alebo aj neskor. Musim v OpenATV 6.0 najprv DebugLOG povolit, potom box zrestartovat, "sposobit chybu" a pokial sa v Debug LOG nieco ukaze ohladne tohto problemu, hodim vam to sem do "ISSUES".

**Comment by speedo919** [comment]
U mna sa to po minute zastavi tak ci tak a pretacanie tiez nejde. Jedine co ide su videa co su uz v HTML5. Tie idu aj viac ako minutu ale nedaju sa pauznut ani pretacat...

**Comment by baaluu** [comment]
Ja som písal na stream a že vraj máme chybu v software.


Dňa 26. 8. 2017 2:46 odpoludnia používateľ "speedo919" <
notifications@github.com> napísal:

**Comment by benko21** [comment]
Moj dnesny poznatok s problemom pretacania.Z hdd som vymazal vela nepotrebnych veci a zrazu vsetko funguje

**Comment by s3n0** [comment]
No tak ja mam na HDD dostatok volneho miesta (16GB USB kluc formatovany priamo pod Enigmou na ext3 format). Takze podla mna problem nebude v dostupnej volnej kapacite na disku :) .

**Comment by benko21** [comment]
Neviem,ale ja tam mam 320gb disk a ked so map viac ako polovicu disku plneho bobol aklj casovac nahravania.Nahravanie sa spustilo aoe iba cierna obrazovka.Premazanim disku sa problem odstranil ako aj dnes pri pretacani.Mam Xtrend 7500 a poslednu OpenATV enigmu

**Comment by ivanisko** [comment]
@mx3L Mate poneti kde by mohl byt problem s pretaceni, pauzou atd? Rad bych se pustil do opravy. Aspon rada kde zacit. Diky

**Comment by s3n0** [comment]
samozrejme je to chyba Sosac - doplnku... samotny ArchivCzSk je len zjednotenie viacerych doplnkov do jedneho... v ostatnych doplnkoch co som vyskusal aspon ja, tak prehravanie funguje beztak na inych principoch - napriklad online videa sa nedaju vobec pauzovat alebo posuvat a musis si to pozerat komplet od zaciatku... videa cez Sosac prehravat je mozne od posledneho update len z prvej minuty a dost, potom sa video zastavi resp. vrati sa zase do MENU Sosaca a plus este k tomu je tam nefunkcna pauza :-/

**Comment by ivanisko** [comment]
Jojo, clovek si musi zaplatit premium ucet na streamuj.tv a pak zadat prihlas. udaje. Jinak se zobrazuji 1:38 dlouha videa.
Pauza ani pretaceni nefunguji vzdy se zasekne a konec.

Jen jsem nikde v sosac kodu nenasel neco o prehravani a v archivCZSK je trida player. Proto ten dotaz zda chyba muze byt v archivu napr. stara knihovna pro prahravani streamu.

Treba nekde neco zmenilo streamuj.tv a proto to nejde.

Diky

**Comment by baaluu** [comment]
Po poslednej aktualizacii sa nedaju niektore filmy a casti serialov spustit vraj prihlasovacie udaje v plugine nie su nastavene pritom mam premium a som prihlaseny.Ostatne veci idu.

**Comment by ivanisko** [comment]
Taky se mi to stava, a proto jsem vepsal sve prihlas. udaje primo do kodu.

/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/resources/repositories/xbmc_doplnky/plugin.video.sosac.ph/resources/lib/sosac.py

V sosac.py na 325 radku je tato metoda 
`def set_streamujtv_info(self, stream):`
a v ni jsem nahradil tyto promenne

self.streamujtv_user za "prihlasovaci jmeno"
self.streamujtv_pass za "heslo"

a hned to funguje lepe. Jen proste nejde pretacet a pauzovat.

**Comment by malepada** [comment]
Pouzivam ArchivCZSK v OpanATV 6.0 a takisto nie je mozne ani s premium uctom posuvat video na SOSAC ale aj na inych archivoch. Len niektore novsie videa ako napr. archivy TV vysielania je mozne aj posuvat.
Na Sosaci v KODI je posuvanie normalne mozne, Radsej by som vsak pouzil ArchivCZSK v satelite lebo ma vyrazne lepsi obraz ako KODI v Androide.

**Comment by mtester270** [comment]
@ivanisko problem moze byt kade tade. Ak to chces hladat tak hura do toho hint odomna stream.resolver alebo potom niekde v archvieCZSK. Pripadne mi napis na ab forum PM

Mne v stream cinema na vti11 vsetko funguje ako ma. Sosac tam moze mat nejake specificku vec pre ktoru to prestalo chodit. Ked bude nova verzia archivuCZSK tak sa teoreticky na to budem vediet pozriet ale budem potrebovat ucet na sosac takze niekto poslite na ab forum do PM myslim ze ma najdete lahko. Takze zatvorim

**Comment by simi168** [comment]
Páni tak 3 dni riesim VU+SOLO s tym ze vsetky image robia vyrobcovia tak, ze to len tak tak vojde do flasky a RAM v tomto stroji je tiez biedna. S tymto suvisel moj velky problem a to prihlasovanie do Premium uctu cez Sosac.
Ked som nemal zadane meno a heslo na stream tv tak film spusti ale po cca 2 minutach je koniec pozerania. Ked som zadal do sosaca meno a heslo na stream tv tak mi film nespustilo pretoze RAM uz bola tak plna z dalsieho procesu prihlasovania ze uz nema kde pchat priebezne data filmu.
Je to len moj laicky nazor a neviem to rukolapne potvrdit ale myslim ze ten system funguje takto nejako.
Po 3 dnoch badania, preinstalovavania a vymazavania pluginov aby som mal dost RAMky ma napadla spasna vec a to vyriesit to swapovanim na USB.
Pichol som USB , inicializoval som ho a cez doinstalovany swap manager - plugin som vytvoril SWAP subor.
Sosac ide bezvadne a dokonca funguje uplne plnohodnotne aj pretacanie dopredu, dozadu pauza, proste vsetko.
Idem to este testovat ale myslim si ze takto to asi pojde a bez tociaceho sa kolieska v lavom hornom rohu.
Bol to porod ale podarilo sa :-) Funguje aj time shift a komplet vsetko.
