### ISSUE TITLE
Open ATV 6.1 - chybějící HTTP protokol

### ISSUE THREAD

**Issue by xdedek** [mx3L/archivczsk#37]
Nedávno jsem na oatv 6.0 zjistil problémy s padajícím videím, rozhodl jsem se přeinstalovat OS a rovnou jsem se rozhodl pro upgrade na 6.1 .  Po instalaci kromě HLS protokolu, kde svítí nápis NENAINSTALOVÁN, což bylo i v předchozí verzi a vše víceméně chodilo je stejný nápis i u HTTP protokolu. Předpokládám tedy, že právě proto plugin befun a další načtou seznam videí, pokusí se i spustit, ale nakonec se zobrazí jen černá obrazovka a informační panel o stavu přehrávání, ale nic se prostě nespustí.
Víte někdo co s tím? Nebo jak doinstalovat chybějící protokoly? 
Přeinstalovat GStreamer a další jsem zkoušel, ale nic nepomohlo..

**Comment by speedo919** [comment]
Ehm. No ono Befun a Sosac nejdu uz dlhsiu dobu. Jedine premium a to zatial nie je dokoncene

**Comment by xdedek** [comment]
No ještě včera šel, ale spustilo se jen kousek videa a za 20 sekund se to vyplo, koukal jsem se na routeru, tak vypadalo to, že se prostě stáhlo několik dat, a pak přestalo stahovat další, přitom video ještě běželo z cache..

jinak opravuji své chybné pojmenování HTTP a HLS jsou protokoly.
díval jsem si i do nainstalovaných balíčků a našel jsem, že je tu určitý rozpor, balíček HLS mám:
gstreamer1.0-plugins-bad-hls

pokusil jsem se i ze zoufalosti doinstalovat balíček:
gstreamer1.0-plugins-bad-neonhttpsrc

ale beze změny..

**Comment by baaluu** [comment]
Ja mam premium sosac aj stream cinema ide ale nejde pretacat.Bez premka to ide ako test 1,20min a potom tma.Dufam ze dalsou aktualizaciou to pretacanie opravia.
