### ISSUE TITLE
ARCHIV CZSK - SOSAC (modre tlacitko sposobuje pad)

### ISSUE THREAD

**Issue by petertrn** [mx3L/archivczsk#38]
Ahojte. Pouzivam na VU+DUO2 a VU+ ZERO image VTI 11x a pri spusteni pluginu nemozem vstupit do nastaveni cez modre tlacitko. Vzdy sa to sekne a musim spravit natvrdo OFF/ON. Skusal som aj VTI 9.x a robi to to iste. Nemomohla ani zmena skinu na AtileHD atd... Nejaka pomoc? Potrebujem cez nastavenia zadat pristupove udaje a hesla na Sosac. Dakujem

**Comment by georgge464** [comment]
Zdravim. Mas nainstalovanu starsiu verziu SKCZ archivu 7.3. Treba ju odinstalovat a naistalovat novsiu 7.4

**Comment by petertrn** [comment]
Dakujem. Uz to ide korektne.

**Comment by mtester270** [comment]
Problem je full hd skin na televizore ak by si mal HD ako AtilaHD tak vsetko funguje. Dany problem bhde vyrieseny v novej verzii
