### ISSUE TITLE
SOSAC - premium placeno - přesto nefunguje

### ISSUE THREAD

**Issue by petrger** [mx3L/archivczsk#39]
Dobrý den, 
používám VU+ a bohužel stále mám problém se Sosáčem.. Stream Cinemu nechci ani vidět, při prémiovém placení a zadání do ARCHIV CZ/SK - Stream Cinema rychlost max 320 Kb/s.. Sosac jede v pohodě i 2 Mb/s.. Problém mám ovšem v tom, že i přes zadání správných údajů do Sosace, přehraje pouze první minutu a půl...Údaje jsou ze Streamuj.tv... Kde je chyba?? Je možné, že ve VU+ zadám heslo / například PEPA /, vypíše SOSAC na přihlašovací obrazovce PEPA*kurzor* ?  Není to pak tím, že nebere heslo PEPA, ale PEPA*kurzor*?  Prosím o radu, mám doma dlouhodobě nemocného juniora / 5 let / a rád bych mu opět pouštěl pohádky.. Děkuji

**Comment by petrger** [comment]
Používám VU+ZERO VTI 11,0 
Některé filmy / mám zaplaceno premium u Streamuj.tv / ukáží délku např. 1.12.46, ale odehrají 1,38 a padnou... Některé automaticky ukáží jen 1,38 minuty..... Kde je problém???

**Comment by vatlach** [comment]
vkladat cez dialkove a nie cez virtualnu klavesnicu(xcursorx) a vsetko bude ok.

**Comment by petrger** [comment]
Prosím o info jak to dokázat.. Když najedu do Archivu CZ/SK a pak do Sosace, pod modrou záložkou je možnost vložení loginu a hesla.. Ovšem jak chci zadat heslo, vyjede virtuální klávesnice... Jak zadám heslo bez ní??? Děkuji

**Comment by vatlach** [comment]
nevstupovat cez OK, ale normalne ako na mobile vlozit viacnasobnym stlacanim klavesu.

**Comment by petrger** [comment]
Skvělé!! Děkuji moc!!!! Funguje!!!! WOW..... Přetáčení ne, ale to je maličkost :)

Díky
