### ISSUE TITLE
stahovanie video suborov

### ISSUE THREAD

**Issue by RasterBob** [mx3L/archivczsk#4]
Zdravim,

Chcel by som sa opytat na jeden problem, ktory mam pri stahovani suborov v SK/CZ archive. 
Ked prejdem do archivu, napr. rtvs.sk, priamo k video suboru kde mi ukazuje [360] nazov suboru.mp4, dam stahovat video subor ale stiahne sa len subor velky okolo 30-50kB s nasledovnym obsahom :

#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:19
#EXT-X-MEDIA-SEQUENCE:0
#EXTINF:10.0,
media-b1125608_0.ts?wowzasessionid=1207148875&auth=b64%3AX2FueV98MTQ0NTk4Mzk1OHw0MWU1MTg5MTcwZGFiNDRmOWJhYWYwMmM1MTE4MjVhOGJlNzI1OWJm
#EXTINF:10.0,
media-b1125608_1.ts?wowzasessionid=1207148875&auth=b64%3AX2FueV98MTQ0NTk4Mzk1OHw0MWU1MTg5MTcwZGFiNDRmOWJhYWYwMmM1MTE4MjVhOGJlNzI1OWJm
#EXTINF:9.92,
media-b1125608_2.ts?
..........

vedeli by set mi, prosim, poradit ako dosiahnem toho aby sa mi stiahol video subor namiesto tohto extm3u obsahu? 

Dakujem.

**Comment by mx3L** [comment]
Zdravim,
Pokusim sa pridat stahovanie hls streamov do dalsej verzii

**Comment by mx3L** [comment]
Stahovanie HLS streamov pridane v 0.72-beta.6 verzii
