### ISSUE TITLE
Sosac a E2 a VTI 11.02

### ISSUE THREAD

**Issue by sinacik** [mx3L/archivczsk#40]
Pri premium sa za menom a heslom sa zapise XcursorX .. Bolo by mozne to opravit pri nejakej akcii? Diky

**Comment by frenky55** [comment]
to je poho, mne na uno 4k a vti 11.02 po stlaceni modrej zhasne obrazovka, pripadne ked kliknem na nastavenie pluginu cierna obrazovka, alebo boot obrazok. Skusal som verzie od 0.72 po 0.74

**Comment by mtester270** [comment]
XcursorX na stream cinema to je opravene a bude to opravene v novej verzii na archivCZSK

pad pri nastaveniach sposobuje ze mas FHD skin na enigme ak by si mal HD taka ti to pojde

dany problem bude tiez odstraneny v novej verzii
