### ISSUE TITLE
Prosba

### ISSUE THREAD

**Issue by 1terit1** [mx3L/archivczsk#41]
Zdravim . Taky mam problem se sosacem . Presneji za jmenem uctu se mi objevi XcursorX . Jak tady nekdo psal , tak jsem jiz heslo na streamujtv zmenil tak aby za nim byl ten XcursorX ale u jmena mi ta zmena nejde . Nevite nekdo jak nato ?? Dekuji za odpoved

**Comment by sinacik** [comment]
settingy su ulozene v /etc/enigma2/settings:
config.plugins.archivCZSK.archives.plugin_video_sosac_ph.streamujtv_user=
config.plugins.archivCZSK.archives.plugin_video_sosac_ph.streamujtv_pass=
config.plugins.archivCZSK.archives.plugin_video_sosac_ph.streamujtv_location=

**Comment by speedo919** [comment]
ja tam XcursorX nemam a nejde mi to.... location mam 1 (neviem ci je to ok a co to ovplyvnuje)

**Comment by 1terit1** [comment]
Zdravim. Me se to uz podarilo rozchodit J  Jedny problem mam , ze mi nepretaci nektera videa na SOSACI L Nenapada vas nekoho , cim by to mohlo byt ??

**Comment by speedo919** [comment]
toto robi aj mne. videa ktore su uz v html5 idu ok. ostatne po minute stop a pretacanie tiez nejde

**Comment by eraser17** [comment]
Zaplatil som si premium na mesiac a tiez mi to nejde prihlasit v E2 ? ked zadam prihlasovacie udaje cez plugin tan to tam prihodi to xcursorx a ked to v tom settingu co tu je popisany prepisem tak sa to plugine aj tak nezmeni. vie dat niekto navod ako na to?

**Comment by ivanisko** [comment]
Taky se mi to stava, a proto jsem vepsal sve prihlas. udaje primo do kodu.

/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/resources/repositories/xbmc_doplnky/plugin.video.sosac.ph/resources/lib/sosac.py

V sosac.py na 325 radku je tato metoda
def set_streamujtv_info(self, stream):
a v ni jsem nahradil tyto promenne

self.streamujtv_user za "prihlasovaci jmeno"
self.streamujtv_pass za "heslo"

a hned to funguje lepe. Jen proste nejde pretacet a pauzovat.

**Comment by mtester270** [comment]
XcursorX bude opraveny v novej verzii archivCZSK

**Comment by dust111** [comment]
Ahojte potrebujem poradit,nemozem sa prihlasit do sosaca a aj do stream cinema cez modre tlacidko na ovladaci....skusal som vseto co tu je napisane a stale nic....cez FTP sa to neulozi...po restarte sat.boxu to tam neni vobec neviem ako to vyriesit...mate niekto napada ako sa to da?
dakujem za pomoc

**Comment by sinacik** [comment]
Verzia vti a ktoré vu

**Comment by dust111** [comment]
mam nakonfigurovanu E2 openAtv 6.1 od ellano.sk skusal som aj cistu a aj openPLi 6.2 aj 6.1 a stale to iste....

**Comment by dust111** [comment]
xtrend et8000

**Comment by sinacik** [comment]
Zaplať si streamuj.tv a sem som to zapísal, mám atv6.2 a rozchodil som to
vo vti11,13, ručne nezapisuje tipujem na práva..po edite resetni stroj..
pekny vecer
/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/resources/repositories/xbmc_doplnky/
plugin.video.sosac.ph/resources/settings.xml

 <setting label="30106" id="streamujtv_user" type="text" default="SEM
LOGIN" />
        <setting label="30107" id="streamujtv_pass" type="text" default="SEM
PASS" option="hidden" />
