### ISSUE TITLE
Formuler F1 s Openatv 6,0 neustale sekanie v archivoch cinema premium 

### ISSUE THREAD

**Issue by baaluu** [mx3L/archivczsk#42]
Kde je chyba ,bude sa to riesit.Naco je mi premium ked vecsina seka a neda sa pretacat.Nech mi nikto nehovori ze to je v mojom softe lebo predtym to vsetko slapalo v pohode az kym sa sosac a stream cinema nespoplatnili.Vyhovorka zatazenia serveru a pod.

**Comment by speedo919** [comment]
stream cinema ma v ponuke aj filmy vo vysokej kvalite (velkost aj 12gb) a tie pri rychlosti (max 1500kbs) nema sancu streamovat. Alebo ti to seka aj pri filmoch beznej velkosti? (Ta je uvedena za nazvom suboru)

**Comment by baaluu** [comment]
Áno aj pri 380mg 720p napr.Teoria v. Tresku


Dňa 21. 9. 2017 9:06 odpoludnia používateľ "speedo919" <
notifications@github.com> napísal:

**Comment by frenky55** [comment]
neviem, ale na dm525 fo ide v pohode

**Comment by mtester270** [comment]
a si si isty ze mas dobre nastaveny ucet na stream cinema?? skus si dat nastavenia a pozri si VIP days ake cislo tam vidis?? ak vacsie ako 0 tak je to OK ... tym padom bude niekde inde problem mozno skus iny image na skusku alebo to cele preistaluj myslim archivCZSK

**Comment by bbaronSVK** [comment]
Este moze byt problem v samotnom mene/hesle - ak obsahuju “specialne znaky” ako diakritika alebo aj ciarka tak to moze byt problem. Treba pouzit alpha umericke meno/heslo.
