### ISSUE TITLE
TA3 archiv

### ISSUE THREAD

**Issue by beri23** [mx3L/archivczsk#46]
aktualne mi nejde prehravanie z TA3 archivu. zoznam programov je tam, kliknem nan a nespusti sa prehravanie. prevazne pozeram motoring

**Comment by mtester270** [comment]
Autor to uz dlho nealtualizoval a ja to za neho momentalne robit nejdem ak moc chces vieme sa dohodnut ze spravim ale zadarmo to nebude. Zatvaram
