### ISSUE TITLE
Update deb image

### ISSUE THREAD

**Issue by adaminko** [mx3L/archivczsk#48]
Zdravím
neviem prečo nedôjde k updatu czsk pluginu, keď je image deb (Merlin,Newenigma),pri ipk image update hneď nabehne (openatv).Ide mi o stream cinema. Neviem ako to dostať do dreamu 520.Skúšam posledné inš. súbory.Vďaka za info

**Comment by mtester270** [comment]
preco to nejde teraz neviem povedat ale stream cinema tam dostanes jednoducho :)
******* prede tym si sprav zalohu :)

1) stiahnes toto
https://github.com/mx3L/archivczsk-doplnky/raw/master/xbmc-doplnky/repo/plugin.video.stream-cinema/plugin.video.stream-cinema-1.1.6.zip
2) prekopcis do pristroja na cestu
/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/resources/repositories/xbmc_doplnky/plugin.video.stream-cinema/
3) restart

neviem ti ale zarucit ci to pojde preto lebo  vela veci nejdem vysvetlovat
GL&HF

**Comment by adaminko** [comment]
Ďakujem, funguje to.

**Comment by mtester270** [comment]
Problem ti to ale neriesi lebo tebe neponukne update ani k jednemu doplnku je to tak? Ak je to tak... Tak mas problem v tom ze n v danom image nemas naistalovany 'curl' s najvacsou pravdepodobnostou.

**Comment by adaminko** [comment]
Veď to je ten problém, že sa jedná iba o image deb(merlin.newnigma...) ipk image bez problémov. Kôli tomu som si myslel, že v inštalačke deb niečo oproti ipk chýba,ale aj tak vďaka a kde najdem tem curl?

**Comment by mtester270** [comment]
skus cez telnet
opkg install curl
ale netusim v tych tvojich image ako sa to tam robi takze skus uja googla ak ti to nepojde

**Comment by adaminko** [comment]
Ďakujem ti veľmi pekne, update prebehol bez problémov a všetko ide ako má.

**Comment by mtester270** [comment]
nz, dakovania potom prijmam aj na url ktoru mam v profile 💃
