### ISSUE TITLE
archiv markiza Vu solo s Open ATV

### ISSUE THREAD

**Issue by dusan77** [mx3L/archivczsk#49]
Dobrý deň
Mám inštalovaný obraz Open ATV, v rámci pluginov je CZ/SK archív, v ňom je markiza.sk
Žiaľ nie sú tam dostupné všetky relácie. Moja žena zvykla pozerávať jeden seriál "sandhya" - to tam nie sú žiadne súbory/epizódy vôbec dostupné na prehratie.
Prosím Vás vedeli by to nejako opraviť ?

vďaka
s pozdravom
dušan

**Comment by mtester270** [comment]
no asi preto ze to ide cez VOYO
(http://videoarchiv.markiza.sk/video/sandhya-svetlo-mojho-zivota) vidis to tam vsak?
... zaplat si a pouzi plugin pre Voyo SK 
za mna som to skusil na 7 dni zadarmo a uplna katastrofa napr. LetsDance len v SD (turbo kocky) rozliseni a to si za to platis oproti tomu v doplnku markiza tam je video v 720p 💃  

ale je dost mozne ze to je len problem v tomto doplnku.

takze zatvaram

**Comment by dusan77** [comment]
zdravím
vďaka
len toľko, že cca v septembri tá sandhya tam v bežnom archíve (nie cez
voyo) ešte bola dostupná

s pozdravom
dušan

Dňa 31. októbra 2017, 9:48, mtester270 <notifications@github.com>
napísal(-a):
