### ISSUE TITLE
instalatin error in posinst line 134 (image merlin OE 2.0)

### ISSUE THREAD

**Issue by ghost** [mx3L/archivczsk#5]
Downloading http://dl.bintray.com/mx3l/generic/enigma2-plugin-extensions-archivczsk_0.72_beta_6_20151108_all.ipk.
Installing enigma2-plugin-extensions-archivczsk (0.72_beta_6_20151108) to root...
package enigma2-plugin-extensions-archivczsk recommend installing python-compression
package enigma2-plugin-extensions-archivczsk recommend installing python-email
package enigma2-plugin-extensions-archivczsk recommend installing python-youtube-dl
Installation for mips32el platform
Installing rtmpdump
Installing pngquant...
Installing servicemp4...
//var/lib/opkg/info/enigma2-plugin-extensions-archivczsk.postinst: line 134: python: not found
.....found enigma2 for mips32el platform, version: 
sh: 201304: unknown operand
.....version for old images will be used
Installing neccessary Python libraries
found Python 2.7
restoring categories...
Clearing temp folder...
Installation of archivCZSK was successfull
Configuring librtmp1.
Configuring enigma2-plugin-extensions-archivczsk.

**Comment by mtester270** [comment]
Stare zatvaram
