### ISSUE TITLE
VU+ SOLO openpli 

### ISSUE THREAD

**Issue by drozkar** [mx3L/archivczsk#50]
ve třech těchto přijímačích s tímto img mi nejdou video doplňky. U všech to píše že to autor musí opravit.
Tv doplňky fungují.
Kdy mám hledat chybu prosím

**Comment by mtester270** [comment]
no najskor mi povedz o akych doplnkoch konkretne sa bavime a potom by bolo fajn napisat o aky prijmac sa jedna a o aky image??

**Comment by drozkar** [comment]
Video doplněk nejde spustit žádný (befun, stream cinema, online...) Jsou to vu+ solo. a Img jsem zkoušel jak openpli 6, tak to čtyřkové poslední, Výsledek všude stejný

**Comment by mtester270** [comment]
Aku mas napisanu verziu pri stream cinema? A aku verziu archvivu si si naistaloval?

**Comment by drozkar** [comment]
zkoušel jsem poslední i předposlední. nefunguje žádný z video doplňků

**Comment by mtester270** [comment]
https://ufile.io/mgeyj

Toto si stiahni a prepis to v plugine a restartni krabicu a potom napis co ti napisalo
Cestu k pluginu si dufam zvladnes najst

.../Plugins/Extensions/archivCZSK/gui/

**Comment by drozkar** [comment]
nahrál jsem, restartoval, aktualizoval doplňky a u video doplňků stále stejná chyba. "autor musí opravit". U všech. Vidím jen seznam doplňků, ale ani jeden nejde spustit

**Comment by mtester270** [comment]
No pokial si spravil to co som ti napisal a spravil si to dobre a restartol krabicu tak ti muselo napisal
Autor musi opravit + presnu chybu teda dalsi text

**Comment by drozkar** [comment]
Nebyl jsem u přístroje a máš pravdu, chyb to vypisuje mnoho. Posílám do mailu, snad to dojde, děkuju moc

**Comment by mtester270** [comment]
Na aky mail si to poslal? Lebo ja som nic nedostal. Kludne to daj sem

**Comment by drozkar** [comment]
https://1drv.ms/i/s!AgtFUUIopTnkg_YIATDH4ezvjnOBgA

**Comment by drozkar** [comment]
snad to bude stačit. Díky za podporu

**Comment by mtester270** [comment]
Tak este raz detto ta poprosim ... Tu je subor
https://www.ulozto.cz/!jNHa1KpSrsB5/exception-py

A posli screen lebo nevidim ten koniec co je dolezite

**Comment by drozkar** [comment]
https://1drv.ms/i/s!AgtFUUIopTnkg_YNLc2RD20Df4OaZA

**Comment by mtester270** [comment]
Chyba ti tam stream rewolver podla vsetkeho do xbmc doplnkov si rozbal toto https://github.com/mx3L/archivczsk-doplnky/raw/master/xbmc-doplnky/repo/script.module.stream.resolver/script.module.stream.resolver-1.6.42.zip
A skus restart aj ked nechapem ako si to potom naistaloval

**Comment by mtester270** [comment]
moze byt takze zatvaram v novej verzii na to pozriem
