### ISSUE TITLE
Bude aj enigma2 plugin-extensions-archivczsk_0.74-20170415 deb pre DM900???

### ISSUE THREAD

**Issue by kostik123456** [mx3L/archivczsk#51]
Pekný deň, chcem sa spýtať autora či bude aj deb verzia pre Dreamboxy DM900 0.74 20170415?
Nikde ju nemôžem nájsť...
Ešta jedna otázka, v originálnom image experimental mi nejde automatická aktualizácia archívov, čo z tým???
Pekný deň.

**Comment by mtester270** [comment]
Auto aktualizacia nejde preto lebo curl
opkg install curl
Verzia bude nova a bude aj deb len si treba pockat a podporit nezaskodi

**Comment by kostik123456** [comment]
Ahoj, Tvoju prácu si moc vážim. kam Ti to mám poslať.
Pekný večer.
PS – Terajšia verzia sa dá prosím nejak opraviť aby sa to aktualizovalo?

Odesláno z aplikace Pošta pro Windows 10

Od: mtester270
Odesláno:úterý 31. října 2017 20:02
Komu: mx3L/archivczsk
Kopie: kostik123456; Author
Předmět: Re: [mx3L/archivczsk] Bude aj enigma2plugin-extensions-archivczsk_0.74-20170415 deb pre DM900??? (#51)

Auto aktualizacia nejde preto lebo curl
opkg install curl
Verzia bude nova a bude aj deb len si treba pockat a podporit nezaskodi

**Comment by mtester270** [comment]
No aspon niekto podakuje.
Opravis to tym ze si doinstalujes 'curl' ako som som uz pisal ak nepomaha tak vyckaj na novu verziu. 
Ps: pozri profil je tam stranka

**Comment by kostik123456** [comment]
ProsímŤa, kde to mám stiahnuť  **opkg install curl** a kde nainštalovať, prekopírovať cez telnet.
Moc ďakujem.

**Comment by mtester270** [comment]
Pozeram ze asi nemas ani tucha co som ti napisal naco si potom kupujes taky box doporucujem studovat...
To co som ti napisal je prikaz ktory sa zada ked sa pripojis na dm900 cez telnet... Napr. Cez windows je putty.exe v mobile napr apka JuiceSSH

**Comment by mtester270** [comment]
Pozeram ze asi nemas ani tucha co som ti napisal naco si potom kupujes taky box doporucujem studovat...
To co som ti napisal je prikaz ktory sa zada ked sa pripojis na dm900 cez telnet... Napr. Cez windows je putty.exe v mobile napr apka JuiceSSH

**Comment by mtester270** [comment]
Pozeram ze asi nemas ani tucha co som ti napisal naco si potom kupujes taky box doporucujem studovat...
To co som ti napisal je prikaz ktory sa zada ked sa pripojis na dm900 cez telnet... Napr. Cez windows je putty.exe v mobile napr apka JuiceSSH

**Comment by kostik123456** [comment]
Ale mám, inštalujem si cez telnet pár pluginov jako HDGlass, GSU, Live Football apod. Len nepoznám tie všelijaké názvy tak preto ma to zmiatlo.
Prijímačov som už nakonfiguroval pre známých dosť ( VU+ Solo 4K, VU+ Uno 4K a najnovší DM900 atd…), čiže viem.
Ďakujem za radu, budem čakať na opravu.
Pekný deň.

Odesláno z aplikace Pošta pro Windows 10

Od: mtester270
Odesláno:středa 1. listopadu 2017 14:46
Komu: mx3L/archivczsk
Kopie: kostik123456; Author
Předmět: Re: [mx3L/archivczsk] Bude aj enigma2plugin-extensions-archivczsk_0.74-20170415 deb pre DM900??? (#51)

Pozeram ze asi nemas ani tucha co som ti napisal naco si potom kupujes taky box doporucujem studovat...
To co som ti napisal je prikaz ktory sa zada ked sa pripojis na dm900 cez telnet... Napr. Cez windows je putty.exe v mobile napr apka JuiceSSH
