### ISSUE TITLE
newenigma2  daily 30.10.2017 na dm7080  OE 2.5

### ISSUE THREAD

**Issue by Petriiik** [mx3L/archivczsk#52]
po nainstalovani enigma2-plugin-extensions-subssupport_1.5.4-20160215_all.deb
enigma2-plugin-extensions-archivczsk_0.74-20170415_all.deb
nenabootuje do grrafickeho rozhrania

**Comment by mtester270** [comment]
Skus byt trosku konkretnejsi? Nespusti sa archiv alebo ti padne cely skin. Ak tak posli crash log

**Comment by Petriiik** [comment]
cez cmd nainstaluje bez chyb
ale ked ho dam restartnut nenastartuje graficke rozhranie, neda sa s tym nic robit. pockal som ked som cez konzolu uvidel ze nastartovala siet, prihlasil sa a spustil recovery mod. Skusim znovu cez vikend.
instalaciu som robil apt-get update, dpkg -i enigma2-plugin-extensions-subssupport_1.5.4-20160215_all.deb,dpkg -i enigma2-plugin-extensions-archivczsk_0.74-20170415_all.deb. pri instalaci bez chyb len napise ze nasiel pearl 2.7.

**Comment by mtester270** [comment]
Treba log lebo asi to na niecom padne bez toho neviem pomoct

**Comment by Petriiik** [comment]
V piatok skusim spravit

**Comment by mtester270** [comment]
Mas ten log ci nie? Lebo zatvaram aby to bolo ciste na novu verziu.

**Comment by Petriiik** [comment]
sorry 
spravilo to tu istu chybu ale nedopatral som sa k logu 
tvarilo sa to ze to spravilo to do /tmp ale nic sa tam neulozilo

**Comment by mtester270** [comment]
Log je na /media/hdd/

**Comment by mtester270** [comment]
zatvaram asi ti nova verzia pojde lebo som tam spravil nejake fixy pre OE2.5 teda mam potvrdene ze na DM to ide
