### ISSUE TITLE
Nejde mi stahování filmu ve Stream Cinema, po zahájení stahování nastane zelená smrt

### ISSUE THREAD

**Issue by 1801** [mx3L/archivczsk#55]
Nejde mi stahování filmu ve Stream Cinema, po zahájení stahování nastane zelená smrt, mám nejnovější verzi Stream Cinema 1.1.8,  je to v Dreamboxu DM 7020 HD v2, v image DMM Experimental OE2.0, mám taky správně zvolenou cestu k ukládáni na HDD, mám na webshare.cz zaplacen VIP účet, a je i aktivní,  v pluginu Stream Cinema jsem přihlášen stejnými údaji jak v PC, přehrávání filmů mi normálně funguje, poradíte mi kde by mohla být chyba? dal bych sem i crashlog, ale asi to sem nejde dát?

**Comment by mtester270** [comment]
napis mi SS na fore a naistaluj si TeamViewer pred tym lebo to potrebujem vidiet co tam mas za bordel podla toho co som ti uz odpisal tam nemas nieco dobre ... takze v SS sa dohodneme na termine a pozriem ti to...
