### ISSUE TITLE
v1.0 bug-y

### ISSUE THREAD

**Issue by frenky55** [mx3L/archivczsk#56]
Dreambox 525
openatv-6.1-dm520-20171206
-nezobrazuje booklet filmu v zozname

dreambox-image-deb-dm520-20171128
-pri zadavani loginu pre stream cinema modul, potvrdenie cez ok na OSD klavesnici neulozi login a heslo(uloženie cez zelene tlačidlo funguje OK)
-pri výbere titulkov vždy reboot

**Comment by mtester270** [comment]
Dik za prispevok zatvaram kedze nevies citat... Chyba log
