### ISSUE TITLE
v1.0 Dreambox 7020HD

### ISSUE THREAD

**Issue by aaabaloo** [mx3L/archivczsk#57]
Na DM 7020HD s OE2.0 (exp 16.02.2017) pri pokuse spustit, resp, este pred vybratim kvality streamu, to vyhodi chybu pluginu a hlasku, ze autor ho musi aktualizovat. Instalaciu som urobil manualne, pretoze pokus instalovat to "online" (opkg install http://gith.....) zlyhal chybou "opkg_download: Failed to download http://git.../archivczsk_1.0-20171205.ipk, wget returned 1.". Skusal som iVysilani a Prima Play. Prikladam log. Da sa to na tomto HW este nejako vyriesit?
[archivCZSK.log](https://github.com/mx3L/archivczsk/files/1536482/archivCZSK.log)

**Comment by mtester270** [comment]
Predpokladam ze prima ani ivysilani ti neslo ani na starsej verzii pluginu ci sa mylim?

**Comment by aaabaloo** [comment]
Pred upgrade na v1.0 som pouzival v0.73, tam mi to islo, aj prima aj ivysilani. Staru verziu som si pre istotu komplet odlozil. Ak by pomohlo keby som Ti poslal nejaky subor z tej zalohy, tak daj vediet. dik

**Comment by mtester270** [comment]
Zajtra ti napisem rano nemam tu pc a ani sa mi uz neche radsej si pozrem vklude futbal.

**Comment by mtester270** [comment]
Tak len zo srandy prepis toto na ceste .../archivczsk/engine/tools/
[util.py.txt](https://github.com/mx3L/archivczsk/files/1536735/util.py.txt)

Vymaz priponu txt nahraj do boxu daj restart a skus ... Povodny subor si radsej odloz ☺️

**Comment by aaabaloo** [comment]
Nepomohlo, prikladam opat log. Dopozeraj v klude futbal a ked bude cas daj vediet ci pomoze nieco z tej zalohy. Dakujem za ochotu. 

[archivCZSK.log](https://github.com/mx3L/archivczsk/files/1536839/archivCZSK.log)

**Comment by mtester270** [comment]
Staru verziu neriesim ani nebudem rano sa ozvem ... Dik

**Comment by mtester270** [comment]
[utf_32_le.py.txt](https://github.com/mx3L/archivczsk/files/1537048/utf_32_le.py.txt)
[utf_32.py.txt](https://github.com/mx3L/archivczsk/files/1537050/utf_32.py.txt)

Skus este toto si nahrat a nasledne restart prijmaca
/usrlib/python2.7/encodings/
[Karty Skylink.pdf](https://github.com/mx3L/archivczsk/files/1537047/Karty.Skylink.pdf)

Aj ked je fakt divne co ti to robi lebo jeden clovek to testoval na dm7020 ale mal tam oe2.5 a vraj mu vsetko islo ... Skusal si aj ine doplnky ci funguju alebo nie?

**Comment by aaabaloo** [comment]
Dakujem, vecer vyskusam ked pridem z prace a dam obratom vediet.  Robi mi to aj na inych, skusal som TA3 aj STV napriklad. Ja OE 2.5 nemozem vobec pouzit, ten clovek ma evidentne 7020HD v2, ja mam jeho predchodcu. Vecer sa teda ozvem, dakujem.

**Comment by mtester270** [comment]
ok, tak ja mam v boxoch spanielsku dedinu a v DM duplo.

Takze za mna by som to tipol na kniznicu TWISTED toto ale moze nadvazovat na dalsie problemy atd takze tu uz neporadim treba len experimentovat. Co sa tyka verzie 0.73 tak ta ti funguje pravdepodobne preto lebo tam sa nepouziva twisted.
a mozno bude problem aj tu /usr/lib/python2.7/re.py", line 186, in finditer fakt netusim...
[util.py.txt](https://github.com/mx3L/archivczsk/files/1538512/util.py.txt)



/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 551


dal som ti tu aspon to ze ti zaloguje co tam pride a nad cim robi regex aby si si mohol skusat ... cize klasika premenut txt nahraj a restart ... hladaj string get_streams_from_manifest data:

**Comment by aaabaloo** [comment]
Skusil som ten patch na "twisted", ale potom uz box ani nebootne. Kaslem teda na to vraciam sa k starej verzii. Dakujem za ochotu, pekny vecer.

**Comment by mtester270** [comment]
Prosim ta este skus ten util.py nahradit v tej verzii 1.0 a posli mi log len pre zauimavost cchcem vidiet co ti tam pride

**Comment by aaabaloo** [comment]
Paci sa, pekny den.
[archivCZSK.log](https://github.com/mx3L/archivczsk/files/1541854/archivCZSK.log)

**Comment by mtester270** [comment]
/usr/lib/python2.7/site-packages/twisted/web/client.py:1375:readBody

Tu je problem cize ako som predpokladal je to problem twisted kniznice v tvojom image. Skusil by som nieco taketo
 opkg update
Neviem ako to mas vo svojom cez dpkg

Ak to neaktualizuje tak by som hladal po webe novsiu verziu pre tvoj pristroj alebo len skusit prehodit len ten client.py ale to som niekde cital ze to pomoze ale len z casti.

Takze zatvaram lebo inak uz neviem pomoct.

Uzi si sviatky cau
