### ISSUE TITLE
booklet filmu v zozname v1.0

### ISSUE THREAD

**Issue by frenky55** [mx3L/archivczsk#58]
Dreambox 525
openatv-6.1-dm520-20171206
-nezobrazuje booklet filmu v zozname

[archivCZSK.log](https://github.com/mx3L/archivczsk/files/1536569/archivCZSK.log)

**Comment by mtester270** [comment]
Errno 28] No space left on device

A teda daj si nastavenia archivu 3 zalozka 'cesta' a zmen si cestu  Plagaty stahovat do a daj ulozit.

Virtualna klavesnica je nejaka posahana v tvojom image takze asi neodporucam pozuivat bohuzial nic stym nespravim.

**Comment by frenky55** [comment]
Ďakujem 
Este sem hodim log, z originalneho DM image, tam je celkovo plugin menej stabilny, teraz sa mi po inštalácii pluginu dreambox nerozbehol
