### ISSUE TITLE
Některé moduly nejsou dostupné  - Twisted require zope.interface 3.6.0. or leter

### ISSUE THREAD

**Issue by HanzusCZ** [mx3L/archivczsk#59]
Dobrý den. Mě se to po instalaci verze 1 v menu vůbec neukáže a v modulech to vyhodí chybu 👍  Některé moduly nejsou dostupné
Extensions/PiconManager (Twisted require zope.interface 3.6.0. or leter)
Extensions/SubsSupport (Twisted require zope.interface 3.6.0. or leter)
Extensions/SatipClient (Twisted require zope.interface 3.6.0. or leter)
Extensions/RemoteChannelStreamConvertor (Twisted require zope.interface 3.6.0. or leter)
Extensions/OpenWebif (Twisted require zope.interface 3.6.0. or leter)
Extensions/archivCZSK (Twisted require zope.interface 3.6.0. or leter)
Image mám VTI 8 .  twisted-16-2-0-fix.ipk   jsem zkoušel.

**Comment by mtester270** [comment]
Kedze pouzivas VTi tak ti doporucujem prejst na verziu VTi11 je stabilna a vsetko tam funguje.

Nechci po mne aby som tu riesil systemove veci tvojho stareho image. Bud si aktualizuj image alebo nepouzivaj tuto verziu pluginu.
