### ISSUE TITLE
Vti 11.0.2

### ISSUE THREAD

**Issue by ganco47** [mx3L/archivczsk#61]
V mojom boxe Vu+solo4K a image Vti team 11.0.2 nefunkcne pretacanie

**Comment by mtester270** [comment]
Asi ti nieco chyba, daj si nastavenia zalozka "Prehravac" zobrazit info o prehravaci a nieco ti tam bude chybat, hladaj po forach najdes komplet navod. Alebo si zapni debug a budes vidiet aky konkretny subor ti chyba stiahnes si ho nastavis chmod 755 restart box a hotovo.

Inac na vti11 a VU aj 4k to bolo testovane a vsetko funguje

**Comment by elam25** [comment]
Ahoj.
Mam VU+solo2, vo verzii 0,74 po inštalacii mi Sosač fungoval, teraz tam bola aktualizovaná Stream Cinema a od toho momentu nefunguje Sosač. Načita film a potom hláška chyba archívu... To isté sa deje aj na ta3...ak sa dá pozrite sa na to...Ďakujem
[archivCZSK.log](https://github.com/mx3L/archivczsk/files/1545797/archivCZSK.log)

**Comment by mtester270** [comment]
Je tam chybny resolver v pondelok bude opravene

**Comment by elam25** [comment]
Ďakujem za opravu Sosáča. elam

**Comment by mtester270** [comment]
kedze nic nepises ganco tak zatvaram lebo asi ti to ide

**Comment by ganco47** [comment]
Ospravedlnujem sa, nebol som tu dlhssi cas, ale uz je to vsetko v poriadku, chyba bola u mna, preinstaloval som subssupport a alles is OK :-), dakujem pekne
