### ISSUE TITLE
Nefunkční titulky

### ISSUE THREAD

**Issue by Sniffer26** [mx3L/archivczsk#62]
Zdravím. Mám VU Zero VTI 13 a na strem_cinema se mi nenačtou automaticky titulky. Má to nějaké řešení ?
Děkuji.

**Comment by mtester270** [comment]
Titulky su len pri niektorych streamoch ak su tam validne titulky tak pri vybere streamu vidis
 ...[EN tit]...
Napr film Detroit. Je to momentalne len na vybere stremu casom sa to mozno zmeni. Pokial tam danu vec nevidis tak bud tam nie je alebo je zle nastavena ale toto je zalezistost nie mna.
Titulky si tam samozrejme vies dotiahnut cez subssupport.
