### ISSUE TITLE
Nejdou doplňky Drtinová Veselovský TV a iVysilani

### ISSUE THREAD

**Issue by 1801** [mx3L/archivczsk#64]
Už ňákou dobu nejdou doplňky Drtinová Veselovský TV a iVysilani, mohli by jste je opravit? předem moc díky

**Comment by 1801** [comment]
jen doplním že mám nejnovější verzi pluginu Archiv cz-sk 1.0.1, vše odtaní mi v něm funguje

**Comment by mtester270** [comment]
Na toto ti fakt inac neodpoviem... Ahoj
