### ISSUE TITLE
nejdou nejnovější verze doplňků Drtinová Veselovský TV a iVysilaní

### ISSUE THREAD

**Issue by 1801** [mx3L/archivczsk#65]
v nejnovější verzi pluginu archiv-czsk mi nejdou nejnovější verze doplňků Drtinová Veselovský TV a iVysilaní, po zahájení přehrávání videí mi to píše "Chyba, chyba archivu, autor jej musí opravit", nevíte někdo zde se dá s tím něco udělat? aby zase tyto doplňky fungovali

**Comment by mtester270** [comment]
Doplnky funguju ako maju problem je u tvojho experimental image co pouzivas takze zmen image. A poprosim ta uz tu nepis to iste. Dakujem a prajem este pekne sviatky.
