### ISSUE TITLE
Navrh funkcionality :)

### ISSUE THREAD

**Issue by noman256** [mx3L/archivczsk#67]
Ahoj,
predem Vam chci podekovat za Vasi praci,usili a rychlost pri oprave a odladovani. Dobra prace! 
Mel bych navrh na novou funkcionalitu.  Moznost vytvaret zastupce v hlavnim menu pro dane moduly. Treba zasadit do hlavniho menu primy odkaz na Archivczsk/Videodoplnky/Stream-cinema/Filmy 
Archivczsk/TV doplnky/iVysilani

Co si o tom myslite?

S pozdravem a diky za reakci,

Petr

**Comment by mtester270** [comment]
Ako napad fajn ked pozuivas len SC avsak sa mi nad tym fakt nechce travit cas lebo by to nebolo jednoduche spravit a neviem ci vobec by to bolo mozne.
Pekne sviatky
