### ISSUE TITLE
zelenáč 

### ISSUE THREAD

**Issue by frenky55** [mx3L/archivczsk#68]
![crash](https://user-images.githubusercontent.com/14328764/34454666-3fcb8afa-ed70-11e7-9bc0-01154a233825.jpg)

Keď vojdem do menu titulky pri prehravaní filmu cez stream cinema.

je to .deb verzia

**Comment by mtester270** [comment]
Treba ti toto naistalovat preinstalovat
      dpkg -i https://github.com/mx3L/archivczsk/releases/download/v1.0/enigma2-plugin-extensions-subssupport_OE2.5_1.5.6-r0.2_all.deb

**Comment by frenky55** [comment]
Vďaka, menu funguje, keď v ňom vyberiem titulky nezobrazuje ich.

**Comment by mtester270** [comment]
To uz ti ja nepomozem, chod na forum a pytaj sa ludi co maju tvoj dreambox. Ja DM nemam takze neporadim.
