### ISSUE TITLE
dm7080 oe3.5 original

### ISSUE THREAD

**Issue by Petriiik** [mx3L/archivczsk#69]
ahoj
original image od dreamboxu
nainstaluju sa v poriadku ale pri pokuse o spustenie v menu napise ze nieje nainstalovane subsuport a nezobrazi sa. negeneruje sa ziaden log.

root@dm7080:/tmp# dpkg -i subssupport_1.5.5-20170116_all.deb 
Selecting previously unselected package enigma2-plugin-extensions-subssupport.
(Reading database ... 13418 files and directories currently installed.)
Preparing to unpack subssupport_1.5.5-20170116_all.deb ...
Unpacking enigma2-plugin-extensions-subssupport (1.5.5-20170116) ...
Setting up enigma2-plugin-extensions-subssupport (1.5.5-20170116) ...
found python2.7
root@dm7080:/tmp# dpkg -i enigma2-plugin-extensions-subssupport_OE2.5_1.5.6-r0.2_all.deb 
(Reading database ... 13849 files and directories currently installed.)
Preparing to unpack enigma2-plugin-extensions-subssupport_OE2.5_1.5.6-r0.2_all.deb ...
Unpacking enigma2-plugin-extensions-subssupport (1.5.6-r0.2) over (1.5.5-20170116) ...
Setting up enigma2-plugin-extensions-subssupport (1.5.6-r0.2) ...
found python2.7
root@dm7080:/tmp# dpkg -i archivczsk_1.0-20171205.deb                          
Selecting previously unselected package enigma2-plugin-extensions-archivczsk.
(Reading database ... 13902 files and directories currently installed.)
Preparing to unpack archivczsk_1.0-20171205.deb ...
Unpacking enigma2-plugin-extensions-archivczsk (1.0) ...
Setting up enigma2-plugin-extensions-archivczsk (1.0) ...
Installation for mips32el platform
Installing pngquant...
Installing neccessary Python libraries
Found Python 2.7
Removing temp folder...
Installation of archivCZSK was successfull
root@dm7080:/tmp# reboot

**Comment by mtester270** [comment]
Skus toto ak nepojde tak bohuzial ja ti uz nepomozem
Samozrejme stare daj uninstall

[enigma2-plugin-extensions-subssupport_OE2.5_1.5.6-r0.2_all.deb.zip](https://github.com/mx3L/archivczsk/files/1733879/enigma2-plugin-extensions-subssupport_OE2.5_1.5.6-r0.2_all.deb.zip)

**Comment by mtester270** [comment]
No reaction ... Takze zatvaram
