### ISSUE TITLE
problém s inštalaciou

### ISSUE THREAD

**Issue by frenky55** [mx3L/archivczsk#72]
root@dm520:~# opkg install http://github.com/mx3L/archivczsk/releases/download/v1.0/archivczsk_1.0-20171205.ipk
Downloading http://github.com/mx3L/archivczsk/releases/download/v1.0/archivczsk_1.0-20171205.ipk.
Collected errors:
 * calculate_dependencies_for: Cannot satisfy the following dependencies for enigma2-plugin-extensions-archivczsk:
 *      gstreamer1.0-plugins-bad-fragmented *
 * opkg_solver_install: Cannot install package enigma2-plugin-extensions-archivczsk.
root@dm520:~#

openatv-6.2-dm520-20180224

**Comment by mtester270** [comment]
Problem open atv to snad je viditelne z toho "krasneho" console vypisu co si poslal. Takze bud napis chlapcom z OpenAtv alebo zmen image alebo si ten plugin manualne nahod do pristroja.
