### ISSUE TITLE
Crash po zadani login a stlaceni zeleno tlacitka(OK) v nastaveni Stream Cinema

### ISSUE THREAD

**Issue by kukinko** [mx3L/archivczsk#73]
openATV 6.1

00:00:31.8011 {   } Components/ActionMap.py:46 action action ->  ColorActions green
00:00:31.8044 { E } Plugins/Extensions/archivCZSK/__init__.py:87 writeLog ####ArchivCZSK#### [ERROR] OK VirtualKeyBoardCFG failed.
Traceback (most recent call last):
  File "/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/gui/menu.py", line 237, in ok
    self.close(removeDiac(self.text), self.configEntry)
AttributeError: 'VirtualKeyBoardCFG' object has no attribute 'text'
00:00:31.8049 {   } Plugins/Extensions/archivCZSK/__init__.py:87 writeLog 
00:00:31.8053 { D } Traceback (most recent call last):
00:00:31.8055 { D }   File "/usr/lib/enigma2/python/Components/ActionMap.py", line 68, in action
00:00:31.8061 { D }   File "/usr/lib/enigma2/python/Components/ActionMap.py", line 48, in action
00:00:31.8065 { D }   File "/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/gui/menu.py", line 237, in ok
00:00:31.8076 { D }     self.close(removeDiac(self.text), self.configEntry)
00:00:31.8082 { D } AttributeError: 'VirtualKeyBoardCFG' object has no attribute 'text'
00:00:31.8084 [ E ] python/python.cpp:209 call [ePyObject] (PyObject_CallObject(<bound method NumberActionMap.action of <Components.ActionMap.NumberActionMap instance at 0x701a86e8>>,('ColorActions', 'green')) failed)

**Comment by mtester270** [comment]
Chyba openatv nic stym nespravim len odporucim zadavat udaje cez numericke tlacitka na ovladaci "nokia 3310 pisanie sms" resp. v pripade skusenejsich uziv. nastavit v settings subore navod si najdes na nete.

**Comment by petrkr** [comment]
Neni to chyba v OpenATV (ani v jinem jinem enigma2 based systemu). V jinych pluginech (treba youtube plugin) tato virtualni klavesnice funguje v poradku.

Problem je na radku, kde se odkazujes na "self.text", ktery ale neexistuje. Jelikoz to mas closed-source, tak se ti neda ani pomoct s debugem. Nicmene sem nasel nejake starsi kody, kde mas (https://github.com/mx3L/archivczsk/blob/71407f392400dbfb0e262b41a75ba7b7f10ea8fe/build/plugin/src/gui/menu.py#L237)

Na kterem to pravdepodobne pada (sice ume to pise cislo radku 157, a tendle je 237, ale jak pisu, starsi verze).

Zkusil bych pouzit tuto konstrukci (odkoukano z jinych pluginu, ktery pouzivaji VirualKeyboard taky):
```pycon
self["text"].getText()
```
napr. youtube plugin: 

(https://github.com/Taapat/enigma2-plugin-youtube/blob/c95200ad08018951b41caa43c92a37d4ff3a21c5/src/YouTubeSearch.py#L42)

Petr

**Comment by mtester270** [comment]
A co ti brani to prepisat a vyskusat? Ja uz na tomto nerobim a taktiez Atv nepouzivam. Potom uz len napisat autorovi nech vam vypublikuje novu verziu ak to pomoze ;-)

**Comment by petrkr** [comment]
Branime to, ze nemam zdrojove kody, protoze nejsou open source. Tyto co sem posilal jsou 2 roky stare a neudrzovane. Verzi kterou mam je pouze v "pyc"  kompilovane verzi... Nejak se v tech repozitarich nevyznam, je to stejne zmateny jako cela enigma2 a open aliance.. nikdy nevim ktere repo je to co me vlastne sestavuje image :)

**Comment by mtester270** [comment]
Pisete to v repozitary pre archivczsk kde su kody dostupne. Pokial mate premium verziu tak to pisete na zlom mieste. Myslim ze nie je tazke najst spravy repozitar ci?

**Comment by petrkr** [comment]
Cekam, ze premium je pouze placena verze tohoto, mimo to v premium zdrojove kody nejsou. Nevim jake mate mezi sebou vazby... Napisu tedy stejny bugreport tam.
