### ISSUE TITLE
otvaranie/nacitavanie Stream Cinema CZ/SK - trva 45 sekund kazda jedna vnorena stranka/polozka pluginu

### ISSUE THREAD

**Issue by jkotvan** [mx3L/archivczsk#74]
Pripojenie cez LAN - UPC Slovensko opticky internet 200 Mb/s
Satelitny prijmac - VU+ Zero, image OpenATV 6.1 najnovsia aktualizacia, CZ SK doplnky v.1.0.7 a Stream Cinema v.1.2.6
popis chyby: otvaranie/nacitavanie Stream Cinema CZ/SK - trva 45 sekund kazda jedna vnorena stranka/polozka pluginu pri vypnutej funkcii zobrazit Plagat filmu
Ak je funkcia zobrazit Plagat filmu zapnuta je to este horsie a nacitava 45 sekund kazdy jeden film v zozname pri posune po jednotlivych filmoch

ping zdroju https://stream-cinema.online je priemerne 17 ms

tracert zdroju https://stream-cinema.online
root@vuzero:~# traceroute 104.28.4.57
traceroute to 104.28.4.57 (104.28.4.57), 30 hops max, 38 byte packets
 1  compalhub.home (192.168.0.1)  1.357 ms  1.001 ms  0.900 ms
 2  84.116.232.13 (84.116.232.13)  13.943 ms  13.716 ms  14.765 ms
 3  sk-bts04a-rd1-ae13-0.aorta.net (84.116.233.37)  14.512 ms  14.362 ms  12.024                  ms
 4  sk-bts03a-ri1-ae0-0.aorta.net (84.116.135.162)  14.966 ms  11.616 ms  14.835                  ms
 5  213.46.181.14 (213.46.181.14)  14.961 ms  13.278 ms  14.859 ms
 6  xe-1-0-0.cr0-vie2.ip4.gtt.net (141.136.107.149)  15.234 ms  19.834 ms  23.18                 6 ms
 7  cloudflare-gw.cr0-vie2.ip4.gtt.net (141.136.101.206)  13.911 ms  17.263 ms                   19.030 ms
 8  104.28.4.57 (104.28.4.57)  14.256 ms  13.567 ms  17.559 ms
Trace complete.

Pripojenie cez Orange Mobilny internet 4G

A tu nastava moj problem. Ked som pripojeny cez ovela pomalsie mobilne internetove pripojenie od ineho poskytovatela ktorym je Orange Slovensko tento problem nemam s dlhym otvaranim Stream Cinema ani vnorenych poloziek a dokonca mozem mat zapnutu aj funkciu  zobrazit Plagat filmu a vsetko ide okamzite bez 45 sekundoveho nacitavania ktore mam len na ovela rychlejsom optickom internete od UPC. Poprosim o radu pripadne postup dalsej diagnostiky mojho problemu.

ping zdroju https://stream-cinema.online je priemerne 157 ms

Tracing route to stream-cinema.online [104.28.5.57]
over a maximum of 30 hops:

  1     5 ms     3 ms     3 ms  192.168.43.1
  2    79 ms    37 ms    37 ms  192.168.210.37
  3    76 ms    33 ms    36 ms  192.168.101.41
  4    43 ms    28 ms    40 ms  192.168.101.157
  5    31 ms    29 ms   140 ms  192.168.101.158
  6    50 ms    38 ms    38 ms  192.168.192.9
  7     *        *        *     Request timed out.
  8   278 ms    35 ms    40 ms  213-151-193-189.static.orange.sk [213.151.193.189]
  9   297 ms    38 ms    43 ms  213-151-198-26.static.orange.sk [213.151.198.26]
 10   326 ms    44 ms    37 ms  cloudflare.peering.cz [91.213.211.102]
 11   284 ms    37 ms    46 ms  104.28.5.57
Trace complete.

**Comment by mtester270** [comment]
1) pozri si kolko volneho miesta ma Zero ak je to pod 15mb tak toto moze byt kamen urazu ... Tu len cista instalacia vti11.0.2 odporucam
2) v zasade si si odpovedal problem moze byt tvoj internet resp. tvoja siet ako to mas pospajane tu ti mozem poradit len
telnet na box (putty) a tam si napis prikaz
curl -v  https://stream-cinema.online/kodi/Movies

A sleduj kolko trva response.

PS: tvoja analyza je z vacsej miery na dve veci takze doporucujem studovat

**Comment by jkotvan** [comment]
1. pripojenie je cez LAN, router som dal do default je to UPC cize tam nie je co riesit to je blbovzdorne pripojenie a v routri sa neda pomaly nic nastavit okrem Firewall ktory som skusal aj vypnut ale nepomohlo to. Miesta mam 95 MB volneho v zariadeni. Miesto nebude problem nakolko na mobilnom internete to ide hned a bez problemov.
2. V routri mam momentalne len toto jedno zariadenie a je na priamo spojene kablom ktory som skusal aj menit. Pripajam vypis z cURL ak by ste sa na to mohli pozriet ci tam nieco nesedi.

Odozva pri zadani curl -v https://stream-cinema.online/kodi/Movies bola 10 sekund od zaciatku do skoncenia prikazu

root@vuzero:~# curl -v https://stream-cinema.online/kodi/Movies
*   Trying 2400:cb00:2048:1::681c:439...
* TCP_NODELAY set
*   Trying 104.28.5.57...
* TCP_NODELAY set
* Connected to stream-cinema.online (104.28.5.57) port 443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-ECDSA-AES128-GCM-SHA256
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: C=US; ST=CA; L=San Francisco; O=CloudFlare, Inc.; CN=stream-cinema.online
*  start date: Jan 25 00:00:00 2018 GMT
*  expire date: Jan 25 12:00:00 2019 GMT
*  subjectAltName: host "stream-cinema.online" matched cert's "stream-cinema.online"
*  issuer: C=US; ST=CA; L=San Francisco; O=CloudFlare, Inc.; CN=CloudFlare Inc ECC CA-2
*  SSL certificate verify ok.
> GET /kodi/Movies HTTP/1.1
> Host: stream-cinema.online
> User-Agent: curl/7.53.1
> Accept: */*
>
< HTTP/1.1 200 OK
< Date: Sun, 08 Apr 2018 09:28:37 GMT
< Content-Type: application/json; charset=utf-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< Set-Cookie: __cfduid=d1eb770b81b7b9c94ddb5f51c2962991f1523179717; expires=Mon, 08-Apr-19 09:28:37 GMT; path=/; domain=.stream-cinema.online; HttpOnly
< Content-Security-Policy: upgrade-insecure-requests; default-src https:; script-src https: 'unsafe-inline' 'unsafe-eval'; style-src https: 'unsafe-inline'; img-src https: data:;
< Set-Cookie: session=4mctrjo9ialvcck9i4mqoigav1i5qq9g62vaj8j9djdofi96vk2j6u9hn7dsrv7aq82n7ce019oeka8r20uinihh3g4emt28745ebt3; path=/; HttpOnly
< Expires: Thu, 19 Nov 1981 08:52:00 GMT
< Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
< Pragma: no-cache
< Access-Control-Allow-Origin: "*"
< Vary: Accept-Encoding
< Access-Control-Allow-Headers: origin,range,accept-encoding,referer
< Access-Control-Allow-Methods: GET, HEAD, OPTIONS
< Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
< Server: cloudflare
< CF-RAY: 4083b4717d198c76-VIE
<
* Connection #0 to host stream-cinema.online left intact
{"menu":[{"type":"dir","title":"Kontaktujte prosim autora pluginu.","url":"\/"}]}root@vuzero:~#

3. https mam vypnute myslim ze je to defaultne vypnute

tracert analyze som tam daval na to aby sa dali porovnat pripojenia UPC kde to blbne a Orange kde to ide v poriadku. Vyzera to na zahadu pripojenia UPC niekde po ceste mozno ale nerozumiem preco kedze ping aj tracert su z mojho pohladu uplne v poriadku a ovela rychlejsie ako na Orange mobilnom internete. Mozno UPC spojenie ide cez nejaky uzol ktory to vyrazne spomaluje som dufal ze sa s tym uz niekto stretol pripadne podla tracert vydedukoval problem aby som to mohol reklamovat u UPC.

Odozvna pri pripojeny cez wifi dongle a Orange mobilny 4g internet pri zadani priakzu curl -v https://stream-cinema.online/kodi/Movies bola v podstate nulova.

Cize vyzera ze tu bude zadrhel na strane UPC ale ako zistit preco mi to na optickom internete od UPC ktory x krat rychlejsi dava taku dlhu odozvu ? Cez pripojenie UPC mi to dalo cez curl prvy riadok adresu v tvare IPV6 az potom 4 nemoze byt tam problem ? Ked som isiel cez Orange tak mam hned ako prve len IPV4 adresu 104.28.4.57.

root@vuzero:~# curl -v https://stream-cinema.online/kodi/Movies
*   Trying 104.28.4.57...
* TCP_NODELAY set
* Connected to stream-cinema.online (104.28.4.57) port 443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-ECDSA-AES128-GCM-SHA256
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: C=US; ST=CA; L=San Francisco; O=CloudFlare, Inc.; CN=stream-cinema.o                                                                                                                     nline
*  start date: Jan 25 00:00:00 2018 GMT
*  expire date: Jan 25 12:00:00 2019 GMT
*  subjectAltName: host "stream-cinema.online" matched cert's "stream-cinema.onl                                                                                                                     ine"
*  issuer: C=US; ST=CA; L=San Francisco; O=CloudFlare, Inc.; CN=CloudFlare Inc E                                                                                                                     CC CA-2
*  SSL certificate verify ok.
> GET /kodi/Movies HTTP/1.1
> Host: stream-cinema.online
> User-Agent: curl/7.53.1
> Accept: */*
>
< HTTP/1.1 200 OK
< Date: Sun, 08 Apr 2018 09:37:34 GMT
< Content-Type: application/json; charset=utf-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< Set-Cookie: __cfduid=da9eeda6a05d48ae11f05f357d2dba0951523180254; expires=Mon,                                                                                                                      08-Apr-19 09:37:34 GMT; path=/; domain=.stream-cinema.online; HttpOnly
< Content-Security-Policy: upgrade-insecure-requests; default-src https:; script                                                                                                                     -src https: 'unsafe-inline' 'unsafe-eval'; style-src https: 'unsafe-inline'; img                                                                                                                     -src https: data:;
< Set-Cookie: session=gj7fvmapj7tmqjcd2o7akred85o09ahubnkk56qisjr13ji1choenrhac3                                                                                                                     31podhb3nr2o0d8li6gi4nnsdkm1fcdooqdm5tfla7f73; path=/; HttpOnly
< Expires: Thu, 19 Nov 1981 08:52:00 GMT
< Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
< Pragma: no-cache
< Access-Control-Allow-Origin: "*"
< Vary: Accept-Encoding
< Access-Control-Allow-Headers: origin,range,accept-encoding,referer
< Access-Control-Allow-Methods: GET, HEAD, OPTIONS
< Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-c                                                                                                                     gi/beacon/expect-ct"
< Server: cloudflare
< CF-RAY: 4083c18c1f0b7bde-PRG
<
* Connection #0 to host stream-cinema.online left intact
{"menu":[{"type":"dir","title":"Kontaktujte prosim autora pluginu.","url":"\/"}] 

Vopred Dakujem priatelia

**Comment by mtester270** [comment]
Ten response ked trva 10sek je problem, preco je tomu tak neviem, a ak mi prepacis tak si toto ries sam resp. si najdi niekoho kto sa do toho vyzna a pozre ti to u teba doma. A kedze to nie je to chyba pluginu tak zatvaram.

**Comment by jkotvan** [comment]
mozem este otazku prosim ? ked som zmenil v subore shortcuts.xml cestu na <params cp="czsklib" list="104.28.4.57/kodi/Movies/popular" tak mi otvara vsetko do 10 sekund co je urcite zlepsenie minimalne o pol minuty ale pri posuvani po jednotlivych filmoch mi kazdy info plus plagat nacitava 10 sekund.  Je este niekde v subore odkaz na stream-cinema.online ktory by som si zmeil na IP adresu prosim ? tiez neviem preco sa pri kazdom filme nacitava info 10 sekund ked by sa to malo davkovo stiahnut na zaciatku ako mi pisali fore:
 zobrazený seznam se ze serveru stream-cinema načítají jako dávka, tzn. máš-li zobrazený seznam filmů, tak se při přecházení od jednoho filmu k druhému už nic ze serveru steram-cinema nepřenáší. To za prvé. SC addon používá simplecache modul, takže většina odkazů na servery stream-cinema se vyřídí z této simplecache, pro nová data na server stream-cinema se tedy chodí jen velmi zřídka
