### ISSUE TITLE
Problém s instalací na OpenATV 6.2

### ISSUE THREAD

**Issue by xdedek** [mx3L/archivczsk#75]
při jakékoliv instalaci, ať už přes opkg, či curl balíčku archivu vypíše instalátor chybu:
```
root@enibox:~# opkg install http://github.com/mx3L/archivczsk/releases/download/v1.0/archivczsk_1.0-20171205.ipk
Downloading http://github.com/mx3L/archivczsk/releases/download/v1.0/archivczsk_1.0-20171205.ipk.
Collected errors:
 * calculate_dependencies_for: Cannot satisfy the following dependencies for enigma2-plugin-extensions-archivczsk:
 *      gstreamer1.0-plugins-bad-fragmented *
 * opkg_solver_install: Cannot install package enigma2-plugin-extensions-archivczsk.
```
předtím mi nějaký z pluginů chyběl, nebo nešel přeinstalovat, ale instalace to ignorovala a pokračovala, nyní ale skončí a nechce pokračovat dále.. co s tím?

**Comment by xdedek** [comment]
Zkoušel jsem to na verzi 2018-04-17 i 15. Obě nejdou. Na starším OATV v. 6.1 z 2018-04-17 běží v pohodě.

**Comment by mtester270** [comment]
Tak este raz a posledny krat chyba zjavne nie je v instalatore pluginu ale v OpenATV6.2 (chyba ti tam gstreamer v systeme pokial ho nemas tak instalator nezbehne lebo ma dependency), viac odomna nechci.

Tu na githube mas navod na manualnu instalaciu do enigmy ktoru by si mal zvladnut.

Howk
