### ISSUE TITLE
In the new versions of VTI currently 13.0.9 archiveCZSK does not work properly

### ISSUE THREAD

**Issue by crosso26** [mx3L/archivczsk#76]
I get following errors:

HTTP Protocol - failed
HLS Protocol - failed

then I tried to reinstall GStreamer plugins according instructions that didnt help either and further errors were reported that some particular installation files were not found in the feed of VTi and are missing.
this is actually happening since version 13.x.x. onwards

secondly markiza TN is not working - I believe due to reason above

please help.
if you need any file listing exact errors, please let me know how to create it.

Thank you

**Comment by mtester270** [comment]
I can't help you with these protocols in VTi 13 (i use VTi 11) so you should found solution on some forum.

About addon Markiza : this doesn't work properly because most of times markiza servers got outage, but you can found archiv log in /tmp/archivCZSK.log and also turn on DEBUG mode in plugin settings before you try to run a TN. But i think your problem related with these protocols.

PS: I hope you use latest version of archivCZSK (1.0.7)

**Comment by crosso26** [comment]
pisal som po EN lebo som videl anglicku stranku ale teraz som si vsimol ze ostatni pisu po slovensky :)

archivCZSK mam samozrejme najnovsiu verziu, ale k tej odpovedi - ked ide na VTi11 mal by ist aj na VTi13 a ked nie tak by to malo byt predmetom pre vyvojarou tohoto pluginu. 

chcem sa spytat kde zapnem ten DEBUG mode, mam to v cestine a neviem to najst
napr. serial milenky mi prehra v pohode a TN dneska vypisal po dlhsom nacitavani ze chyba archivu - autor jej musi opravit

archivCZSK (1.0.7) markiza 1.1.8 z 23.04.18

**Comment by mtester270** [comment]
Bratu a ty si myslis ze mi tu za vyvoj niekto plati sa spamataj 😂

TN po dnesnej oprave funguju avsak niekedy sa stane ze to nenacita takze asi maju tie serveri dost vprdeli takze chod do nastaveni markizy a tam si vypni Nove nacitavanie videa alebo nieco take.

Debug mod zapnes v nastaveniach archivu asi tretia zalozka mod=ladenie

Ako som uz napisal ak ti nejde vo VTi13 tak hladaj pomoc u niekoho ineho.

PS: trosku ucty s tvojej strany by nezaskodilo do buducna, takze zatvaram

**Comment by michalhainc** [comment]
Ten konkretny clovek som mozno ja... ja stale zijem s VTI 13.0.2 a uz raz ma VTI presvedcil ze netreba updatovat nadarmo ak ta nic nepali... lebo potom kadeco nejde... v 13.0.2 s archivom 1.1.x problem nemam ziaden...
