### ISSUE TITLE
Pad VTI 13.0.9

### ISSUE THREAD

**Issue by vatlach** [mx3L/archivczsk#77]
Od urcitej doby sposobuje archivczsk pad image.
V prilohe su logy snad pomozu.
[archivCZSK.log](https://github.com/mx3L/archivczsk/files/2276678/archivCZSK.log)
[dvbapp2_crash_2018-08-10_06-45-20_1533876320.log](https://github.com/mx3L/archivczsk/files/2276679/dvbapp2_crash_2018-08-10_06-45-20_1533876320.log)

**Comment by mtester270** [comment]
Co je od urcitej doby? Robil si update niecoho ci mi chces povedat ze to samo od seba prestalo ist?

A Logy su fajn len este by si mi mohol popisat co kedy ako ti to robi.

**Comment by vatlach** [comment]
Robi to ked rychlo stlacas EXIT,aby si vysiel z archivov.Vtedy to nahodne spadne.Od urcitej doby znamena posledna verzia 1.1.

**Comment by mtester270** [comment]
Tak ti doporucujem nestlacat rychlo exit. Dovod je taky ze ked stlacis exit a archiv nieco stale nacitava tak sa vola zrusenie danej veci cize ked to robis takto jak blazen tak sa to cele posaha.
Zatvaram
