### ISSUE TITLE
Markiza.sk nezobrazuje videa

### ISSUE THREAD

**Issue by michalhainc** [mx3L/archivczsk#78]
Markiza.sk nezobrazuje videa iba kategorie, log prilozim ked sa k tomu dostanem

**Comment by mtester270** [comment]
Markiza mava casto vypadky, nevidim momentalne ziadny problem co popisujes takze zatvaram

**Comment by michalhainc** [comment]
VU+ Zero 4k s imagom VTI 13.0.2 
tu je screenshot ked si to tak "frisko" zavrel... 
Ide o konkretnu kategoriu ale namatkou co som preklikal tak vsetky su takto prazne... idem este vylovit tie logy... 

![image](https://user-images.githubusercontent.com/3962233/44604284-a7d67800-a7e5-11e8-9b16-759abbd9c7e5.png)

**Comment by michalhainc** [comment]
Hmm z nejakeho dovodu mi ponuklo moje vu+ zero 4k s vti 13.0.2 update na verziu archivczsk 1.1.0 az dneska... aj to asi na 3ti krat po vstupe do pluginu z hlavneho menu... ako som pozeral tak 1.1.0 si releasol v juni... a od juna som tento plugin pouzival pomerne casto a nikdy ziaden update... divne ale po update mi markiza archiv ide... diky... dobra praca... keby si potreboval pomoc s vyvojom/maintenancom kludne napis...

**Comment by mtester270** [comment]
Co sa tyka updatu uz som sa stym stretol problem bol hlavne pri prvom spustani, kedy sa github tvaril ze nic nove nema tak proste kod neskoncil ani chybou proste nenasiel update (videl by si v logu ak by si mal mod ladenia Debug), prislo mi to ako problem provider-github. Z tohto dovodu je spravemy hack ak v nastaveniach archivu zmenis auto update je jedno ktory tak to resetne timestamp kedy robil naposledy update nasledne ulozis znova otvoris das spat na auto aktualizaciu vypnes archiv zapnes a v logoch by si mal opat vidiet ze kontroloval updaty toto druhe volanie by malo chodit. Cize necakas 2h resp neresetujes pristroj.

 Pokial chces robit support alebo vyvoj do doplnkov nemam problem kludne nieco mozes poopravovat alebo vylepsit (okrem stream-cinema) nasledne ti mozem spravit merge ak to bude vsetko OK da sa zariadit pristup ze to potom mozes robit aj sam. Kontakt potom asi cez hangout alebo gmail ...
