### ISSUE TITLE
Ve Stream Cinema se mi nezobrazují žádné složky

### ISSUE THREAD

**Issue by pavsla** [mx3L/archivczsk#80]
Už cca 60 h se mi ve Stream Cinema nezobrazují žádné složky, je tam jen jedna složka "BAN 2", poradíte mi kde je chyba, a jak opět zprovoznit Stream Cinema?

**Comment by mtester270** [comment]
Mas BAN na tvoju IP (niekto alebo ty s rovnakou IP robil nieco co sa nema) takze bud zmenit IP alebo napis na kodi forum do sekcie Hlasenie chyb ... resp. PM uzivatelovi BBaron na danom fore
