### ISSUE TITLE
Chyba v načítání videí DVTV

### ISSUE THREAD

**Issue by FoPa8** [mx3L/archivczsk#84]
Po nainstalování Archivu verze 1.1-20180623 chyba v doplňku DVTV:
- správně se načte seznam videí
- po výběru videa se nenačte seznam pro určení kvality přehrávání

VU+ UNO4K  Open ATV 6.2
[archivCZSK.log](https://github.com/mx3L/archivczsk/files/2704146/archivCZSK.log)

**Comment by FoPa8** [comment]
Chci vám poděkovat. Ani jsem v to nedoufal, že se to podaří v tak krátké době. Dnes po aktualizaci DVTV funguje bezchybně.
ArchivCZSK mě vyhovuje mnohem lépe než nabubřelé Kodi. Ještě jednou děkuji.

**Comment by mtester270** [comment]
Cau,
mne nedakuj ja som to len vypublikoval.
Skor sa podakuj ludom z changelog.txt ... boddie2 a spol

Pekny vecer
