### ISSUE TITLE
Cache Stream Cinema a dalších pluginů

### ISSUE THREAD

**Issue by xdedek** [mx3L/archivczsk#86]
Nedávno jsem se přestěhoval z 55M optiky na 10M WiFi. Mám výkonný přijímač Octagon SF4008. Na optice jsem online koukal všelijaké filmy bez problému, ale na wifi se mi často sekají. Vysledoval jsem, co se při zaseknutí děje, z grafů rychlosti na routeru. Nějvětší problém dělají filmy s výrazným variabilním bitratem, prostě wifi od místního poskytovatele není tak "flexibilní", jak by si plugin přál a tím vzniká problém. Totiž když je nějaká na bitrate "pomalá scéna", tak jde vše v pořádku a jakmile se blíží něco rychlého, tak místo rychlého skoku na třeba 8M se rychlost downloadu vyšplhá pomalinku na 6M a film se zaškubne, mezitím se to stihne zrychlit a už se dá zase chvíli sledovat, ale zanedlouho to udělá opět. Řešením by bylo, kdyby se dala nastavit větší cache, například u mého přiímače mám běžně přes 130MB v RAM volno, takže bych si klidně mohl dovolit větší cache. Když dám film stahovat na disk, tak běží celou dobu plnou rychlostí. jen je to ale otrava pro ostatní členy rodiny a nezapomenout jej následně vymazat a taky pak po celou dobu sledování "hučí" disk, to RAM by byly neslyšné. No a další nevýhoda stahování na HDD je ta, že když to začnu sledovat a náhodou dojde na místo, kde to ještě není dostaženo (občas se přibrzdí asi server), tak se přehrávání zasekne, následně musím spustit film znovu a přetočit na to místo. Nedalo by se do pluginu zakomponovat možnost nastavení velikosti cache? Mám dojem, že to tam i kdysi bylo. Případně se hlásím i jako tester beta verze. Díky.

**Comment by mtester270** [comment]
neviem o akom nastaveni hovoris ale mozno myslis toto
ArchivCZSK->Nastavenia->Zalozka:Prehravac->RTMP buffer .. tam si daj nejaku vacsiu hodnotu 

viac ti asi nepomozem

**Comment by hansolo272** [comment]
výkonný přijímač Octagon SF4008 ?
4K arm za 200eury ? deláš si legraci ?
RTMP buffer ti nepomuže 
10MB WiFi ?? co to je ? tak dobrý na meil nebo youtube
potrebuješ kabel a min 30MB 
určite ti to bude ale stačit na sosač ,predplat si a testni 
na s cinemu u filmu nad 5gb fhd zapomen pri dané rychlosti netu
