### ISSUE TITLE
plugin a Merlin3 img

### ISSUE THREAD

**Issue by pe3kf** [mx3L/archivczsk#89]
[log2.txt](https://github.com/mx3L/archivczsk/files/2824888/log2.txt)

Zdravím,
mám problém s pluginom v img Merlin3, ked ho nainštalujem a reštartnem box , tak sa box pred koncom bootovania zasekne. musím bud vymaať plugin, alebo preinštalovať box.
Pripájam log,  možno sa dá z toho nieo vyčítať, kde je problém.
Ď.

**Comment by mtester270** [comment]
uz som ti to predsa napisal na forum co mas skusit, takze zatvaram
