### ISSUE TITLE
Sosac a Befun

### ISSUE THREAD

**Issue by Luky68** [mx3L/archivczsk#9]
nefunguju od vcera neprehravaju ziadny stream pod enigma2

**Comment by mx3L** [comment]
Ahoj, oprava bola dnes pridana, sosac funguje

**Comment by Luky68** [comment]
Pozdravujem.

Ano pod kodi to ide ale pod enigma2 to stale nenabehlo. Uz som skusal vsetko

**Comment by mx3L** [comment]
Fungovalo len zopar serialov, preklep je uz opraveny, po dalsej aktualizacii stream resolver to bude snad ok.

**Comment by ScytheSVK** [comment]
Mne to na vu+ a enigme nejde stale . Robim nieco zle ?
Dakujem

**Comment by mx3L** [comment]
sosac funguje, aspon zopar serialov co som skusal, ak nejaky konkretny nefunguje prosim napis presne ktory serial(epizoda)/film.
Prebehla aktualizacia stream-resolvera po spusteni archivu?

**Comment by ScytheSVK** [comment]
Aktualizacia neprebehla ani raz a nejde vobec nic ziadny film ziadny serial

**Comment by mx3L** [comment]
No tak v tom bude problem
mozes spustit `curl` v prijmaci cez telnet/ssh? Co ti vypise?

**Comment by mx3L** [comment]
v pripade ak curl nie nainstalovany, tak ho treba skusit nainstalovat:
```
opkg update
opkg install curl
```
V pripade ze to zbehne v poriadku aktualizacia by sa mala nainstalovat po naslednom spusteni archivov

**Comment by ScytheSVK** [comment]
nainstaloval som curl podla pokynu

ked ho spustim cez telnet vypise mi

curl : try curl -- manual curl -- help for help

skusal som rebootnut vu+ a znova spustit archivy ale nefunguje to , 
ukaze mi zoznam filmov da mi vybrat aku chcem kvalitu ale potom uz len 
tma

Moze to byt tym ze nemam najnovsiu verziu pluginu archivcz/sk ?

**Comment by mx3L** [comment]
minimalne treba mat 0.72 beta 5 inac aktualizacie fungovat nebudu

**Comment by ScytheSVK** [comment]
Ok skusim nainstalovat a napisem

**Comment by ScytheSVK** [comment]
Dal som najnovsiu verziu reboot a vyzera ze vsetko slape . Dakujem

**Comment by baronbb** [comment]
Aktualizoval jsem stream revolver, na sosaci mi ale stále některá videa nejdou, např. posledni Star wars nebo poslední Star Trek. Po kliknutí na odkaz se nelze dostat na formáty videi.

**Comment by mx3L** [comment]
@ScytheSVK 
vdaka za info

@baronbb
prosim vyskusaj ci tieto videa funguju na Kodi

**Comment by baronbb** [comment]
odzkouseno, na Kodi na android se po kliknuti na oba zminene filmy nabidnou dostupne formaty videi a jdou spustit, video se zacne prehravat.

**Comment by mx3L** [comment]
Za par minut by mala nabehnut aktualizacia stream resolvera

**Comment by baronbb** [comment]
Zdravím a díky za úpravu, včera vecer na sosaci byl výpadek,  dnes již běži, zkusil jsem tedy opět výše uvedené filmy. 
Star Trek- video stream se rovnou spustí a bezi, nenabidne ale dostupné formáty jako na pc (sd a hd) 
Star wars- stále nejde, hlásí nemožnost získat url videa, na pc jde

**Comment by mx3L** [comment]
star trek - je len jeden dostupny format, na Kodi sa objavi aj HD kvalita ale ak ju skusis spustit nefunguje
star wars - opravene v dalsej aktualizacii stream resolvera

aktualizovany je aj sosac podla sosaca na Kodi - funguje vyhladavanie, pridane zanry filmov a nacitavanie zoznamu filmov [A-Z] je teraz takmer okamzite.

**Comment by mx3L** [comment]
Befun je takisto aktualizovany, v nastaveni befunu je nutne este zvysit casovy limit pre nacitavanie, kedze tato stranka je dost pomala a povodnych 15s niekedy nestaci:

![befun](https://cloud.githubusercontent.com/assets/3874649/17552815/80a72686-5f02-11e6-90da-c20c7faeab6c.png)

**Comment by maciii** [comment]
Ahoj. updatoval jsem teď na cca 8 strojích na poslední verzi (nechodil Sosáč :-). Vypozoroval jsem, že po instalaci se to vždy zeptá pouze na aktualizaci balíčku Prima Play (pouze tohoto jednoho pluginu) a až po restartu E2 to nabídne aktualizaci dalších balíčků (včetně Resolver a Sosáč). Průser je ten, že se občas aktualizace těch dalších balíčku nenabídne vůbec a tím pádem se nedostanu dál. Stalo se mi to ve dvou případech (vše totožné stroje VU+ Zero a Open ATV 5.3 v posledním buildu, ale stalo se mi to i na Open ATV 5.1 takže v tom asi problém nebude). Flashoval jsem vždy čistý image a prošlo mi to teď až na potřetí tak nevím kde je problém.

Dá se aktualizace vyvolat nějak ručně?

Mimochodem skvělá práce! Je to dokonalé111

**Comment by mx3L** [comment]
@maciii 
Ahoj, predpokladam ze pouzivas najnovsiu verziu beta.8, takisto ze openatv image ma nainstalovany program curl. Ak je to tak a problem stale pretrvava vytvor prosimta log:
```
init 4
enigma2.sh 2> /tmp/e2.log
```
Spusti archivy a vypni enigma2(restartovat enigma2), Log je /tmp/e2.log potom ho priloz prosimta sem.

1. Ak chces skusit aktualizovat manualne tak vsetky verzie doplnkov mozes najst zazipovane v adresaroch repozitarov, napr. pre xbmc-doplnky:
https://github.com/mx3L/archivczsk-doplnky/tree/master/xbmc-doplnky/repo
2. Potom je potrebne rozbalit tento doplnok na prijmaci do spravneho adresara:
`/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/resources/repositories/xbmc_doplnky/nazov_dopnlku/`
3. restartovat enigma2

**Comment by mmirousek** [comment]
Ahoj 
mám problém při instalaci na VU+ DUO s image OpenPli, přikládám log

root@vuduo:~# opkg install http://dl.bintray.com/mx3l/generic/enigma2-plugin-ext
ensions-subssupport_1.5.4_20151105_all.ipk
Downloading http://dl.bintray.com/mx3l/generic/enigma2-plugin-extensions-subssupport_1.5.4_20151105_all.ipk.
Installing enigma2-plugin-extensions-subssupport (1.5.4_20151105) on root.
Configuring enigma2-plugin-extensions-subssupport.
found python2.7
root@vuduo:~# opkg install http://dl.bintray.com/mx3l/generic/enigma2-plugin-ext
ensions-archivczsk_0.72-beta-8-20160321_all.ipk
Downloading http://dl.bintray.com/mx3l/generic/enigma2-plugin-extensions-archivczsk_0.72-beta-8-20160321_all.ipk.
Installing enigma2-plugin-extensions-archivczsk (0.72-beta-8-20160321) on root.
Installing python-email (2.7.3-r5.3.9) on root.
Downloading http://downloads.pli-images.org/feeds/openpli-4/mips32el/python-email_2.7.3-r5.3.9_mips32el.ipk.
wget: server returned error: HTTP/1.1 404 Not Found
Collected errors:
 * opkg_download: Failed to download http://downloads.pli-images.org/feeds/openpli-4/mips32el/python-email_2.7.3-r5.3.9_mips32el.ipk, wget returned 1.
 * opkg_install_pkg: Failed to download python-email. Perhaps you need to run 'opkg update'?
 * opkg_install_cmd: Cannot install package enigma2-plugin-extensions-archivczsk.

Je nějaká možnost někde najít  knihovny Pythonu potřebné pro chod doplňku ?
dík za odpověď

**Comment by mx3L** [comment]
Ahoj,
Najprv daj `opkg update`, dopisem do navodu. Potom ti to uz takmer zbehlo, az na uvedenu chybu.

Skus restartovat prijmac `shutdown -r now` a znova nainstalovat archivy `opkg --force-reinstall install opkg install http://dl.bintray.com/mx3l/generic/enigma2-plugin-extensions-archivczsk_0.72-beta-8-20160321_all.ipk`

**Comment by mmirousek** [comment]
dík za rychlou odpověď
opkg update jsem právě udělal před dalším pokusem ale restart jsem nedělal
zkusím

**Comment by mx3L** [comment]
Neni zac ;)

**Comment by Rianus** [comment]
Caute.
Mam problem pri instalacii archivczsk
Installing enigma2-plugin-extensions-archivczsk (0.74-20161026) on root.
enigma2-plugin-extensions-archivczsk: unsatisfied recommendation for rtmpdump
Installing python-youtube-dl (2015.04.17-r0.0) on root.
Collected errors:
 * opkg_download_pkg: Package python-youtube-dl is not available from any configured src.
 * opkg_install_pkg: Failed to download python-youtube-dl. Perhaps you need to run 'opkg update'?
 * opkg_install_cmd: Cannot install package enigma2-plugin-extensions-archivczsk.


opkg update som samozrejme skusal, ale nenachadza ten balik.

prijimac je Vu+ Zero, enigma2, Open-Pli 4

Da sa s tym nieco robit ? 
Vdaka.

**Comment by mx3L** [comment]
@Rianus 
To je len odporuceny balicek aby isli chranene youtube videa vo videacesky plugine, archiv by mal fungovat aj bez neho. Momentalne na openpli feedoch chyba..

**Comment by zipo11** [comment]
Čaute borci,  ide vám na enigma 2 sosac a befun vpohode?  Mne to ale pred týždňom nešlo vôbec a teraz idú videá cca 1 minútu a hned má vypne ani sťahovanie nefunguje.  Máte niekto skúsenosti ako to vyriešiť?  Ďakujem

**Comment by ScytheSVK** [comment]
zaplatit. bezplatne uz nejde

**Comment by zipo11** [comment]
A kde nastavím login? V archíve som to nevidel

Dňa 21. 7. 2017 23:23 používateľ "ScytheSVK" <notifications@github.com>
napísal:

> zaplatit. bezplatne uz nejde
>

**Comment by ScytheSVK** [comment]
v kodim sa to da nastaviť cez stlacenim menu na polozke sosac

**Comment by zipo11** [comment]
Kodi viem že ide.  Ale ja mám octagon SF 108 hd s enigmou 2. A tam som
nenašiel žiadne nastavenia loginu a ani funkčné kodi na enigmu

Dňa 21. 7. 2017 23:28 používateľ "ScytheSVK" <notifications@github.com>
napísal:

> v kodim sa to da nastaviť cez stlacenim menu na polozke sosac
>

**Comment by ScytheSVK** [comment]
funkcne kodi ma openvti len neviem ci sa to tam da nainštalovať. ale pokial ma pamat neklame mal nastavenia aj sosac tam kde sa vyberal zdroj sa dal nastavit ci sa myslim?

**Comment by zipo11** [comment]
Neviem čo konkrétne myslíš.  Ja mám linux cca mesiac tak sa len učím,  v
nastaveniach to nevidím ale cez úpravu knižnice sosac_kodi.py by to hádam
mohlo ísť tu som našiel user name aj login.  Skúsim uvidím.  Ďakujem za
rady

Dňa 21. 7. 2017 23:34 používateľ "ScytheSVK" <notifications@github.com>
napísal:

> funkcne kodi ma openvti len neviem ci sa to tam da nainštalovať. ale
> pokial ma pamat neklame mal nastavenia aj sosac tam kde sa vyberal zdroj sa
> dal nastavit ci sa myslim?
>

**Comment by mtester270** [comment]
Stare zatvaram
