### ISSUE TITLE
Add new sources

### ISSUE THREAD

**Issue by pavelschon** [mx3L/archivczsk#90]
Please add new video sources: Mall.tv, iDNES.tv

**Comment by mtester270** [comment]
Bohuzial ja ani kolega na to nemame cas, tak bud to spravis sam alebo si najdes cloveka co ma o to zaujem a spravi to cez pull request. Takze zatvaram

**Comment by pavelschon** [comment]
Kdyz nemas cas, tak to klidne mohlo zustat otevrene, treba si nekdo jiny vsimne.
Jinak je to mrtvy projekt?

**Comment by mtester270** [comment]
Neviem ci si myslis ze ludia nemaju co robit a len robi zadara tak sa
pleties. Robim to len ja aj to len z dobrej vole a na zapracovanie novych
doplnkov nemam cas som pracovne vytazeny. Potom je este jeden chalan co sa
sam prihlasil s ktorym som to samozrjeme konzultoval a tiez na to nema cas
a aj ked by sa nasiel novy clovek tak to nie robota ze sadnem pozrem vidim
a naprogramujem ked neveris tak si to skus ale predpokladam ze netusis o
com je programovanie. Takze preto som to zatvoril.
