### ISSUE TITLE
OpenATV 6.2 a sosac

### ISSUE THREAD

**Issue by sinacik** [mx3L/archivczsk#91]
Taká malá otázočka, či nevieme kde sa ručne zapisuje cez ftp meno a heslo do sosáča. Ak to píšem cez nastavenia skončí to modrou chybou a okná sú prázdne. 

Ďakujem

**Comment by mtester270** [comment]
Nepouzivat virtualnu klavesnicu ale tlacitka 0-9 tak ako na starej nokii
