### ISSUE TITLE
DM920 OE2.5

### ISSUE THREAD

**Issue by pe3kf** [mx3L/archivczsk#93]
Zdravím , mám pár dní nový DM920 , ale nedarí sa mi doň nainštalovať plugin archív czsk.
Do VUčiek to ide v pohode, ale do DM s image OE2.5 nie.
Neviem kde robím chybu, skúšal som image :
dreambox-image-deb-dm920-20190312.tar.xz
gemini4-unstable-OE25-image-dm920-20180921000113.tar.xz
Merlin_OE-2.5-dm920-experimental-20190312.tar.xz
newnigma2-deb-daily-OE2.5-dm920-16_03_2019.tar.xz
ale ani v jednom mi nejde archív.
Robím to rovnako cez putty ako do VUčiek.
###
dpkg -i curl
dpkg -i https://github.com/mx3L/archivczsk/releases/download/v1.1/archivczsk_1.1-20180623.deb
(dpkg -i http://github.com/mx3L/archivczsk/releases/download/v1.0/enigma2-plugin-extensions-subssupport_OE2.5_1.5.6-r0.2_all.deb)
dpkg -i http://github.com/mx3L/archivczsk/releases/download/v1.1/archivczsk_1.1-20180623.deb
init 4
init 3
(alebo: reboot)
###
a toto vypíše v putty:
root@dm920:~# dpkg -i curl
dpkg: error processing archive curl (–install):
cannot access archive: No such file or directory
Errors were encountered while processing:
curl

root@dm920:~# dpkg -i https://github.com/mx3L/archivczsk/releases/download/v1.1/archivczsk_1.1-20180623.deb
dpkg: error processing archive https://github.com/mx3L/archivczsk/releases/download/v1.1/archivczsk_1.1-20180623.deb (–install):
cannot access archive: No such file or directory
Errors were encountered while processing:
https://github.com/mx3L/archivczsk/releases/download/v1.1/archivczsk_1.1-20180623.deb

root@dm920:~# dpkg -i http://github.com/mx3L/archivczsk/releases/download/v1.1/archivczsk_1.1-20180623.deb
dpkg: error processing archive http://github.com/mx3L/archivczsk/releases/download/v1.1/archivczsk_1.1-20180623.deb (–install):
cannot access archive: No such file or directory
Errors were encountered while processing:
http://github.com/mx3L/archivczsk/releases/download/v1.1/archivczsk_1.1-20180623.deb

netuším prečo , ani inštalačka priamo z /tmp sa nechc nainštalovať.
Ď.

**Comment by boddie2** [comment]
Zkus ten curl nainstalovat pres: apt-get install curl

**Comment by pe3kf** [comment]
skúsil som , ale asi nepomohlo:

dm920 login: root
root@dm920:~# apt-get install curl
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following extra packages will be installed:
  libcurl4
The following NEW packages will be installed:
  curl libcurl4
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 202 kB of archives.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] Y
Get:1 http://dreamboxupdate.com/opendreambox/2.5/unstable/r0/dm920/deb/cortexa15hf-neon-vfpv4/ ./ libcurl4 7.47.1-r0.4 [111 kB]
Get:2 http://dreamboxupdate.com/opendreambox/2.5/unstable/r0/dm920/deb/cortexa15hf-neon-vfpv4/ ./ curl 7.47.1-r0.4 [90.6 kB]
Fetched 202 kB in 0s (681 kB/s)
Selecting previously unselected package libcurl4.
(Reading database ... 14849 files and directories currently installed.)
Preparing to unpack .../libcurl4_7.47.1-r0.4_armhf.deb ...
Unpacking libcurl4 (7.47.1-r0.4) ...
Selecting previously unselected package curl.
Preparing to unpack .../curl_7.47.1-r0.4_armhf.deb ...
Unpacking curl (7.47.1-r0.4) ...
Setting up libcurl4 (7.47.1-r0.4) ...
Setting up curl (7.47.1-r0.4) ...
root@dm920:

**Comment by mtester270** [comment]
1) stiahni subssuport aj archiv do PC potom do boxu /tmp
2) spusti instalaciu najskor subssup potom archiv

**Comment by pe3kf** [comment]
...Ďakujem, toto zabralo, aj ked som vedel o tej možnosti neskúsil som ju pretože upozornuješ na nie celkom dobrú funkčnosť...
"Manual (nedoporucujem, mozne problemy)
    stiahnut balicek (.ipk|.deb) a nahrat do setoboxu do adresara /tmp
    cez software setoboxu najst manualne instalovanie balickov a mal by sa objavit dany nazov balicku
    naistalovat a restart setoboxu
    nebude fungovat auto update pokial nie je naistalovany curl "
Tak neviem , či už je to aj týmto spôsobom plne funkčné.

A pečo vlastne nefunguje "dpkg -i curl"

Ď.

**Comment by mtester270** [comment]
Skus cez telnet
curl -V
malo by ti vypisal verziu napr. curl 7.42.1

Pokial nie a napise ti unknown command tak ti nebude fungovat automaticky update takze aktualizaciu doplnkov pripadne archivu musis spravit manualne kde si stiahnes konkretny *.zip subor a prepises v boxe.

Preco tam nemas curl ja neviem a tiez neviem ako ho tam dostat ale mozem ti poradit zmenit image napr openpli tam ten curl je sa mi vidi.

Povazujem za vyriesene takze zatvaram.

**Comment by pe3kf** [comment]
root@dm920:~# curl -V
curl 7.47.1 (arm-oe-linux-gnueabi) libcurl/7.47.1 OpenSSL/1.0.2h zlib/1.2.8
Protocols: file ftp ftps http https
Features: IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP UnixSockets
root@dm920:~#

toto vypísalo, takže curl tam je a update bude fungovať ?

Ď.

**Comment by boddie2** [comment]
A pečo vlastne nefunguje "dpkg -i curl"
dpkg - instaluje balicek
apt-get install curl - stahne balicek z repository a nainstaluje

**Comment by mtester270** [comment]
malo by fungovat, odtestovat to mozes jednoducho
tu: /usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/
prepis: https://webshare.cz/group/6xK7mT4iz4/

daj komplet restart krabice a pusti archiv malo by ti skocit ziadost na update

**Comment by pe3kf** [comment]
....
> Preco tam nemas curl ja neviem a tiez neviem ako ho tam dostat ale mozem ti poradit zmenit image napr openpli tam ten curl je sa mi vidi.
> 

Update zatial funguje.
Čo sa týka iného image, skúšal som aj OpenATV, openPli už asi nerobí podporu pre DM920.
v openatv to išlo cez putty v pohode, ale ja chcem  image s OE2.5 a to majú len origo image zatial.

Ďakujem za pomoc a želám vela dobrých  nápadov a ochotu pracovať na podpore pluginu.
