### ISSUE TITLE
Stream cinema záložky

### ISSUE THREAD

**Issue by baaluu** [mx3L/archivczsk#94]
Mam Open atv 6,2 a pri aktualizacii archivu miznu zalozky stream cinema.Nezobrazi sa mi ani zaloha ktoru znovu nakopirujem do usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/resources/data /tmp/archivczsk.

**Comment by mtester270** [comment]
Na zaklade nedostatocneho mnozstva poskytnutych informacii a dat Vam pomoct neviem.

Zalozky bezne pouzivam a pri online aktualizacii nic nemizne.

**Comment by hansolo272** [comment]
co to máš za prapodivnou cestu ?
v extensions/archivCZSK/resources/
jsou jen libraries+repositories+init py +init pyo  
data mám navolenou cestu /media/usb
a záložky vidno v shortcuts.xml
