### ISSUE TITLE
Stream cinema - vyhhladavanie - virtual keyboard

### ISSUE THREAD

**Issue by cellentano** [mx3L/archivczsk#95]
Zdravim,
VU+ Solo2, OpenATV 6.3 - V stream cinema - vyhladavanie - nefunguje DO, neda sa pisat, na vsetky tlacidla vyskoci okno s ikonou (x), jediny sposob ako z toho von je "natvrdo" vypnut/zapnut prijmac. Debug log prilozeny.
[archivCZSK.log](https://github.com/mx3L/archivczsk/files/3129227/archivCZSK.log)

**Comment by mtester270** [comment]
Tento log je zbytocny, skus pripojit Crash log ak spadla enigma (/media/hdd/crash_*.log) ale skus odfotit obrazovku. Kazdopadne bude asi chyba v ATV6.3. Pokial mas Solo2 tak by som doporucil system VTi 11.

**Comment by cellentano** [comment]
crash log nemam, kedze enigma necreshne ale je iba neovladatelna. Problem nastal po update enigmy, takze to asi bude v nej. Foto prilozene.
![IMG_20190430_075841](https://user-images.githubusercontent.com/25830542/56946036-5d05c080-6b29-11e9-8dde-3724b3d86ac4.jpg)

**Comment by mtester270** [comment]
Tak to ti nemam ako pomoct vratit zalohu ale reinstall systemu. Povazujem za vyriesene, zatvaram
