### ISSUE TITLE
subssupport OE2.5.deb

### ISSUE THREAD

**Issue by forsajd** [mx3L/archivczsk#98]
subssupport mi nejde nainštalovať lebo je pre OE2.5 a ja potrebujem ho dostať do dreamone a ten používa OE2.6, dá sa to nejako po riešiť Dík

**Comment by s3n0** [comment]
Pomohol by nejaký error message, ktorý zobrazuje konzola / Shell pri pokuse o nainštalovanie subsupport balíčka v OE2.6 alebo pomohl by tiež veľmi debug-log záznam (v ktorom bude vidieť, čo za chybu vzniklo pri inštalovaní subsupport balíčka v OE2.6). Zapni niekde v tvojej enigma (Dream One) debug-log a potom keď bude debug aktívny, potom okopíruj do svojho príspevku všetky riadky s chybou inštalácie subsupport pluginu, ktoré sa objavia následne v tomto vygenerovanom LOG-súbore.
