### ISSUE TITLE
premium na viacerych boxoch

### ISSUE THREAD

**Issue by hyllm** [mx3L/archivczsk#99]
zaplatil som premium, ale mam doma 5 boxov s archiv cz/sk (vsetko vu+, sat prijimace v kazdej izbe v dome). ako postupovat??? ci treba platit za kazdy zvlast?

**Comment by mtester270** [comment]
trosku si sa netrafil :D 
https://github.com/mtester270/archivczskpremium/blob/master/README.md
("Klient sa rozumie set-top box.")

**Comment by ganco47** [comment]
mam podobny problem a nikto mi este neodpovedal, hlavne, ze sme zaplatili.....maju nas na haku

**Comment by misanov** [comment]
Brečíte na špatným hrobě, musíte tady https://github.com/mtester270/archivczskpremium ;-)
